AD-02|Canillo
AD-03|Encamp
AD-04|La Massana
AD-05|Ordino
AD-06|Sant Julià de Lòria
AD-07|Andorra la Vella
AD-08|Escaldes-Engordany
AD-U-A|
AE-AJ|Ajman Emirate
AE-AZ|Abu Dhabi Emirate
AE-DU|Dubai Emirate
AE-FU|Fujairah Emirate
AE-RK|Ras al-Khaimah Emirate
AE-SH|Sharjah Emirate
AE-U-A|
AE-UQ|Umm al-Quwain Emirate
AF-BAL|Balkh Province
AF-BAM|Bamiyan Province
AF-BDG|Badghis Province
AF-BDS|Badakhshan Province
AF-BGL|Baghlan Province
AF-DAY|Daykundi Province
AF-FRA|Farah Province
AF-FYB|Faryab Province
AF-GHA|Ghazni Province
AF-GHO|Gh?r Province
AF-HEL|Helmand Province
AF-HER|Herat Province
AF-JOW|Jowzjan Province
AF-KAB|Kabul Province
AF-KAN|Kandahar Province
AF-KAP|Kapisa Province
AF-KDZ|Kunduz Province
AF-KHO|Khost Province
AF-KNR|Kunar Province
AF-LAG|Laghman Province
AF-LOW|Logar Province
AF-NAN|Nangarhar Province
AF-NIM|Nimruz Province
AF-NUR|Nurestan Province
AF-ORU|Or?zg?n Province
AF-PAN|Panjshir Province
AF-PAR|Parwan Province
AF-PIA|Paktia Province
AF-PKA|Paktika Province
AF-SAM|Samangan Province
AF-SAR|Sar-e Pol Province
AF-TAK|Takhar Province
AF-U-A|
AF-WAR|Wardak Province
AF-ZAB|Zabul Province
AG-03|Saint George
AG-04|Saint John
AG-05|Saint Mary
AG-06|Saint Paul
AG-07|Saint Peter
AG-08|Saint Philip
AG-10|Barbuda
AG-U-A|
AI-U-A|
AL-BR|Berat
AL-BU|Bulqizë
AL-DI|Dibër
AL-DL|Delvinë
AL-DR|Durrës
AL-DV|Devoll
AL-EL|Elbasan
AL-ER|Kolonjë
AL-FR|Fier
AL-GJ|Gjirokastër
AL-GR|Gramsh
AL-HA|Has
AL-KA|Kavajë
AL-KB|Kurbin
AL-KC|Kuçovë
AL-KO|Korçë
AL-KR|Krujë
AL-KU|Kukës
AL-LB|Librazhd
AL-LE|Lezhë
AL-LU|Lushnjë
AL-MK|Mallakastër
AL-MM|Malësi e Madhe
AL-MR|Mirditë
AL-MT|Mat
AL-PG|Pogradec
AL-PQ|Peqin
AL-PR|Përmet
AL-PU|Pukë
AL-SH|Shkodër
AL-SK|Skrapar
AL-SR|Sarandë
AL-TE|Tepelenë
AL-TP|Tropojë
AL-TR|Tiranë
AL-U-A|
AL-VL|Vlorë
AM-AG|Aragatsotn Province
AM-AR|Ararat Province
AM-AV|Armavir Province
AM-ER|Yerevan (capital district)
AM-GR|Gegharkunik Province
AM-KT|Kotayk Province
AM-LO|Lori Province
AM-SH|Shirak Province
AM-SU|Syunik Province
AM-TV|Tavush Province
AM-U-A|
AM-VD|Vayots Dzor Province
AN-U-A|
AO-BGO|Bengo Province
AO-BGU|Benguela Province
AO-BIE|Bié Province
AO-CAB|Cabinda Province
AO-CCU|Cuando Cubango Province
AO-CNN|Cunene Province
AO-CNO|Cuanza Norte Province
AO-CUS|Cuanza Sul Province
AO-HUA|Huambo Province
AO-HUI|Huíla Province
AO-LNO|Lunda Norte Province
AO-LSU|Lunda Sul Province
AO-LUA|Luanda Province
AO-MAL|Malanje Province
AO-MOX|Moxico Province
AO-NAM|Namibe Province
AO-U-A|
AO-UIG|Uíge Province
AO-ZAI|Zaire Province
AQ-U-A|
AR-A|Salta Province
AR-B|Buenos Aires Province
AR-C|Capital federal
AR-D|San Luis Province
AR-E|Entre Ríos Province
AR-F|La Rioja Province
AR-G|Santiago del Estero Province
AR-H|Chaco Province
AR-J|San Juan Province
AR-K|Catamarca Province
AR-L|La Pampa Province
AR-M|Mendoza Province
AR-N|Misiones Province
AR-P|Formosa Province
AR-Q|Neuquén Province
AR-R|Río Negro Province
AR-S|Santa Fe Province
AR-T|Tucumán Province
AR-U|Chubut Province
AR-U-A|
AR-V|Tierra del Fuego Province
AR-W|Corrientes Province
AR-X|Córdoba Province
AR-Y|Jujuy Province
AR-Z|Santa Cruz Province
AS-U-A|
AT-1|Burgenland
AT-2|Carinthia
AT-3|Lower Austria
AT-4|Upper Austria
AT-5|Salzburg
AT-6|Styria
AT-7|Tyrol
AT-8|Vorarlberg
AT-9|Vienna
AT-U-A|
AU-AAT|Australian Antarctic Territory
AU-ACT|Australian Capital Territory
AU-NSW|New South Wales
AU-NT|Northern Territory
AU-QLD|Queensland
AU-SA|South Australia
AU-TAS|Tasmania
AU-U-A|
AU-VIC|Victoria
AU-WA|Western Australia
AW-U-A|
AZ-AB|Ali Bayramli
AZ-ABS|Abseron
AZ-AGA|Agstafa
AZ-AGC|Agcabadi
AZ-AGM|Agdam
AZ-AGS|Agdas
AZ-AGU|Agsu
AZ-AST|Astara
AZ-BA|Baki
AZ-BAB|Babak
AZ-BAL|Balakan
AZ-BAR|Barda
AZ-BEY|Beylagan
AZ-BIL|Bilasuvar
AZ-CAB|Cabrayll
AZ-CAL|Calilabad
AZ-CUL|Culfa
AZ-DAS|Daskasan
AZ-DAV|Davaci
AZ-FUZ|Fuzuli
AZ-GA|Ganca
AZ-GAD|Gadabay
AZ-GOR|Goranboy
AZ-GOY|Goycay
AZ-HAC|Haciqabul
AZ-IMI|Imisli
AZ-ISM|Ismayilli
AZ-KAL|Kalbacar
AZ-KUR|Kurdamir
AZ-LA|Lankaran
AZ-LAC|Lacin
AZ-LER|Lerik
AZ-MAS|Masalli
AZ-MI|Mingacevir
AZ-NA|Naftalan
AZ-NEF|Neftcala
AZ-NX|Naxcivan
AZ-OGU|Oguz
AZ-ORD|Ordubad
AZ-QAB|Qabala
AZ-QAX|Qax
AZ-QAZ|Qazax
AZ-QBA|Quba
AZ-QBI|Qubadli
AZ-QOB|Qobustan
AZ-QUS|Qusar
AZ-SA|Saki
AZ-SAB|Sabirabad
AZ-SAD|Sadarak
AZ-SAH|Sahbuz
AZ-SAL|Salyan
AZ-SAR|Sarur
AZ-SAT|Saatli
AZ-SIY|Siyazan
AZ-SKR|Samkir
AZ-SM|Sumqayit
AZ-SMI|Samaxi
AZ-SMX|Samux
AZ-SS|Susa
AZ-TAR|Tartar
AZ-TOV|Tovuz
AZ-U-A|
AZ-UCA|Ucar
AZ-XA|Xankandi
AZ-XAC|Xacmaz
AZ-XAN|Xanlar
AZ-XCI|Xocali
AZ-XIZ|Xizi
AZ-XVD|Xocavand
AZ-YAR|Yardimli
AZ-YE|Yevlax
AZ-ZAN|Zangilan
AZ-ZAQ|Zaqatala
AZ-ZAR|Zardab
BA-BIH|Federacija Bosna i Hercegovina
BA-SRP|Republika Srpska
BA-U-A|
BB-01|Christ Church
BB-02|Saint Andrew
BB-03|Saint George
BB-04|Saint James
BB-05|Saint John
BB-06|Saint Joseph
BB-07|Saint Lucy
BB-08|Saint Michael
BB-09|Saint Peter
BB-10|Saint Philip
BB-11|Saint Thomas
BB-U-A|
BD-1|Barisal Division
BD-2|Chittagong Division
BD-3|Dhaka Division
BD-4|Khulna Division
BD-5|Rajshahi Division
BD-6|Sylhet Division
BD-U-A|
BE-BRU|Brussels-Capital Region
BE-U-A|
BE-VAN|Antwerp
BE-VBR|Flemish Brabant
BE-VLI|Limburg
BE-VOV|East Flanders
BE-VWV|West Flanders
BE-WBR|Walloon Brabant
BE-WHT|Hainaut
BE-WLG|Liège
BE-WLX|Luxembourg
BE-WNA|Namur
BF-BAL|Bale
BF-BAM|Bam
BF-BAN|Banwa
BF-BAZ|Bazega
BF-BGR|Bougouriba
BF-BLG|Boulgou
BF-BLK|Boulkiemde
BF-COM|Comoe
BF-GAN|Ganzourgou
BF-GNA|Gnagna
BF-GOU|Gourma
BF-HOU|Houet
BF-IOB|Ioba
BF-KAD|Kadiogo
BF-KEN|Kenedougou
BF-KMD|Komondjari
BF-KMP|Kompienga
BF-KOP|Koulpulogo
BF-KOS|Kossi
BF-KOT|Kouritenga
BF-KOW|Kourweogo
BF-LER|Leraba
BF-LOR|Loroum
BF-MOU|Mouhoun
BF-NAM|Namentenga
BF-NAO|Nahouri
BF-NAY|Nayala
BF-NOU|Noumbiel
BF-OUB|Oubritenga
BF-OUD|Oudalan
BF-PAS|Passore
BF-PON|Poni
BF-SEN|Seno
BF-SIS|Siasili
BF-SMT|Sanmatenga
BF-SNG|Sanguie
BF-SOM|Soum
BF-SOR|Sourou
BF-TAP|Tapoa
BF-TUI|Tui
BF-U-A|
BF-YAG|Yagha
BF-YAT|Yatenga
BF-ZIR|Ziro
BF-ZON|Zondoma
BF-ZOU|Zoundweogo
BG-01|Blagoevgrad
BG-02|Burgas
BG-03|Varna
BG-04|Veliko Tarnovo
BG-05|Vidin
BG-06|Vraca
BG-07|Gabrovo
BG-08|Dobric
BG-09|Kardzali
BG-10|Kyustendil
BG-11|Lovec
BG-12|Montana
BG-13|Pazardzik
BG-14|Pernik
BG-15|Pleven
BG-16|Plovdiv
BG-17|Razgrad
BG-18|Ruse
BG-19|Silistra
BG-20|Sliven
BG-21|Smoljan
BG-23|Sofia
BG-24|Stara Zagora
BG-25|Targovishte
BG-26|Haskovo
BG-27|Sumen
BG-28|Jambol
BG-U-A|
BH-13|Capital Governorate
BH-14|Southern Governorate
BH-15|Muharraq Governorate
BH-16|Central Governorate
BH-17|Northern Governorate
BH-U-A|
BI-BB|Bubanza
BI-BJ|Bujumbura
BI-BR|Bururi
BI-CA|Cankuzo
BI-CI|Cibitoke
BI-GI|Gitega
BI-KR|Karuzi
BI-KY|Kayanza
BI-MA|Makamba
BI-MU|Muramvya
BI-MW|Mwaro
BI-NG|Ngozi
BI-RT|Rutana
BI-RY|Ruyigi
BI-U-A|
BJ-AK|Atakora
BJ-AL|Alibori
BJ-AQ|Atlantique
BJ-BO|Borgou
BJ-CO|Collines
BJ-DO|Donga
BJ-KO|Kouffo
BJ-LI|Littoral
BJ-MO|Mono
BJ-OU|Oueme
BJ-PL|Plateau
BJ-U-A|
BJ-ZO|Zou
BL-U-A|
BM-U-A|
BN-BE|Belait
BN-BM|Brunei-Muara
BN-TE|Temburong
BN-TU|Tutong
BN-U-A|
BO-B|El Beni
BO-C|Cochabamba
BO-H|Chuquisaca
BO-L|La Paz
BO-N|Pando
BO-O|Oruro
BO-P|Potosí
BO-S|Santa Cruz
BO-T|Tarija
BO-U-A|
BR-AC|Acre
BR-AL|Alagoas
BR-AM|Amazonas
BR-AP|Amapá
BR-BA|Bahia
BR-CE|Ceará
BR-DF|Distrito Federal
BR-ES|Espírito Santo
BR-GO|Goiás
BR-MA|Maranhão
BR-MG|Minas Gerais
BR-MS|Mato Grosso do Sul
BR-MT|Mato Grosso
BR-PA|Pará
BR-PB|Paraíba
BR-PE|Pernambuco
BR-PI|Piauí
BR-PR|Paraná
BR-RJ|Rio de Janeiro
BR-RN|Rio Grande do Norte
BR-RO|Rondônia
BR-RR|Roraima
BR-RS|Rio Grande do Sul
BR-SC|Santa Catarina
BR-SE|Sergipe
BR-SP|São Paulo
BR-TO|Tocatins
BR-U-A|
BS-AC|Acklins and Crooked Islands
BS-BI|Bimini
BS-CI|Cat Island
BS-EX|Exuma
BS-FC|Fresh Creek
BS-FP|Freeport
BS-GH|Governor's Harbour
BS-GT|Green Turtle Cay
BS-HI|Harbour Island
BS-HR|High Rock
BS-IN|Inagua
BS-KB|Kemps Bay
BS-LI|Long Island
BS-MG|Mayaguana
BS-MH|Marsh Harbour
BS-NB|Nicholls Town and Berry Islands
BS-NP|New Providence
BS-RI|Ragged Island
BS-RS|Rock Sound
BS-SP|Sandy Point
BS-SR|San Salvador and Rum Cay
BS-U-A|
BT-11|Paro
BT-12|Chhukha
BT-13|Ha
BT-14|Samtee
BT-15|Thimphu
BT-21|Tsirang
BT-22|Dagana
BT-23|Punakha
BT-24|Wangdue Phodrang
BT-31|Sarpang
BT-32|Trongsa
BT-33|Bumthang
BT-34|Zhemgang
BT-41|Trashigang
BT-42|Monggar
BT-43|Pemagatshel
BT-44|Lhuentse
BT-45|Samdrup Jongkha
BT-GA|Gasa
BT-TY|Trashi Yangtse
BT-U-A|
BW-CE|Central District
BW-GH|Ghanzi District
BW-KG|Kgalagadi District
BW-KL|Kgatleng District
BW-KW|Kweneng District
BW-NE|North-East District
BW-NW|North-West District
BW-SE|South-East District
BW-SO|Southern District
BW-U-A|
BY-BR|Brest Voblast
BY-HO|Homiel Voblast
BY-HR|Hrodna Voblast
BY-MA|Mahilyow Voblast
BY-MI|Minsk Voblast
BY-U-A|
BY-VI|Vitsebsk Voblast
BZ-BZ|Belize District
BZ-CY|Cayo District
BZ-CZL|Corozal District
BZ-OW|Orange Walk District
BZ-SC|Stann Creek District
BZ-TOL|Toledo District
BZ-U-A|
CA-AB|Alberta
CA-BC|British Columbia
CA-MB|Manitoba
CA-NB|New Brunswick
CA-NL|Newfoundland and Labrador
CA-NS|Nova Scotia
CA-NT|Northwest Territories
CA-NU|Nunavut
CA-ON|Ontario
CA-PE|Prince Edward Island
CA-QC|Quebec
CA-SK|Saskatchewan
CA-U-A|
CA-YT|Yukon Territory
CC-U-A|
CD-BC|Bas-Congo
CD-BN|Bandundu
CD-EQ|Equateur
CD-HC|Haut-Congo
CD-KA|Katanga
CD-KE|Kasai-Oriental
CD-KN|Kinshasa
CD-KW|Kasai-Occidental
CD-MA|Maniema
CD-NK|Nord-Kivu
CD-OR|Orientale
CD-SK|Sud-Kivu
CD-U-A|
CF-AC|Ouham
CF-BB|Bamingui-Bangoran
CF-BGF|Bangui
CF-BK|Basse-Kotto
CF-HK|Haute-Kotto
CF-HM|Haut-Mbomou
CF-HS|Mambéré-Kadéï
CF-KB|Nana-Grébizi
CF-KG|Kémo
CF-LB|Lobaye
CF-MB|Mbomou
CF-MP|Ombella-M'Poko
CF-NM|Nana-Mambéré
CF-OP|Ouham-Pendé
CF-SE|Sangha-Mbaéré
CF-U-A|
CF-UK|Ouaka
CF-VR|Vakaga
CG-11|Bouenza
CG-12|Pool
CG-13|Sangha
CG-14|Plateaux
CG-15|Cuvette-Ouest
CG-2|Lekoumou
CG-5|Kouilou
CG-7|Likouala
CG-8|Cuvette
CG-9|Niari
CG-BZV|Brazzaville
CG-U-A|
CH-AG|Aargau
CH-AI|Appenzell Innerrhoden
CH-AR|Appenzell Ausserrhoden
CH-BE|Berne
CH-BL|Basel-Country
CH-BS|Basel-City
CH-FR|Fribourg
CH-GE|Geneva
CH-GL|Glarus
CH-GR|Grisons
CH-JU|Jura
CH-LU|Lucerne
CH-NE|Neuchâtel
CH-NW|Nidwalden
CH-OW|Obwalden
CH-SG|St. Gallen
CH-SH|Schaffhausen
CH-SO|Solothurn
CH-SZ|Schwyz
CH-TG|Thurgau
CH-TI|Ticino
CH-U-A|
CH-UR|Uri
CH-VD|Vaud
CH-VS|Valais
CH-ZG|Zug
CH-ZH|Zurich
CI-01|Lagunes
CI-02|Haut-Sassandra
CI-03|Savanes
CI-04|Vallée du Bandama
CI-05|Moyen-Comoé
CI-06|Dix-Huit Montagnes
CI-07|Lacs
CI-08|Zanzan
CI-09|Bas-Sassandra
CI-10|Denguélé
CI-11|N'zi-Comoé
CI-12|Marahoué
CI-13|Sud-Comoé
CI-14|Worodouqou
CI-15|Sud-Bandama
CI-16|Agnéby
CI-17|Bafing
CI-18|Fromager
CI-19|Moyen-Cavally
CI-U-A|
CK-U-A|
CL-AI|Aisén del General Carlos Ibañez
CL-AN|Antofagasta
CL-AP|Arica and Parinacota
CL-AR|Araucanía
CL-AT|Atacama
CL-BI|Bío-Bío
CL-CO|Coquimbo
CL-LI|O'Higgins
CL-LL|Los Lagos
CL-LR|Los Ríos
CL-MA|Magallanes
CL-ML|Maule
CL-RM|Santiago Metropolitan Region
CL-TA|Tarapacá
CL-U-A|
CL-VS|Valparaíso
CM-AD|Adamaoua Region
CM-CE|Centre Region
CM-EN|Far North Region
CM-ES|East Region
CM-LT|Littoral Region
CM-NO|North Region
CM-NW|North-West Region
CM-OU|West Region
CM-SU|South Region
CM-SW|South-West Region
CM-U-A|
CN-11|Beijing Municipality
CN-12|Tianjin Municipality
CN-13|Hebei Province
CN-14|Shanxi Province
CN-15|Inner Mongolia Autonomous Region
CN-21|Liaoning Province
CN-22|Jilin Province
CN-23|Heilongjiang Province
CN-31|Shanghai Municipality
CN-32|Jiangsu Province
CN-33|Zhejiang Province
CN-34|Anhui Province
CN-35|Fujian Province
CN-36|Jiangxi Province
CN-37|Shandong Province
CN-41|Henan Province
CN-42|Hubei Province
CN-43|Hunan Province
CN-44|Guangdong Province
CN-45|Guangxi Autonomous Region
CN-46|Hainan Province
CN-50|Chongqing Municipality
CN-51|Sichuan Province
CN-52|Guizhou Province
CN-53|Yunnan Province
CN-54|Tibet Autonomous Region
CN-61|Shaanxi Province
CN-62|Gansu Province
CN-63|Qinghai Province
CN-64|Ningxia Autonomous Region
CN-65|Xinjiang Autonomous Region
CN-71|Taiwan (disputed)
CN-91|Hong Kong Special Administrative Region
CN-92|Macau Special Administrative Region
CN-U-A|
CO-AMA|Amazonas
CO-ANT|Antioquía
CO-ARA|Arauca
CO-ATL|Atlántico
CO-BOL|Bolívar
CO-BOY|Boyacá
CO-CAL|Caldas
CO-CAQ|Caquetá
CO-CAS|Casanare
CO-CAU|Cauca
CO-CES|César
CO-CHO|Chocó
CO-COR|Córdoba
CO-CUN|Cundinamarca
CO-DC|Distrito Capital de Bogotá
CO-GUA|Guainía
CO-GUV|Guaviare
CO-HUI|Huila
CO-LAG|La Guajira
CO-MAG|Magdalena
CO-MET|Meta
CO-NAR|Nariño
CO-NSA|Norte de Santander
CO-PUT|Putumayo
CO-QUI|Quindio
CO-RIS|Risaralda
CO-SAN|Santander
CO-SAP|Providencia y Santa Catalina San Andrés
CO-SUC|Sucre
CO-TOL|Tolima
CO-U-A|
CO-VAC|Valle del Cauca
CO-VAU|Vaupés
CO-VID|Vichada
CR-A|Alajuela
CR-C|Cartago
CR-G|Guanacaste
CR-H|Heredia
CR-L|Limon
CR-P|Puntarenas
CR-SJ|San Jose
CR-U-A|
CU-01|Pinar del Río
CU-02|La Habana
CU-03|Ciudad de la Habana
CU-04|Matanzas
CU-05|Villa Clara
CU-06|Cienfuegos
CU-07|Sancti Spíritus
CU-08|Ciego de Ávila
CU-09|Camagüey
CU-10|Las Tunas
CU-11|Holguín
CU-12|Granma
CU-13|Santiago de Cuba
CU-14|Guantánamo
CU-99|Isla de la Juventud
CU-CA|Ciego de Avila
CU-CG|Camagoey
CU-HO|Holgun
CU-IJ|Municipio Especial Isla de la Juventud
CU-PR|Pinar del Roo
CU-SS|Sancti Spritus
CU-U-A|
CV-B|Barlavento Islands
CV-S|Sotavento Islands
CV-U-A|
CX-U-A|
CY-01|Kyrenia District
CY-02|Nicosia District
CY-03|Famagusta District
CY-04|Larnarca District
CY-05|Limassol District
CY-06|Paphos District
CY-U-A|
CZ-JC|South Bohemian Region
CZ-JM|South Moravian Region
CZ-KA|Carlsbad Region
CZ-KR|Hradec Králové Region
CZ-LI|Liberec Region
CZ-MO|Moravian-Silesian Region
CZ-OL|Olomouc Region
CZ-PA|Pardubice Region
CZ-PL|Plze? Region
CZ-PR|Prague (capital city)
CZ-ST|Central Bohemian Region
CZ-U-A|
CZ-US|Ústí nad Labem Region
CZ-VY|Vyso?ina Region
CZ-ZL|Zlin Region
DE-BE|Berlin
DE-BR|Brandenburg
DE-BW|Baden-Württemberg
DE-BY|Bavaria
DE-HB|Bremen
DE-HE|Hesse
DE-HH|Hamburg
DE-MV|Mecklenburg-Vorpommern
DE-NI|Lower Saxony
DE-NW|North Rhine-Westphalia
DE-RP|Rhineland-Palatinate
DE-SH|Schleswig-Holstein
DE-SL|Saarland
DE-SN|Saxony
DE-ST|Saxony-Anhalt
DE-TH|Thuringia
DE-U-A|
DJ-AR|Arta
DJ-AS|Ali Sabiah
DJ-DI|Dikhil
DJ-DJ|Djibouti
DJ-OB|Obock
DJ-TA|Tadjoura
DJ-U-A|
DK-81|North Jutland
DK-82|Central Jutland
DK-83|South Denmark
DK-84|Capital Region
DK-85|Zealand
DK-U-A|
DM-02|Saint Andrew
DM-03|Saint David
DM-04|Saint George
DM-05|Saint John
DM-06|Saint Joseph
DM-07|Saint Luke
DM-08|Saint Mark
DM-09|Saint Patrick
DM-10|Saint Paul
DM-11|Saint Peter
DM-U-A|
DO-01|Distrito Nacional
DO-02|Azua Province
DO-03|Baoruco Province
DO-04|Barahona Province
DO-05|Dajabón Province
DO-06|Duarte Province
DO-07|Elías Piña Province
DO-08|El Seybo Province
DO-09|Espaillat Province
DO-10|Independencia Province
DO-11|La Altagracia Province
DO-12|La Romana Province
DO-13|La Vega Province
DO-14|María Trinidad Sánchez Province
DO-15|Monte Cristi Province
DO-16|Pedernales Province
DO-17|Peravia Province
DO-18|Puerto Plata Province
DO-19|Hermanas Mirabal Province
DO-20|Samaná Province
DO-21|San Cristóbal Province
DO-22|San Juan Province
DO-23|San Pedro de Macorís Province
DO-24|Sánchez Ramírez Province
DO-25|Santiago de los Caballeros Province
DO-26|Santiago Rodríguez Province
DO-27|Valverde Province
DO-28|Monseñor Nouel Province
DO-29|Monte Plata Province
DO-30|Hato Mayor Province
DO-U-A|
DZ-01|Adrar Province
DZ-02|Chlef Province
DZ-03|Laghouat Province
DZ-04|Oum el Bouaghi Province
DZ-05|Batna Province
DZ-06|Béjaïa Province
DZ-07|Biskra Province
DZ-08|Béchar Province
DZ-09|Blida Province
DZ-10|Bouira Province
DZ-11|Tamanghasset Province
DZ-12|Tébessa Province
DZ-13|Tlemcen Province
DZ-14|Tiaret Province
DZ-15|Tizi Ouzou Province
DZ-16|Algiers Province
DZ-17|Djelfa Province
DZ-18|Jijel Province
DZ-19|Sétif Province
DZ-20|Saïda Province
DZ-21|Skikda Province
DZ-22|Sidi Bel Abbes Province
DZ-23|Annaba Province
DZ-24|Guelma Province
DZ-25|Constantine Province
DZ-26|Médéa Province
DZ-27|Mostaganem Province
DZ-28|M'Sila Province
DZ-29|Mascara Province
DZ-30|Ouargla Province
DZ-31|Oran Province
DZ-32|El Bayadh Province
DZ-33|Illizi Province
DZ-34|Bordj Bou Arréridj Province
DZ-35|Boumerdès Province
DZ-36|El Tarf Province
DZ-37|Tindouf Province
DZ-38|Tissemsilt Province
DZ-39|El Oued Province
DZ-40|Khenchela Province
DZ-41|Souk Ahras Province
DZ-42|Tipaza Province
DZ-43|Mila Province
DZ-44|Aïn Defla Province
DZ-45|Naama Province
DZ-46|Aïn Témouchent Province
DZ-47|Ghardaïa Province
DZ-48|Relizane Province
DZ-U-A|
EC-A|Azuay
EC-B|Bolivar
EC-C|Carchi
EC-D|Orellana
EC-E|Esmeraldas
EC-F|Canar
EC-G|Guayas
EC-H|Chimborazo
EC-I|Imbabura
EC-L|Loja
EC-M|Manabi
EC-N|Napo
EC-O|El Oro
EC-P|Pichincha
EC-R|Los Rios
EC-S|Morona-Santiago
EC-T|Tungurahua
EC-U|Sucumbios
EC-U-A|
EC-W|Galapagos
EC-X|Cotopaxi
EC-Y|Pastaza
EC-Z|Zamora-Chinchipe
EE-37|Harju County
EE-39|Hiiu County
EE-44|Ida-Viru County
EE-49|Jõgeva County
EE-51|Järva County
EE-57|Lääne County
EE-59|Lääne-Viru County
EE-65|Põlva County
EE-67|Pärnu County
EE-70|Rapla County
EE-74|Saare County
EE-7B|Tartu County
EE-82|Valga County
EE-84|Viljandi County
EE-86|Võru County
EE-U-A|
EG-ALX|Alexandria Governorate
EG-ASN|Aswan Governorate
EG-AST|Asyut Governorate
EG-BA|Red Sea Governorate
EG-BH|Beheira Governorate
EG-BNS|Beni Suef Governorate
EG-C|Cairo Governorate
EG-DK|Dakahlia Governorate
EG-DT|Damietta Governorate
EG-FYM|Faiyum Governorate
EG-GH|Gharbia Governorate
EG-GZ|Giza Governorate
EG-IS|Ismailia Governorate
EG-JS|South Sinai Governorate
EG-KB|Qalyubia Governorate
EG-KFS|Kafr el-Sheikh Governorate
EG-KN|Qena Governorate
EG-MN|Minya Governorate
EG-MNF|Monufia Governorate
EG-MT|Matruh Governorate
EG-PTS|Port Said Governorate
EG-SHG|Sohag Governorate
EG-SHR|Sharqia Governorate
EG-SIN|North Sinai Governorate
EG-SUZ|Suez Governorate
EG-U-A|
EG-WAD|New Valley Governorate
EH-U-A|
ER-AN|Anseba
ER-DK|Debubawi Keyih Bahri
ER-DU|Debub
ER-GB|Gash-Barka
ER-MA|Maakel
ER-SK|Semenawi Keyih Bahri
ER-U-A|
ES-A|Alicante
ES-AB|Albacete
ES-AL|Almería
ES-AN|Andalucía
ES-AR|Aragón
ES-AV|Ávila
ES-B|Barcelona
ES-BA|Badajoz
ES-BI|Vizcaya
ES-BU|Burgos
ES-C|La Coruña
ES-CA|Cádiz
ES-CC|Cáceres
ES-CE|Ceuta
ES-CL|Castilla y León
ES-CM|Castilla-La Mancha
ES-CN|Canary Islands
ES-CR|Ciudad Real
ES-CS|Castellón
ES-CT|Catalonia
ES-CU|Cuenca
ES-EX|Extremadura
ES-GA|Galicia
ES-GC|Las Palmas
ES-GE|Girona
ES-GR|Granada
ES-GU|Guadalajara
ES-H|Huelva
ES-HU|Huesca
ES-IB|Baleares
ES-J|Jaén
ES-L|Lleida
ES-LE|León
ES-LO|La Rioja
ES-LU|Lugo
ES-M|Madrid
ES-MA|Málaga
ES-ML|Melilla
ES-MU|Murcia
ES-NA|Navarra
ES-O|Asturias
ES-OR|Ourense
ES-P|Palencia
ES-PM|Baleares
ES-PO|Pontevedra
ES-PV|Basque Country
ES-S|Cantabria
ES-SA|Salamanca
ES-SE|Sevilla
ES-SG|Segovia
ES-SO|Soria
ES-SS|Guipúzcoa
ES-T|Tarragona
ES-TE|Teruel
ES-TF|Santa Cruz de Tenerife
ES-U-A|
ES-V|Valencia
ES-VA|Valladolid
ES-VI|Álava
ES-Z|Zaragoza
ES-ZA|Zamora
ET-AA|Addis Ababa
ET-AF|Afar
ET-AM|Amara
ET-BE|Benshangul-Gumaz
ET-DD|Dire Dawa
ET-GA|Gambela Peoples
ET-HA|Harari People
ET-OR|Oromia
ET-SN|Nationalities and Peoples Southern Nations
ET-SO|Somali
ET-TI|Tigrai
ET-U-A|
FI-AL|Åland Islands
FI-ES|Southern Finland
FI-IS|Eastern Finland
FI-LL|Lapland
FI-LS|Western Finland
FI-OL|Oulu
FI-U-A|
FJ-C|Central
FJ-E|Eastern
FJ-N|Northern
FJ-R|Rotuma
FJ-U-A|
FJ-W|Western
FK-U-A|
FM-KSA|Kosrae
FM-PNI|Pohnpei
FM-TRK|Chuuk
FM-U-A|
FM-YAP|Yap
FO-U-A|
FR-A|Alsace
FR-B|Aquitaine
FR-C|Auvergne
FR-D|Burgundy
FR-E|Brittany
FR-F|Centre
FR-G|Champagne-Ardenne
FR-H|Corsica
FR-I|Franche-Comté
FR-J|Île-de-France
FR-K|Languedoc-Roussillon
FR-L|Limousin
FR-M|Lorraine
FR-N|Midi-Pyrénées
FR-O|Nord-Pas-de-Calais
FR-P|Lower Normandy
FR-Q|Upper Normandy
FR-R|Pays-de-la-Loire
FR-S|Picardie
FR-T|Poitou-Charentes
FR-U|Provence-Alpes-Côte-d'Azur
FR-U-A|
FR-V|Rhône Alpes
GA-1|Estuaire Province
GA-2|Haut-Ogooué Province
GA-3|Moyen-Ogooué Province
GA-4|Ngounié Province
GA-5|Nyanga Province
GA-6|Ogooué-Ivindo Province
GA-7|Ogooué-Lolo Province
GA-8|Ogooué-Maritime Province
GA-9|Woleu-Ntem Province
GA-U-A|
GB-ENG|England
GB-NIR|Northern Ireland
GB-SCT|Scotland
GB-U-A|
GB-WLS|Wales
GD-AN|Saint Andrew
GD-DA|Saint David
GD-GE|Saint George
GD-JO|Saint John
GD-MA|Saint Mark
GD-PA|Saint Patrick
GD-U-A|
GE-AB|Abkhazia
GE-AJ|Adjara
GE-GU|Guria
GE-IM|Imereti
GE-KA|Kakheti
GE-KK|Kvemo Kartli
GE-MM|Mtskheta-Mtianeti
GE-RL|Racha-Lechkhumi and Kvemo Svaneti
GE-SJ|Samtskhe-Javakheti
GE-SK|Shida Kartli
GE-SZ|Samegrelo-Zemo Svaneti
GE-TB|Tbilisi
GE-U-A|
GF-CY|Cayenne
GF-SL|Saint-Laurent-du-Maroni
GF-U-A|
GG-U-A|
GH-AA|Greater Accra Region
GH-AH|Ashanti Region
GH-BA|Brong-Ahafo Region
GH-CP|Central Region
GH-EP|Eastern Region
GH-NP|Northern Region
GH-TV|Volta Region
GH-U-A|
GH-UE|Upper East Region
GH-UW|Upper West Region
GH-WP|Western Region
GI-U-A|
GL-U-A|
GM-B|Banjul
GM-C|Central River
GM-L|Lower River
GM-M|MacCarthy Island
GM-N|North Bank
GM-U|Upper River
GM-U-A|
GM-W|Western
GN-BE|Beyla
GN-BF|Boffa
GN-BK|Boke
GN-C|Conakry
GN-CO|Coyah
GN-DB|Dabola
GN-DI|Dinguiraye
GN-DL|Dalaba
GN-DU|Dubreka
GN-FA|Faranah
GN-FO|Forecariah
GN-FR|Fria
GN-GA|Gaoual
GN-GU|Guekedou
GN-KA|Kankan
GN-KB|Koubia
GN-KD|Kindia
GN-KE|Kerouane
GN-KN|Koundara
GN-KO|Kouroussa
GN-KS|Kissidougou
GN-LA|Labe
GN-LE|Lelouma
GN-LO|Lola
GN-MC|Macenta
GN-MD|Mandiana
GN-ML|Mali
GN-MM|Mamou
GN-NZ|Nzerekore
GN-PI|Pita
GN-SI|Siguiri
GN-TE|Telimele
GN-TO|Tougue
GN-U-A|
GN-YO|Yomou
GP-U-A|
GQ-AN|Annobon
GQ-BN|Bioko Norte
GQ-BS|Bioko Sur
GQ-C|Region Continental
GQ-CS|Centro Sur
GQ-I|Region Insular
GQ-KN|Kie-Ntem
GQ-LI|Litoral
GQ-U-A|
GQ-WN|Wele-Nzas
GR-01|Aetolia-Acarnania
GR-03|Boeotia
GR-04|Euboea
GR-05|Evrytania
GR-06|Phthiotis
GR-07|Phocis
GR-11|Argolis
GR-12|Arcadia
GR-13|Achaea
GR-14|Ilia
GR-15|Corinthia
GR-16|Laconia
GR-17|Messinia
GR-21|Zakynthos
GR-22|Corfu
GR-23|Kefallinia
GR-24|Lefkada
GR-31|Arta
GR-32|Thesprotia
GR-33|Ioannina
GR-34|Preveza
GR-41|Karditsa
GR-42|Larissa
GR-43|Magnesia
GR-44|Trikala
GR-51|Grevena
GR-52|Drama
GR-53|Imathia
GR-54|Thessaloniki
GR-55|Kavala
GR-56|Kastoria
GR-57|Kilkis
GR-58|Kozani
GR-59|Pella
GR-62|Serres
GR-63|Florina
GR-64|Chalcidice
GR-69|Mount Athos
GR-71|Evros
GR-72|Xanthi
GR-73|Rhodope
GR-81|Dodecanese
GR-82|Cyclades
GR-83|Lesbos
GR-84|Samos
GR-85|Chios
GR-91|Irakleion
GR-92|Lasithion
GR-93|Rethymnon
GR-94|Chania
GR-A1|Attica
GR-U-A|
GS-U-A|
GT-AV|Alta Verapez
GT-BV|Baja Verapez
GT-CM|Chimaltenango
GT-CQ|Chiquimula
GT-ES|Escuintla
GT-GU|Guatemala
GT-HU|Huehuetenango
GT-IZ|Izabal
GT-JA|Jalapa
GT-JU|Jutiapa
GT-PE|Peten
GT-PR|El Progreso
GT-QC|Quiche
GT-QZ|Quetzaltenango
GT-RE|Reta.thuleu
GT-SA|Sacatepequez
GT-SM|San Marcos
GT-SO|Solol6
GT-SR|Santa Rosa
GT-SU|Suchitepequez
GT-TO|Totonicapan
GT-U-A|
GT-ZA|Zacapa
GU-U-A|
GW-BA|Bafatá
GW-BL|Bolama
GW-BM|Biombo
GW-BS|Bissau
GW-CA|Cacheu
GW-GA|Gabu
GW-OI|Oio
GW-QU|Quloara
GW-TO|Tombali
GW-U-A|
GY-BA|Barima-Waini
GY-CU|Cuyuni-Mazaruni
GY-DE|Demerara-Mahaica
GY-EB|East Berbice-Corentyne
GY-ES|Essequibo Islands-West Demerara
GY-MA|Mahaica-Berbice
GY-PM|Pomeroon-Supenaam
GY-PT|Potaro-Siparuni
GY-U-A|
GY-UD|Upper Demerara-Berbice
GY-UT|Upper Takutu-Upper Essequibo
HK-U-A|
HN-AT|Atlantida
HN-CH|Choluteca
HN-CL|Colon
HN-CM|Comayagua
HN-CP|Copan
HN-CR|Cortes
HN-EP|El Paraiso
HN-FM|Francisco Morazan
HN-GD|Gracias a Dios
HN-IB|Islas de la Bahia
HN-IN|Intibuca
HN-LE|Lempira
HN-LP|La Paz
HN-OC|Ocotepeque
HN-OL|Olancho
HN-SB|Santa Barbara
HN-U-A|
HN-VA|Valle
HN-YO|Yoro
HR-01|Zagreb
HR-02|Krapina-Zagorje
HR-03|Sisak-Moslavina
HR-04|Karlovac
HR-05|Varaždin
HR-06|Koprivnica-Križevci
HR-07|Bjelovar-Bilogora
HR-08|Primorje-Gorski Kotar
HR-09|Lika-Senj
HR-10|Virovitica-Podravina
HR-11|Požega-Slavonia
HR-12|Brod-Posavina
HR-13|Zadar
HR-14|Osijek-Baranja
HR-15|Šibenik-Knin
HR-16|Vukovar-Srijem
HR-17|Split-Dalmatia
HR-18|Istria
HR-19|Dubrovnik-Neretva
HR-20|Me?imurje
HR-21|Zagreb (city)
HR-U-A|
HT-AR|Artibonite Department
HT-CE|Centre Department
HT-GA|Grande'Anse Department
HT-ND|Nord Department
HT-NE|Nord-Est Department
HT-NI|Nippes
HT-NO|Nord-Ouest Department
HT-OU|Ouest Department
HT-SD|Sud Department
HT-SE|Sud-Est Department
HT-U-A|
HU-BA|Baranya
HU-BC|Békéscsaba
HU-BE|Békés
HU-BK|Bács-Kiskun
HU-BU|Budapest
HU-BZ|Borsod-Abaúj-Zemplén
HU-CS|Csongrád
HU-DE|Debrecen
HU-DU|Dunaújváros
HU-EG|Eger
HU-FE|Fejér
HU-GS|Gy?r-Moson-Sopron
HU-GY|Gy?r
HU-HB|Hajdu-Bihar
HU-HE|Heves
HU-HV|Hódmez?vásárhely
HU-JN|Jász-Nagykun-Szolnok
HU-KE|Komárom-Esztergom
HU-KM|Kecskemét
HU-KV|Kaposvár
HU-MI|Miskolc
HU-NK|Nagykanizsa
HU-NO|Nográd
HU-NY|Nyiregyháza
HU-PE|Pest
HU-PS|Pécs
HU-SD|Szeged
HU-SF|Székesfehérvár
HU-SH|Szombathely
HU-SK|Szolnok
HU-SN|Sopron
HU-SO|Somogy
HU-SS|Szekszárd
HU-ST|Salgótarján
HU-SZ|Szabolcs-Szatmár-Bereg
HU-TB|Tatabánya
HU-TO|Tolna
HU-U-A|
HU-VA|Vas
HU-VE|Veszprém
HU-ZA|Zala
HU-ZE|Zalaegerszeg
ID-AC|Aceh
ID-BA|Bali
ID-BB|Bangka Belitung
ID-BE|Bengkulu
ID-BT|Banten
ID-GO|Gorontalo
ID-IJ|Irian Jaya
ID-JA|Jambi
ID-JB|Jawa Barat
ID-JI|Jawa Timur
ID-JK|Jakarta Raya
ID-JT|Jawa Tengah
ID-KB|Kalimantan Barat
ID-KI|East Kalimantan
ID-KR|Kepulauan Riau
ID-KS|Kalimantan Selatan
ID-KT|Kalimantan Timur
ID-LA|Lampung
ID-MA|Maluku
ID-MU|Maluku Utara
ID-NB|Nusa Tenggara Barat
ID-NT|Nusa Tenggara Timur
ID-PA|Papua
ID-RI|Riau
ID-SA|Sulawesi Utara
ID-SB|Sumatra Barat
ID-SG|Sulawesi Tenggara
ID-SN|Sulawesi Selatan
ID-SS|Sumatra Selatan
ID-ST|Sulawesi Tengah
ID-SU|Sumatera Utara
ID-U-A|
ID-YO|Yogyakarta
IE-C|County Cork
IE-CE|County Clare
IE-CN|County Cavan
IE-CW|County Carlow
IE-D|County Dublin
IE-DL|County Donegal
IE-G|County Galway
IE-KE|County Kildare
IE-KK|County Kilkenny
IE-KY|County Kerry
IE-LD|County Longford
IE-LH|County Louth
IE-LK|County Limerick
IE-LM|County Leitrim
IE-LS|County Laois
IE-MH|County Meath
IE-MN|County Monaghan
IE-MO|County Mayo
IE-OY|County Offaly
IE-RN|County Roscommon
IE-SO|County Sligo
IE-TA|County Tipperary
IE-U-A|
IE-WD|County Waterford
IE-WH|County Westmeath
IE-WW|County Wicklow
IE-WX|County Wexford
IL-D|South District
IL-HA|Haifa District
IL-JM|Jerusalem District
IL-M|Center District
IL-TA|Tel Aviv District
IL-U-A|
IL-Z|North District
IM-U-A|
IN-DL|Delhi
IN-DN|Dadra and Nagar Haveli
IN-GA|Goa
IN-GJ|Gujarat
IN-HP|Himachal Pradesh
IN-HR|Haryana
IN-JH|Jharkhand
IN-JK|Jammu and Kashmir
IN-KA|Karnataka
IN-KL|Kerala
IN-LD|Lakshadweep
IN-ML|Meghalaya
IN-MM|Maharashtra
IN-MN|Manipur
IN-MP|Madhya Pradesh
IN-MZ|Mizoram
IN-NL|Nagaland
IN-OR|Orissa
IN-PB|Punjab
IN-PY|Pondicherry
IN-RJ|Rajasthan
IN-SK|Sikkim
IN-TN|Tamil Nadu
IN-TR|Tripura
IN-U-A|
IN-UL|Uttaranchal
IN-UP|Uttar Pradesh
IN-WB|West Bengal
IN-AN|Andaman and Nicobar Islands
IN-AP|Andhra Pradesh
IN-AR|Arunachal Pradesh
IN-AS|Assam
IN-BR|Bihar
IN-CH|Chandigarh
IN-CT|Chhattisgarh
IN-DD|Daman and Diu
IN-DL|Delhi
IN-DN|Dadra and Nagar Haveli
IN-GA|Goa
IN-GJ|Gujarat
IN-HP|Himachal Pradesh
IN-HR|Haryana
IN-JH|Jharkhand
IN-JK|Jammu and Kashmir
IN-KA|Karnataka
IN-KL|Kerala
IN-LD|Lakshadweep
IN-ML|Meghalaya
IN-MM|Maharashtra
IN-MN|Manipur
IN-MP|Madhya Pradesh
IN-MZ|Mizoram
IN-NL|Nagaland
IN-OR|Orissa
IN-PB|Punjab
IN-PY|Pondicherry
IN-RJ|Rajasthan
IN-SK|Sikkim
IN-TN|Tamil Nadu
IN-TR|Tripura
IN-U-A|
IN-UL|Uttaranchal
IN-UP|Uttar Pradesh
IN-WB|West Bengal
IO-U-A|
IO-U-A|
IQ-AN|Al-Anbar Governorate
IQ-AR|Arbil Governorate
IQ-BA|Basra Governorate
IQ-BB|Babil Governorate
IQ-BG|Baghdad Governorate
IQ-DA|Duhok Governorate
IQ-DI|Diyala Governorate
IQ-DQ|Dhi Qar Governorate
IQ-KA|Karbala Governorate
IQ-MA|Maysan Governorate
IQ-MU|Al-Muthanna Governorate
IQ-NA|Najaf Governorate
IQ-NI|Ninawa Governorate
IQ-QA|Al-Qadisiyyah Governorate
IQ-SD|Salah ad Din Governorate
IQ-SW|As-Sulaymaniyyah Governorate
IQ-TS|Kirkuk Governorate
IQ-U-A|
IQ-WA|Wasit Governorate
IQ-AN|Al-Anbar Governorate
IQ-AR|Arbil Governorate
IQ-BA|Basra Governorate
IQ-BB|Babil Governorate
IQ-BG|Baghdad Governorate
IQ-DA|Duhok Governorate
IQ-DI|Diyala Governorate
IQ-DQ|Dhi Qar Governorate
IQ-KA|Karbala Governorate
IQ-MA|Maysan Governorate
IQ-MU|Al-Muthanna Governorate
IQ-NA|Najaf Governorate
IQ-NI|Ninawa Governorate
IQ-QA|Al-Qadisiyyah Governorate
IQ-SD|Salah ad Din Governorate
IQ-SW|As-Sulaymaniyyah Governorate
IQ-TS|Kirkuk Governorate
IQ-U-A|
IQ-WA|Wasit Governorate
IR-01|East Azarbaijan Province
IR-02|West Azarbaijan Province
IR-03|Ardabil Province
IR-04|Esfahan Province
IR-05|Iiam Province
IR-06|Bushehr Province
IR-07|Tehran Province
IR-08|Chaharmahal and Bakhtiari Province
IR-10|Khuzestan Province
IR-11|Zanjan Province
IR-12|Semnan Province
IR-13|Sistan and Baluchestan Province
IR-14|Fars Province
IR-15|Kerman Province
IR-16|Kordestan Province
IR-17|Kermanshah Province
IR-18|Kohgiluyeh and Boyer-Ahmad Province
IR-19|Gilan Province
IR-20|Lorestan Province
IR-21|Mazandaran Province
IR-22|Markazi Province
IR-23|Hormozgan Province
IR-24|Hamadan Province
IR-25|Yazd Province
IR-26|Qom Province
IR-27|Golestan Province
IR-28|Qazvin Province
IR-29|South Khorasan Province
IR-30|Razavi Khorasan Province
IR-31|North Khorasan Province
IR-U-A|
IR-01|East Azarbaijan Province
IR-02|West Azarbaijan Province
IR-03|Ardabil Province
IR-04|Esfahan Province
IR-05|Iiam Province
IR-06|Bushehr Province
IR-07|Tehran Province
IR-08|Chaharmahal and Bakhtiari Province
IR-10|Khuzestan Province
IR-11|Zanjan Province
IR-12|Semnan Province
IR-13|Sistan and Baluchestan Province
IR-14|Fars Province
IR-15|Kerman Province
IR-16|Kordestan Province
IR-17|Kermanshah Province
IR-18|Kohgiluyeh and Boyer-Ahmad Province
IR-19|Gilan Province
IR-20|Lorestan Province
IR-21|Mazandaran Province
IR-22|Markazi Province
IR-23|Hormozgan Province
IR-24|Hamadan Province
IR-25|Yazd Province
IR-26|Qom Province
IR-27|Golestan Province
IR-28|Qazvin Province
IR-29|South Khorasan Province
IR-30|Razavi Khorasan Province
IR-31|North Khorasan Province
IR-U-A|
IS-1|Capital Region
IS-2|Southern Peninsula
IS-3|West
IS-4|Westfjords
IS-5|Northwest
IS-6|Northeast
IS-7|East
IS-8|South
IS-U-A|
IS-1|Capital Region
IS-2|Southern Peninsula
IS-3|West
IS-4|Westfjords
IS-5|Northwest
IS-6|Northeast
IS-7|East
IS-8|South
IS-U-A|
IT-21|Piedmont
IT-23|Valle d'Aosta
IT-25|Lombardy
IT-32|Trentino-Alto Adige
IT-34|Veneto
IT-36|Friuli-Venezia Giulia
IT-42|Liguria
IT-45|Emilia-Romagna
IT-52|Tuscany
IT-55|Umbria
IT-57|Marche
IT-62|Lazio
IT-65|Abruzzi
IT-67|Molise
IT-72|Campania
IT-75|Apulia
IT-77|Basilicata
IT-78|Calabria
IT-82|Sicily
IT-88|Sardinia
IT-U-A|
IT-21|Piedmont
IT-23|Valle d'Aosta
IT-25|Lombardy
IT-32|Trentino-Alto Adige
IT-34|Veneto
IT-36|Friuli-Venezia Giulia
IT-42|Liguria
IT-45|Emilia-Romagna
IT-52|Tuscany
IT-55|Umbria
IT-57|Marche
IT-62|Lazio
IT-65|Abruzzi
IT-67|Molise
IT-72|Campania
IT-75|Apulia
IT-77|Basilicata
IT-78|Calabria
IT-82|Sicily
IT-88|Sardinia
IT-U-A|
JE-U-A|
JE-U-A|
JM-01|Kingston
JM-02|Saint Andrew
JM-03|Saint Thomea
JM-04|Portland
JM-05|Saint Mary
JM-06|Saint Ann
JM-07|Trelawny
JM-08|Saint James
JM-09|Hanover
JM-10|Westmoreland
JM-11|Saint Elizabeth
JM-12|Manchester
JM-13|Clarendon
JM-14|Saint Catherine
JM-U-A|
JM-01|Kingston
JM-02|Saint Andrew
JM-03|Saint Thomea
JM-04|Portland
JM-05|Saint Mary
JM-06|Saint Ann
JM-07|Trelawny
JM-08|Saint James
JM-09|Hanover
JM-10|Westmoreland
JM-11|Saint Elizabeth
JM-12|Manchester
JM-13|Clarendon
JM-14|Saint Catherine
JM-U-A|
JO-AJ|Ajln
JO-AM|Amman
JO-AQ|Al 'Aqaba
JO-AT|At Tafilah
JO-AZ|Az Zarga
JO-BA|Al Balqa'
JO-JA|Jarash
JO-JR|Irbid
JO-KA|Al Karak
JO-MA|Al Mafraq
JO-MD|Madaba
JO-MN|Ma'an
JO-U-A|
JO-AJ|Ajln
JO-AM|Amman
JO-AQ|Al 'Aqaba
JO-AT|At Tafilah
JO-AZ|Az Zarga
JO-BA|Al Balqa'
JO-JA|Jarash
JO-JR|Irbid
JO-KA|Al Karak
JO-MA|Al Mafraq
JO-MD|Madaba
JO-MN|Ma'an
JO-U-A|
JP-01|Hokkaid? Prefecture
JP-02|Aomori Prefecture
JP-03|Iwate Prefecture
JP-04|Miyagi Prefecture
JP-05|Akita Prefecture
JP-06|Yamagata Prefecture
JP-07|Fukusima Prefecture
JP-08|Ibaraki Prefecture
JP-09|Tochigi Prefecture
JP-10|Gunma Prefecture
JP-11|Saitama Prefecture
JP-12|Chiba Prefecture
JP-13|T?ky? Prefecture
JP-14|Kanagawa Prefecture
JP-15|Niigata Prefecture
JP-16|Toyama Prefecture
JP-17|Ishikawa Prefecture
JP-18|Fukui Prefecture
JP-19|Yamanashi Prefecture
JP-20|Nagano Prefecture
JP-21|Gifu Prefecture
JP-22|Shizuoka Prefecture
JP-23|Aichi Prefecture
JP-24|Mie Prefecture
JP-25|Shiga Prefecture
JP-26|Ky?to Prefecture
JP-27|?saka Prefecture
JP-28|Hy?go Prefecture
JP-29|Nara Prefecture
JP-30|Wakayama Prefecture
JP-31|Tottori Prefecture
JP-32|Shimane Prefecture
JP-33|Okayama Prefecture
JP-34|Hiroshima Prefecture
JP-35|Yamaguchi Prefecture
JP-36|Tokushima Prefecture
JP-37|Kagawa Prefecture
JP-38|Ehime Prefecture
JP-39|K?chi Prefecture
JP-40|Fukuoka Prefecture
JP-41|Saga Prefecture
JP-42|Nagasaki Prefecture
JP-43|Kumamoto Prefecture
JP-44|?ita Prefecture
JP-45|Miyazaki Prefecture
JP-46|Kagoshima Prefecture
JP-47|Okinawa Prefecture
JP-U-A|
JP-01|Hokkaid? Prefecture
JP-02|Aomori Prefecture
JP-03|Iwate Prefecture
JP-04|Miyagi Prefecture
JP-05|Akita Prefecture
JP-06|Yamagata Prefecture
JP-07|Fukusima Prefecture
JP-08|Ibaraki Prefecture
JP-09|Tochigi Prefecture
JP-10|Gunma Prefecture
JP-11|Saitama Prefecture
JP-12|Chiba Prefecture
JP-13|T?ky? Prefecture
JP-14|Kanagawa Prefecture
JP-15|Niigata Prefecture
JP-16|Toyama Prefecture
JP-17|Ishikawa Prefecture
JP-18|Fukui Prefecture
JP-19|Yamanashi Prefecture
JP-20|Nagano Prefecture
JP-21|Gifu Prefecture
JP-22|Shizuoka Prefecture
JP-23|Aichi Prefecture
JP-24|Mie Prefecture
JP-25|Shiga Prefecture
JP-26|Ky?to Prefecture
JP-27|?saka Prefecture
JP-28|Hy?go Prefecture
JP-29|Nara Prefecture
JP-30|Wakayama Prefecture
JP-31|Tottori Prefecture
JP-32|Shimane Prefecture
JP-33|Okayama Prefecture
JP-34|Hiroshima Prefecture
JP-35|Yamaguchi Prefecture
JP-36|Tokushima Prefecture
JP-37|Kagawa Prefecture
JP-38|Ehime Prefecture
JP-39|K?chi Prefecture
JP-40|Fukuoka Prefecture
JP-41|Saga Prefecture
JP-42|Nagasaki Prefecture
JP-43|Kumamoto Prefecture
JP-44|?ita Prefecture
JP-45|Miyazaki Prefecture
JP-46|Kagoshima Prefecture
JP-47|Okinawa Prefecture
JP-U-A|
KE-110|Nairobi Province
KE-200|Central Province
KE-300|Coast Province
KE-400|Eastern Province
KE-500|North-Eastern Province
KE-600|Nyanza Province
KE-700|Rift Valley Province
KE-900|Western Province
KE-U-A|
KE-110|Nairobi Province
KE-200|Central Province
KE-300|Coast Province
KE-400|Eastern Province
KE-500|North-Eastern Province
KE-600|Nyanza Province
KE-700|Rift Valley Province
KE-900|Western Province
KE-U-A|
KG-B|Batken
KG-C|Chuy
KG-GB|Bishkek
KG-J|Jalal-Abad
KG-N|Naryn
KG-O|Osh
KG-T|Talas
KG-U-A|
KG-Y|Issyk-Kul
KG-B|Batken
KG-C|Chuy
KG-GB|Bishkek
KG-J|Jalal-Abad
KG-N|Naryn
KG-O|Osh
KG-T|Talas
KG-U-A|
KG-Y|Issyk-Kul
KH-1|Banteay Mean Chey
KH-10|Krachoh
KH-11|Mondol Kiri
KH-12|Phnom Penh
KH-13|Preah Vihear
KH-14|Prey Veaeng
KH-15|Pousaat
KH-16|Rotanak Kiri
KH-17|Siem Reab
KH-18|Xrong Preah Sihanouk
KH-19|Stueng Traeng
KH-2|Baat Dambang
KH-20|Svaay Rieng
KH-21|Taakaev
KH-22|Otdar Mean Chey
KH-23|Krong Kaeb
KH-24|Krong Pailin
KH-3|Kampong Chaam
KH-4|Kampong Chhnang
KH-5|Kampong Spueu
KH-6|Kampong Thum
KH-7|Kampot
KH-8|Kandaal
KH-9|Kach Kong
KH-U-A|
KH-1|Banteay Mean Chey
KH-10|Krachoh
KH-11|Mondol Kiri
KH-12|Phnom Penh
KH-13|Preah Vihear
KH-14|Prey Veaeng
KH-15|Pousaat
KH-16|Rotanak Kiri
KH-17|Siem Reab
KH-18|Xrong Preah Sihanouk
KH-19|Stueng Traeng
KH-2|Baat Dambang
KH-20|Svaay Rieng
KH-21|Taakaev
KH-22|Otdar Mean Chey
KH-23|Krong Kaeb
KH-24|Krong Pailin
KH-3|Kampong Chaam
KH-4|Kampong Chhnang
KH-5|Kampong Spueu
KH-6|Kampong Thum
KH-7|Kampot
KH-8|Kandaal
KH-9|Kach Kong
KH-U-A|
KI-G|Gilbert Islands
KI-L|Line Islands
KI-P|Phoenix Islands
KI-U-A|
KI-G|Gilbert Islands
KI-L|Line Islands
KI-P|Phoenix Islands
KI-U-A|
KM-A|Anjouan Ndzouani
KM-G|Grande Comore Ngazidja
KM-M|Moheli Moili
KM-U-A|
KM-A|Anjouan Ndzouani
KM-G|Grande Comore Ngazidja
KM-M|Moheli Moili
KM-U-A|
KN-U-A|
KN-U-A|
KP-CHA|Chagang-do
KP-HAB|Hamgyongbuk-do
KP-HAN|Hamgyongnam-do
KP-HWB|Hwanghaebuk-do
KP-HWN|Hwanghaenam-do
KP-KAE|Kaesong-si
KP-KAN|Kangwon-do
KP-NAJ|Najin Sonbong-si
KP-NAM|Nampo-si
KP-PYB|Pyonganbuk-do
KP-PYN|Pyongannam-do
KP-PYO|Pyongyang-ai
KP-U-A|
KP-YAN|Yanggang-do
KP-CHA|Chagang-do
KP-HAB|Hamgyongbuk-do
KP-HAN|Hamgyongnam-do
KP-HWB|Hwanghaebuk-do
KP-HWN|Hwanghaenam-do
KP-KAE|Kaesong-si
KP-KAN|Kangwon-do
KP-NAJ|Najin Sonbong-si
KP-NAM|Nampo-si
KP-PYB|Pyonganbuk-do
KP-PYN|Pyongannam-do
KP-PYO|Pyongyang-ai
KP-U-A|
KP-YAN|Yanggang-do
KR-11|Seoul Teugbyeolsi
KR-26|Busan Gwang'yeogsi
KR-27|Daegu Gwang'yeogsi
KR-28|Incheon Gwang'yeogsi
KR-29|Gwangju Gwang'yeogsi
KR-30|Daejeon Gwang'yeogsi
KR-31|Ulsan Gwang'yeogsi
KR-41|Gyeonggido
KR-42|Gang'weondo
KR-43|Chungcheongbugdo
KR-44|Chungcheongnamdo
KR-45|Jeonrabugdo
KR-46|Jeonranamdo
KR-47|Gyeongsangbugdo
KR-48|Gyeongsangnamdo
KR-49|Jejudo
KR-U-A|
KR-11|Seoul Teugbyeolsi
KR-26|Busan Gwang'yeogsi
KR-27|Daegu Gwang'yeogsi
KR-28|Incheon Gwang'yeogsi
KR-29|Gwangju Gwang'yeogsi
KR-30|Daejeon Gwang'yeogsi
KR-31|Ulsan Gwang'yeogsi
KR-41|Gyeonggido
KR-42|Gang'weondo
KR-43|Chungcheongbugdo
KR-44|Chungcheongnamdo
KR-45|Jeonrabugdo
KR-46|Jeonranamdo
KR-47|Gyeongsangbugdo
KR-48|Gyeongsangnamdo
KR-49|Jejudo
KR-U-A|
KS-U-A|
KS-U-A|
KW-AH|Al Ahmadi Governorate
KW-FA|Al Farwaniyah Governorate
KW-HA|Hawalli Governorate
KW-JA|Al Jahra Governorate
KW-KU|Al Asimah Governorate
KW-MU|Mubarak Al-Kabeer Governorate
KW-U-A|
KW-AH|Al Ahmadi Governorate
KW-FA|Al Farwaniyah Governorate
KW-HA|Hawalli Governorate
KW-JA|Al Jahra Governorate
KW-KU|Al Asimah Governorate
KW-MU|Mubarak Al-Kabeer Governorate
KW-U-A|
KY-U-A|
KY-U-A|
KZ-AKM|Akmola
KZ-AKT|Aktobe
KZ-ALA|Almaty (city)
KZ-ALM|Almaty
KZ-AST|Astana
KZ-ATY|Atyrau
KZ-BAY|Baikonur
KZ-KAR|Karagandy
KZ-KUS|Kostanay
KZ-KZY|Kyzylorda
KZ-MAN|Mangystau
KZ-PAV|Pavlodar
KZ-SEV|North Kazakhstan
KZ-U-A|
KZ-VOS|East Kazakhstan
KZ-YUZ|South Kazakhstan
KZ-ZAP|West Kazakhstan
KZ-ZHA|Zhambyl
KZ-AKM|Akmola
KZ-AKT|Aktobe
KZ-ALA|Almaty (city)
KZ-ALM|Almaty
KZ-AST|Astana
KZ-ATY|Atyrau
KZ-BAY|Baikonur
KZ-KAR|Karagandy
KZ-KUS|Kostanay
KZ-KZY|Kyzylorda
KZ-MAN|Mangystau
KZ-PAV|Pavlodar
KZ-SEV|North Kazakhstan
KZ-U-A|
KZ-VOS|East Kazakhstan
KZ-YUZ|South Kazakhstan
KZ-ZAP|West Kazakhstan
KZ-ZHA|Zhambyl
LA-AT|Attapu
LA-BK|Bokeo
LA-BL|Bolikhamxai
LA-CH|Champasak
LA-HO|Houaphan
LA-KH|Khammouan
LA-LM|Louang Namtha
LA-LP|Louangphabang
LA-OU|Oudomxai
LA-PH|Phongsali
LA-SL|Salavan
LA-SV|Savannakhet
LA-U-A|
LA-VT|Vientiane
LA-XA|Xaignabouli
LA-XE|Xekong
LA-XI|Xiangkhoang
LA-XN|Xiasomboun
LA-AT|Attapu
LA-BK|Bokeo
LA-BL|Bolikhamxai
LA-CH|Champasak
LA-HO|Houaphan
LA-KH|Khammouan
LA-LM|Louang Namtha
LA-LP|Louangphabang
LA-OU|Oudomxai
LA-PH|Phongsali
LA-SL|Salavan
LA-SV|Savannakhet
LA-U-A|
LA-VT|Vientiane
LA-XA|Xaignabouli
LA-XE|Xekong
LA-XI|Xiangkhoang
LA-XN|Xiasomboun
LB-AK|Aakkar Governorate
LB-AS|North Governorate
LB-BA|Beirut Governorate
LB-BH|Baalbek-Hermel Governorate
LB-BI|Beqaa Governorate
LB-JA|South Governorate
LB-JL|Mount Lebanon Governorate
LB-NA|Nabatieh Governorate
LB-U-A|
LB-AK|Aakkar Governorate
LB-AS|North Governorate
LB-BA|Beirut Governorate
LB-BH|Baalbek-Hermel Governorate
LB-BI|Beqaa Governorate
LB-JA|South Governorate
LB-JL|Mount Lebanon Governorate
LB-NA|Nabatieh Governorate
LB-U-A|
LC-01|Anse la Raye
LC-02|Castries
LC-03|Choiseul
LC-04|Dauphin
LC-05|Dennery
LC-06|Gros Islet
LC-07|Laborie
LC-08|Micoud
LC-09|Praslin
LC-10|Soufrière
LC-11|Vieux Fort
LC-U-A|
LC-01|Anse la Raye
LC-02|Castries
LC-03|Choiseul
LC-04|Dauphin
LC-05|Dennery
LC-06|Gros Islet
LC-07|Laborie
LC-08|Micoud
LC-09|Praslin
LC-10|Soufrière
LC-11|Vieux Fort
LC-U-A|
LI-01|Balzers
LI-02|Eschen
LI-03|Gamprin
LI-04|Mauren
LI-05|Planken
LI-06|Ruggell
LI-07|Schaan
LI-08|Schellenberg
LI-09|Triesen
LI-10|Triesenberg
LI-11|Vaduz
LI-U-A|
LI-01|Balzers
LI-02|Eschen
LI-03|Gamprin
LI-04|Mauren
LI-05|Planken
LI-06|Ruggell
LI-07|Schaan
LI-08|Schellenberg
LI-09|Triesen
LI-10|Triesenberg
LI-11|Vaduz
LI-U-A|
LK-1|Western Province
LK-2|Central Province
LK-3|Southern Province
LK-4|Northern Province
LK-5|Eastern Province
LK-6|North Western Province
LK-7|North Central Province
LK-8|Uva Province
LK-9|Sabaragamuwa Province
LK-U-A|
LK-1|Western Province
LK-2|Central Province
LK-3|Southern Province
LK-4|Northern Province
LK-5|Eastern Province
LK-6|North Western Province
LK-7|North Central Province
LK-8|Uva Province
LK-9|Sabaragamuwa Province
LK-U-A|
LR-BG|Bong
LR-BM|Bomi
LR-CM|Grand Cape Mount
LR-GB|Grand Basaa
LR-GG|Grand Gedeh
LR-GK|Grand Kru
LR-LO|Lofa
LR-MG|Margibi
LR-MO|Montserrado
LR-MY|Maryland
LR-NI|Nimba
LR-RI|Rivercess
LR-SI|Sinoe
LR-U-A|
LR-BG|Bong
LR-BM|Bomi
LR-CM|Grand Cape Mount
LR-GB|Grand Basaa
LR-GG|Grand Gedeh
LR-GK|Grand Kru
LR-LO|Lofa
LR-MG|Margibi
LR-MO|Montserrado
LR-MY|Maryland
LR-NI|Nimba
LR-RI|Rivercess
LR-SI|Sinoe
LR-U-A|
LS-A|Maseru
LS-B|Butha-Buthe
LS-C|Leribe
LS-D|Berea
LS-E|Mafeteng
LS-F|Mohale's Hoek
LS-G|Quthing
LS-H|Qacha's Nek
LS-J|Mokhotlong
LS-K|Thaba-Tseka
LS-U-A|
LS-A|Maseru
LS-B|Butha-Buthe
LS-C|Leribe
LS-D|Berea
LS-E|Mafeteng
LS-F|Mohale's Hoek
LS-G|Quthing
LS-H|Qacha's Nek
LS-J|Mokhotlong
LS-K|Thaba-Tseka
LS-U-A|
LT-AL|Alytus County
LT-KL|Klaip?da County
LT-KU|Kaunas County
LT-MR|Marijampol? County
LT-PN|Panev?žys County
LT-SA|Šiauliai County
LT-TA|Taurag? County
LT-TE|Telšiai County
LT-U-A|
LT-UT|Utena County
LT-VL|Vilnius County
LT-AL|Alytus County
LT-KL|Klaip?da County
LT-KU|Kaunas County
LT-MR|Marijampol? County
LT-PN|Panev?žys County
LT-SA|Šiauliai County
LT-TA|Taurag? County
LT-TE|Telšiai County
LT-U-A|
LT-UT|Utena County
LT-VL|Vilnius County
LU-D|Diekirch
LU-G|Grevenmacher
LU-L|Luxembourg
LU-U-A|
LU-D|Diekirch
LU-G|Grevenmacher
LU-L|Luxembourg
LU-U-A|
LV-AI|Aizkraukle District
LV-AL|Al?ksne District
LV-BL|Balvi District
LV-BU|Bauska District
LV-CE|C?sis District
LV-DA|Daugavpils District
LV-DGV|Daugavpils (city)
LV-DO|Dobele District
LV-GU|Gulbene District
LV-JEL|Jelgava (city)
LV-JK|J?kabpils District
LV-JL|Jelgava District
LV-JUR|J?rmala (city)
LV-KR|Kr?slava District
LV-KU|Kuld?ga District
LV-LE|Liep?ja District
LV-LM|Limbaži District
LV-LPX|Liep?ja (city)
LV-LU|Ludza District
LV-MA|Madona District
LV-OG|Ogre District
LV-PR|Prei?i District
LV-RE|R?zekne District
LV-REZ|R?zekne (city)
LV-RI|Riga District
LV-RIX|Riga (city)
LV-SA|Saldus District
LV-TA|Talsi District
LV-TU|Tukums District
LV-U-A|
LV-VE|Ventspils
LV-VEN|Ventspils (city)
LV-VK|Valka District
LV-VM|Valmiera District
LV-AI|Aizkraukle District
LV-AL|Al?ksne District
LV-BL|Balvi District
LV-BU|Bauska District
LV-CE|C?sis District
LV-DA|Daugavpils District
LV-DGV|Daugavpils (city)
LV-DO|Dobele District
LV-GU|Gulbene District
LV-JEL|Jelgava (city)
LV-JK|J?kabpils District
LV-JL|Jelgava District
LV-JUR|J?rmala (city)
LV-KR|Kr?slava District
LV-KU|Kuld?ga District
LV-LE|Liep?ja District
LV-LM|Limbaži District
LV-LPX|Liep?ja (city)
LV-LU|Ludza District
LV-MA|Madona District
LV-OG|Ogre District
LV-PR|Prei?i District
LV-RE|R?zekne District
LV-REZ|R?zekne (city)
LV-RI|Riga District
LV-RIX|Riga (city)
LV-SA|Saldus District
LV-TA|Talsi District
LV-TU|Tukums District
LV-U-A|
LV-VE|Ventspils
LV-VEN|Ventspils (city)
LV-VK|Valka District
LV-VM|Valmiera District
LY-BA|Benghazi District
LY-BU|Al Butnan District
LY-DR|Darnah District
LY-GT|Ghat District
LY-JA|Al Jabal al Akhdar District
LY-JG|Al Jabal al Gharbi District
LY-JI|Al Jfara District
LY-JU|Al Jufrah District
LY-KF|Al Kufrah District
LY-MB|Al Murgub District
LY-MI|Misurata District
LY-MJ|Al Marj District
LY-MQ|Murzuq District
LY-NL|Nalut District
LY-NQ|An Nuqat al Khams District
LY-SB|Sabha District
LY-SH|Wadi Al Shatii District
LY-SR|Surt District
LY-TB|Tripoli District
LY-U-A|
LY-WA|Al Wahat District
LY-WD|Wadi Al Hayaa District
LY-ZA|Az Zawiyah District
LY-BA|Benghazi District
LY-BU|Al Butnan District
LY-DR|Darnah District
LY-GT|Ghat District
LY-JA|Al Jabal al Akhdar District
LY-JG|Al Jabal al Gharbi District
LY-JI|Al Jfara District
LY-JU|Al Jufrah District
LY-KF|Al Kufrah District
LY-MB|Al Murgub District
LY-MI|Misurata District
LY-MJ|Al Marj District
LY-MQ|Murzuq District
LY-NL|Nalut District
LY-NQ|An Nuqat al Khams District
LY-SB|Sabha District
LY-SH|Wadi Al Shatii District
LY-SR|Surt District
LY-TB|Tripoli District
LY-U-A|
LY-WA|Al Wahat District
LY-WD|Wadi Al Hayaa District
LY-ZA|Az Zawiyah District
MA-AGD|Agadir
MA-ASZ|Assa-Zag
MA-AZI|Azilal
MA-BAH|Aït Baha
MA-BEM|Beni Mellal
MA-BER|Berkane
MA-BES|Ben Sllmane
MA-BOD|Boujdour
MA-BOM|Boulemane
MA-CAS|Casablanca
MA-CHE|Chefchaouene
MA-CHI|Chichaoua
MA-ERR|Errachidia
MA-ESI|Essaouira
MA-ESM|Es Smara
MA-FES|Fès
MA-FIG|Figuig
MA-GUE|Guelmim
MA-HAJ|El Hajeb
MA-HAO|Al Haouz
MA-HOC|Al Hoceïma
MA-IFR|Ifrane
MA-JDI|El Jadida
MA-JRA|Jerada
MA-KEN|Kénitra
MA-KES|Kelaat Sraghna
MA-KHE|Khemisaet
MA-KHN|Khenifra
MA-KHO|Khouribga
MA-LAA|Laâyoune (EH)
MA-LAP|Larache
MA-MAR|Marrakech
MA-MEK|Meknsès
MA-MEL|Aït Melloul
MA-NAD|Nador
MA-OUA|Ouarzazate
MA-OUD|Oued ed Dahab (EH)
MA-OUJ|Oujda
MA-RBA|Rabat-Salé
MA-SAF|Safi
MA-SEF|Sefrou
MA-SET|Settat
MA-SIK|Sidl Kacem
MA-TAO|Taounate
MA-TAR|Taroudannt
MA-TAT|Tata
MA-TAZ|Taza
MA-TET|Tétouan
MA-TIZ|Tiznit
MA-TNG|Tanger
MA-TNT|Tan-Tan
MA-U-A|
MA-AGD|Agadir
MA-ASZ|Assa-Zag
MA-AZI|Azilal
MA-BAH|Aït Baha
MA-BEM|Beni Mellal
MA-BER|Berkane
MA-BES|Ben Sllmane
MA-BOD|Boujdour
MA-BOM|Boulemane
MA-CAS|Casablanca
MA-CHE|Chefchaouene
MA-CHI|Chichaoua
MA-ERR|Errachidia
MA-ESI|Essaouira
MA-ESM|Es Smara
MA-FES|Fès
MA-FIG|Figuig
MA-GUE|Guelmim
MA-HAJ|El Hajeb
MA-HAO|Al Haouz
MA-HOC|Al Hoceïma
MA-IFR|Ifrane
MA-JDI|El Jadida
MA-JRA|Jerada
MA-KEN|Kénitra
MA-KES|Kelaat Sraghna
MA-KHE|Khemisaet
MA-KHN|Khenifra
MA-KHO|Khouribga
MA-LAA|Laâyoune (EH)
MA-LAP|Larache
MA-MAR|Marrakech
MA-MEK|Meknsès
MA-MEL|Aït Melloul
MA-NAD|Nador
MA-OUA|Ouarzazate
MA-OUD|Oued ed Dahab (EH)
MA-OUJ|Oujda
MA-RBA|Rabat-Salé
MA-SAF|Safi
MA-SEF|Sefrou
MA-SET|Settat
MA-SIK|Sidl Kacem
MA-TAO|Taounate
MA-TAR|Taroudannt
MA-TAT|Tata
MA-TAZ|Taza
MA-TET|Tétouan
MA-TIZ|Tiznit
MA-TNG|Tanger
MA-TNT|Tan-Tan
MA-U-A|
MC-U-A|
MC-U-A|
MD-AN|Anenii Noi
MD-BE|Bender
MD-BL|B?l?i
MD-BR|Briceni
MD-BS|Basarabeanca
MD-C|Chi?in?u
MD-CC|Cameanca
MD-CG|Ceadîr-Lunga
MD-CH|Cahul
MD-CL|C?l?ra?i
MD-CM|Cimi?lia
MD-CN|Cainari
MD-CO|Comrat
MD-CR|Criuleni
MD-CS|C?u?eni/C?u?ani
MD-CT|Cantemir
MD-DB|Dub?sari
MD-DN|Dondu?eni
MD-DR|Drochia
MD-ED|Edine?
MD-FL|F?le?ti
MD-FR|Flore?ti
MD-GL|Glodeni
MD-HN|Hînce?ti
MD-IL|Ialoveni
MD-LV|Leova
MD-NS|Nisporeni
MD-OC|Ocni?a
MD-OR|Orhei
MD-RB|Rîbni?a
MD-RS|Rî?cani
MD-RZ|Rezina
MD-SG|Sîngerei
MD-SL|Slobozia
MD-SR|Soroca
MD-ST|Str??eni
MD-SV|?tefan-Vod?
MD-TA|Taraclia
MD-TL|Telene?ti
MD-TR|Tiraspol
MD-U-A|
MD-UN|Ungheni
MD-VL|Vulc?ne?ti
MD-AN|Anenii Noi
MD-BE|Bender
MD-BL|B?l?i
MD-BR|Briceni
MD-BS|Basarabeanca
MD-C|Chi?in?u
MD-CC|Cameanca
MD-CG|Ceadîr-Lunga
MD-CH|Cahul
MD-CL|C?l?ra?i
MD-CM|Cimi?lia
MD-CN|Cainari
MD-CO|Comrat
MD-CR|Criuleni
MD-CS|C?u?eni/C?u?ani
MD-CT|Cantemir
MD-DB|Dub?sari
MD-DN|Dondu?eni
MD-DR|Drochia
MD-ED|Edine?
MD-FL|F?le?ti
MD-FR|Flore?ti
MD-GL|Glodeni
MD-HN|Hînce?ti
MD-IL|Ialoveni
MD-LV|Leova
MD-NS|Nisporeni
MD-OC|Ocni?a
MD-OR|Orhei
MD-RB|Rîbni?a
MD-RS|Rî?cani
MD-RZ|Rezina
MD-SG|Sîngerei
MD-SL|Slobozia
MD-SR|Soroca
MD-ST|Str??eni
MD-SV|?tefan-Vod?
MD-TA|Taraclia
MD-TL|Telene?ti
MD-TR|Tiraspol
MD-U-A|
MD-UN|Ungheni
MD-VL|Vulc?ne?ti
ME-01|Andrijevica Municipality
ME-02|Bar Municipality
ME-03|Berane Municipality
ME-04|Bijelo Polje Municipality
ME-05|Budva Municipality
ME-06|Cetinje Municipality
ME-07|Danilovgrad Municipality
ME-08|Herceg-Novi Municipality
ME-09|Kolašin Municipality
ME-10|Kotor Municipality
ME-11|Mojkovac Municipality
ME-12|Nikši? Municipality
ME-13|Plav Municipality
ME-14|Pljevlja Municipality
ME-15|Plužine Municipality
ME-16|Podgorica Municipality
ME-17|Rožaje Municipality
ME-18|Šavnik Municipality
ME-19|Tivat Municipality
ME-20|Ulcinj Municipality
ME-21|Žabljak Municipality
ME-U-A|
ME-01|Andrijevica Municipality
ME-02|Bar Municipality
ME-03|Berane Municipality
ME-04|Bijelo Polje Municipality
ME-05|Budva Municipality
ME-06|Cetinje Municipality
ME-07|Danilovgrad Municipality
ME-08|Herceg-Novi Municipality
ME-09|Kolašin Municipality
ME-10|Kotor Municipality
ME-11|Mojkovac Municipality
ME-12|Nikši? Municipality
ME-13|Plav Municipality
ME-14|Pljevlja Municipality
ME-15|Plužine Municipality
ME-16|Podgorica Municipality
ME-17|Rožaje Municipality
ME-18|Šavnik Municipality
ME-19|Tivat Municipality
ME-20|Ulcinj Municipality
ME-21|Žabljak Municipality
ME-U-A|
MF-U-A|
MF-U-A|
MG-A|Toamasina
MG-D|Antsiranana
MG-F|Fianarantsoa
MG-M|Mahajanga
MG-T|Antananarivo
MG-U|Toliara
MG-U-A|
MG-A|Toamasina
MG-D|Antsiranana
MG-F|Fianarantsoa
MG-M|Mahajanga
MG-T|Antananarivo
MG-U|Toliara
MG-U-A|
MH-ALK|Ailuk
MH-ALL|Ailinglapalap
MH-ARN|Arno
MH-AUR|Aur
MH-BIK|Bikini
MH-EBO|Ebon
MH-ENI|Eniwetok
MH-JAL|Jaluit
MH-KIL|Kili
MH-KWA|Kwajalein
MH-LAE|Lae
MH-LIB|Lib
MH-LIK|Likiep
MH-MAJ|Majuro
MH-MAL|Maloelap
MH-MEJ|Mejit
MH-MIL|Mili
MH-NMK|Namorik
MH-NMU|Namu
MH-RON|Rongelap
MH-U-A|
MH-UJA|Ujae
MH-UJL|Ujelang
MH-UTI|Utirik
MH-WTJ|Wotje
MH-WTN|Wotho
MH-ALK|Ailuk
MH-ALL|Ailinglapalap
MH-ARN|Arno
MH-AUR|Aur
MH-BIK|Bikini
MH-EBO|Ebon
MH-ENI|Eniwetok
MH-JAL|Jaluit
MH-KIL|Kili
MH-KWA|Kwajalein
MH-LAE|Lae
MH-LIB|Lib
MH-LIK|Likiep
MH-MAJ|Majuro
MH-MAL|Maloelap
MH-MEJ|Mejit
MH-MIL|Mili
MH-NMK|Namorik
MH-NMU|Namu
MH-RON|Rongelap
MH-U-A|
MH-UJA|Ujae
MH-UJL|Ujelang
MH-UTI|Utirik
MH-WTJ|Wotje
MH-WTN|Wotho
MK-01|Aerodrom municipality
MK-02|Ara?inovo
MK-03|Berovo
MK-04|Bitola
MK-05|Bogdanci
MK-06|Bogovinje
MK-07|Bosilovo
MK-08|Brvenica
MK-09|Butel
MK-10|Valandovo
MK-11|Vasilevo
MK-12|Vev?ani
MK-13|Veles
MK-14|Vinica
MK-15|Vraneštica
MK-16|Vrap?ište
MK-17|Gazi Baba
MK-18|Gevgelija
MK-19|Gostivar
MK-20|Gradsko
MK-21|Debar
MK-22|Debarca
MK-23|Del?evo
MK-24|Demir Kapija
MK-25|Demir Hisar
MK-26|Dojran
MK-27|Dolneni
MK-28|Drugovo
MK-29|Gjor?e Petrov
MK-30|Želino
MK-31|Zajas
MK-32|Zelenikovo
MK-33|Zrnovci
MK-34|Ilinden
MK-35|Jegunovce
MK-36|Kavadarci
MK-37|Karbinci
MK-38|Karpoš
MK-39|Kisela Voda
MK-40|Ki?evo
MK-41|Kon?e
MK-42|Ko?ani
MK-43|Kratovo
MK-44|Kriva Palanka
MK-45|Krivogaštani
MK-46|Kruševo
MK-47|Kumanovo
MK-48|Lipkovo
MK-49|Lozovo
MK-50|Mavrovo-i-Rostuša
MK-51|Makedonska Kamenica
MK-52|Makedonski Brod
MK-53|Mogila
MK-54|Negotino
MK-55|Novaci
MK-56|Novo Selo
MK-57|Oslomej
MK-58|Ohrid
MK-59|Petrovec
MK-60|Peh?evo
MK-61|Plasnica
MK-62|Prilep
MK-63|Probištip
MK-64|Radoviš
MK-65|Rankovce
MK-66|Resen
MK-67|Rosoman
MK-68|Saraj
MK-69|Sveti Nikole
MK-70|Sopište
MK-71|Staro Nagori?ane
MK-72|Struga
MK-73|Strumica
MK-74|Studeni?ani
MK-75|Tearce
MK-76|Tetovo
MK-77|Centar
MK-78|Centar Župa
MK-79|?air
MK-80|?aška
MK-81|?ešinovo-Obleševo
MK-82|?u?er Sandevo
MK-83|Štip
MK-84|Šuto Orizari
MK-U-A|
MK-01|Aerodrom municipality
MK-02|Ara?inovo
MK-03|Berovo
MK-04|Bitola
MK-05|Bogdanci
MK-06|Bogovinje
MK-07|Bosilovo
MK-08|Brvenica
MK-09|Butel
MK-10|Valandovo
MK-11|Vasilevo
MK-12|Vev?ani
MK-13|Veles
MK-14|Vinica
MK-15|Vraneštica
MK-16|Vrap?ište
MK-17|Gazi Baba
MK-18|Gevgelija
MK-19|Gostivar
MK-20|Gradsko
MK-21|Debar
MK-22|Debarca
MK-23|Del?evo
MK-24|Demir Kapija
MK-25|Demir Hisar
MK-26|Dojran
MK-27|Dolneni
MK-28|Drugovo
MK-29|Gjor?e Petrov
MK-30|Želino
MK-31|Zajas
MK-32|Zelenikovo
MK-33|Zrnovci
MK-34|Ilinden
MK-35|Jegunovce
MK-36|Kavadarci
MK-37|Karbinci
MK-38|Karpoš
MK-39|Kisela Voda
MK-40|Ki?evo
MK-41|Kon?e
MK-42|Ko?ani
MK-43|Kratovo
MK-44|Kriva Palanka
MK-45|Krivogaštani
MK-46|Kruševo
MK-47|Kumanovo
MK-48|Lipkovo
MK-49|Lozovo
MK-50|Mavrovo-i-Rostuša
MK-51|Makedonska Kamenica
MK-52|Makedonski Brod
MK-53|Mogila
MK-54|Negotino
MK-55|Novaci
MK-56|Novo Selo
MK-57|Oslomej
MK-58|Ohrid
MK-59|Petrovec
MK-60|Peh?evo
MK-61|Plasnica
MK-62|Prilep
MK-63|Probištip
MK-64|Radoviš
MK-65|Rankovce
MK-66|Resen
MK-67|Rosoman
MK-68|Saraj
MK-69|Sveti Nikole
MK-70|Sopište
MK-71|Staro Nagori?ane
MK-72|Struga
MK-73|Strumica
MK-74|Studeni?ani
MK-75|Tearce
MK-76|Tetovo
MK-77|Centar
MK-78|Centar Župa
MK-79|?air
MK-80|?aška
MK-81|?ešinovo-Obleševo
MK-82|?u?er Sandevo
MK-83|Štip
MK-84|Šuto Orizari
MK-U-A|
ML-1|Kayes
ML-2|Koulikoro
ML-3|Sikasso
ML-4|Ségou
ML-5|Mopti
ML-6|Tombouctou
ML-7|Gao
ML-8|Kidal
ML-BK0|Bamako
ML-U-A|
ML-1|Kayes
ML-2|Koulikoro
ML-3|Sikasso
ML-4|Ségou
ML-5|Mopti
ML-6|Tombouctou
ML-7|Gao
ML-8|Kidal
ML-BK0|Bamako
ML-U-A|
MM-01|Sagaing Division
MM-02|Bago Division
MM-03|Magway Division
MM-04|Mandalay Division
MM-05|Tanintharyi Division
MM-06|Yangon Division
MM-07|Ayeyarwady Division
MM-11|Kachin State
MM-12|Kayah State
MM-13|Kayin State
MM-14|Chin State
MM-15|Mon State
MM-16|Rakhine State
MM-17|Shan State
MM-U-A|
MM-01|Sagaing Division
MM-02|Bago Division
MM-03|Magway Division
MM-04|Mandalay Division
MM-05|Tanintharyi Division
MM-06|Yangon Division
MM-07|Ayeyarwady Division
MM-11|Kachin State
MM-12|Kayah State
MM-13|Kayin State
MM-14|Chin State
MM-15|Mon State
MM-16|Rakhine State
MM-17|Shan State
MM-U-A|
MN-035|Orhon
MN-037|Darhan uul
MN-039|Hentiy
MN-041|Khövsgöl
MN-043|Khovd
MN-046|Uvs
MN-047|Tov
MN-049|Selenge
MN-051|Shbaatar
MN-053|Ömnögovi
MN-055|Övörkhangai
MN-057|Dzavhan
MN-059|DundgovL
MN-061|Dornod
MN-063|Dornogov
MN-064|Govi-Smber
MN-065|Govi-Altay
MN-067|Bulgan
MN-069|Bayanhongor
MN-071|Bayan-Olgiy
MN-073|Arhangay
MN-1|Ulanbaatar
MN-U-A|
MN-035|Orhon
MN-037|Darhan uul
MN-039|Hentiy
MN-041|Khövsgöl
MN-043|Khovd
MN-046|Uvs
MN-047|Tov
MN-049|Selenge
MN-051|Shbaatar
MN-053|Ömnögovi
MN-055|Övörkhangai
MN-057|Dzavhan
MN-059|DundgovL
MN-061|Dornod
MN-063|Dornogov
MN-064|Govi-Smber
MN-065|Govi-Altay
MN-067|Bulgan
MN-069|Bayanhongor
MN-071|Bayan-Olgiy
MN-073|Arhangay
MN-1|Ulanbaatar
MN-U-A|
MO-U-A|
MO-U-A|
MP-U-A|
MP-U-A|
MQ-U-A|
MQ-U-A|
MR-01|Hodh ech Chargui
MR-02|Hodh el Charbi
MR-03|Assaba
MR-04|Gorgol
MR-05|Brakna
MR-06|Trarza
MR-07|Adrar
MR-08|Dakhlet Nouadhibou
MR-09|Tagant
MR-10|Guidimaka
MR-11|Tiris Zemmour
MR-12|Inchiri
MR-NKC|Nouakchott
MR-U-A|
MR-01|Hodh ech Chargui
MR-02|Hodh el Charbi
MR-03|Assaba
MR-04|Gorgol
MR-05|Brakna
MR-06|Trarza
MR-07|Adrar
MR-08|Dakhlet Nouadhibou
MR-09|Tagant
MR-10|Guidimaka
MR-11|Tiris Zemmour
MR-12|Inchiri
MR-NKC|Nouakchott
MR-U-A|
MS-U-A|
MS-U-A|
MT-01|Attard
MT-02|Balzan
MT-03|Birgu
MT-04|Birkirkara
MT-05|Bir?ebbu?a
MT-06|Bormla
MT-07|Dingli
MT-08|Fgura
MT-09|Floriana
MT-10|Fontana
MT-11|Gudja
MT-12|Gzira
MT-13|G?ajnsielem
MT-14|G?arb
MT-15|G?arg?ur
MT-16|G?asri
MT-17|G?axaq
MT-18|Hamrun
MT-19|Iklin
MT-20|Isla
MT-21|Kalkara
MT-22|Ker?em
MT-23|Kirkop
MT-24|Lija
MT-25|Luqa
MT-26|Marsa
MT-27|Marsaskala
MT-28|Marsaxlokk
MT-29|Mdina
MT-30|Mellie?a
MT-31|Mgarr
MT-32|Mosta
MT-33|Mqabba
MT-34|Msida
MT-35|Mtarfa
MT-36|Munxar
MT-37|Nadur
MT-38|Naxxar
MT-39|Paola
MT-40|Pembroke
MT-41|Pietà
MT-42|Qala
MT-43|Qormi
MT-44|Qrendi
MT-45|Rabat Gozo
MT-46|Rabat Malta
MT-47|Safi
MT-48|Saint Julian's
MT-49|Saint John
MT-50|Saint Lawrence
MT-51|Saint Paul's Bay
MT-52|Sannat
MT-53|Saint Lucia's
MT-54|Santa Venera
MT-55|Si??iewi
MT-56|Sliema
MT-57|Swieqi
MT-58|Ta' Xbiex
MT-59|Tarxien
MT-60|Valletta
MT-61|Xag?ra
MT-62|Xewkija
MT-63|Xg?ajra
MT-64|?abbar
MT-65|?ebbu? Gozo
MT-66|?ebbu? Malta
MT-67|?ejtun
MT-68|?urrieq
MT-U-A|
MT-01|Attard
MT-02|Balzan
MT-03|Birgu
MT-04|Birkirkara
MT-05|Bir?ebbu?a
MT-06|Bormla
MT-07|Dingli
MT-08|Fgura
MT-09|Floriana
MT-10|Fontana
MT-11|Gudja
MT-12|Gzira
MT-13|G?ajnsielem
MT-14|G?arb
MT-15|G?arg?ur
MT-16|G?asri
MT-17|G?axaq
MT-18|Hamrun
MT-19|Iklin
MT-20|Isla
MT-21|Kalkara
MT-22|Ker?em
MT-23|Kirkop
MT-24|Lija
MT-25|Luqa
MT-26|Marsa
MT-27|Marsaskala
MT-28|Marsaxlokk
MT-29|Mdina
MT-30|Mellie?a
MT-31|Mgarr
MT-32|Mosta
MT-33|Mqabba
MT-34|Msida
MT-35|Mtarfa
MT-36|Munxar
MT-37|Nadur
MT-38|Naxxar
MT-39|Paola
MT-40|Pembroke
MT-41|Pietà
MT-42|Qala
MT-43|Qormi
MT-44|Qrendi
MT-45|Rabat Gozo
MT-46|Rabat Malta
MT-47|Safi
MT-48|Saint Julian's
MT-49|Saint John
MT-50|Saint Lawrence
MT-51|Saint Paul's Bay
MT-52|Sannat
MT-53|Saint Lucia's
MT-54|Santa Venera
MT-55|Si??iewi
MT-56|Sliema
MT-57|Swieqi
MT-58|Ta' Xbiex
MT-59|Tarxien
MT-60|Valletta
MT-61|Xag?ra
MT-62|Xewkija
MT-63|Xg?ajra
MT-64|?abbar
MT-65|?ebbu? Gozo
MT-66|?ebbu? Malta
MT-67|?ejtun
MT-68|?urrieq
MT-U-A|
MU-AG|Agalega Islands
MU-BL|Black River
MU-BR|Beau Bassin-Rose Hill
MU-CC|Cargados Carajos Shoals
MU-CU|Curepipe
MU-FL|Flacq
MU-GP|Grand Port
MU-MO|Moka
MU-PA|Pamplemousses
MU-PL|Port Louis (district)
MU-PU|Port Louis
MU-PW|Plaines Wilhems
MU-QB|Quatre Bornes
MU-RO|Rodrigues Island
MU-RP|Riviere du Rempart
MU-SA|Savanne
MU-U-A|
MU-VP|Vacosa-Phoenix
MU-AG|Agalega Islands
MU-BL|Black River
MU-BR|Beau Bassin-Rose Hill
MU-CC|Cargados Carajos Shoals
MU-CU|Curepipe
MU-FL|Flacq
MU-GP|Grand Port
MU-MO|Moka
MU-PA|Pamplemousses
MU-PL|Port Louis (district)
MU-PU|Port Louis
MU-PW|Plaines Wilhems
MU-QB|Quatre Bornes
MU-RO|Rodrigues Island
MU-RP|Riviere du Rempart
MU-SA|Savanne
MU-U-A|
MU-VP|Vacosa-Phoenix
MV-01|Seenu Atoll
MV-02|Alif Alif Atoll
MV-03|Lhaviyani
MV-04|Vaavu
MV-05|Laamu Atoll
MV-07|Haa Alif
MV-08|Thaa
MV-12|Meemu
MV-13|Raa
MV-14|Faafu
MV-17|Dhaalu
MV-20|Baa
MV-23|Haa Dhaalu Atoll
MV-24|Shaviyani
MV-25|Noonu
MV-26|Kaafu
MV-27|Gaaf Alif
MV-28|Gaafu Dhaalu Atoll
MV-29|Gnaviyani
MV-MLE|Malé Capital
MV-U-A|
MV-01|Seenu Atoll
MV-02|Alif Alif Atoll
MV-03|Lhaviyani
MV-04|Vaavu
MV-05|Laamu Atoll
MV-07|Haa Alif
MV-08|Thaa
MV-12|Meemu
MV-13|Raa
MV-14|Faafu
MV-17|Dhaalu
MV-20|Baa
MV-23|Haa Dhaalu Atoll
MV-24|Shaviyani
MV-25|Noonu
MV-26|Kaafu
MV-27|Gaaf Alif
MV-28|Gaafu Dhaalu Atoll
MV-29|Gnaviyani
MV-MLE|Malé Capital
MV-U-A|
MW-BA|Balaka
MW-BL|Blantyre
MW-CK|Chikwawa
MW-CR|Chiradzulu
MW-CT|Chitipa
MW-DE|Dedza
MW-DO|Dowa
MW-KR|Karonga
MW-KS|Kasungu
MW-LI|Lilongwe
MW-LK|Likoma Island
MW-MC|Mchinji
MW-MG|Mangochi
MW-MH|Machinga
MW-MU|Mulanje
MW-MW|Mwanza
MW-MZ|Mzimba
MW-NB|Nkhata Bay
MW-NI|Ntchisi
MW-NK|Nkhotakota
MW-NS|Nsanje
MW-NU|Ntcheu
MW-PH|Phalomba
MW-RU|Rumphi
MW-SA|Salima
MW-TH|Thyolo
MW-U-A|
MW-ZO|Zomba
MW-BA|Balaka
MW-BL|Blantyre
MW-CK|Chikwawa
MW-CR|Chiradzulu
MW-CT|Chitipa
MW-DE|Dedza
MW-DO|Dowa
MW-KR|Karonga
MW-KS|Kasungu
MW-LI|Lilongwe
MW-LK|Likoma Island
MW-MC|Mchinji
MW-MG|Mangochi
MW-MH|Machinga
MW-MU|Mulanje
MW-MW|Mwanza
MW-MZ|Mzimba
MW-NB|Nkhata Bay
MW-NI|Ntchisi
MW-NK|Nkhotakota
MW-NS|Nsanje
MW-NU|Ntcheu
MW-PH|Phalomba
MW-RU|Rumphi
MW-SA|Salima
MW-TH|Thyolo
MW-U-A|
MW-ZO|Zomba
MX-AGU|Aguascalientes
MX-BCN|Baja California
MX-BCS|Baja California Sur
MX-CAM|Campeche
MX-CHH|Chihushua
MX-CHP|Chiapas
MX-COA|Coahuila
MX-COL|Col ima
MX-DIF|Distrito Federal
MX-DUR|Durango
MX-GRO|Guerrero
MX-GUA|Guanajuato
MX-HID|Hidalgo
MX-JAL|Jalisco
MX-MEX|Mexico
MX-MIC|Michoacin
MX-MOR|Moreloa
MX-NAY|Nayarit
MX-NLE|Nuevo Leon
MX-OAX|Oaxaca
MX-PUE|Puebla
MX-QUE|Queretaro
MX-ROO|Quintana Roo
MX-SIN|Sinaloa
MX-SLP|San Luis Potosi
MX-SON|Sonora
MX-TAB|Tabasco
MX-TAM|Tamaulipas
MX-TLA|Tlaxcala
MX-U-A|
MX-VER|Veracruz
MX-YUC|Yucatan
MX-ZAC|Zacatecas
MX-AGU|Aguascalientes
MX-BCN|Baja California
MX-BCS|Baja California Sur
MX-CAM|Campeche
MX-CHH|Chihushua
MX-CHP|Chiapas
MX-COA|Coahuila
MX-COL|Col ima
MX-DIF|Distrito Federal
MX-DUR|Durango
MX-GRO|Guerrero
MX-GUA|Guanajuato
MX-HID|Hidalgo
MX-JAL|Jalisco
MX-MEX|Mexico
MX-MIC|Michoacin
MX-MOR|Moreloa
MX-NAY|Nayarit
MX-NLE|Nuevo Leon
MX-OAX|Oaxaca
MX-PUE|Puebla
MX-QUE|Queretaro
MX-ROO|Quintana Roo
MX-SIN|Sinaloa
MX-SLP|San Luis Potosi
MX-SON|Sonora
MX-TAB|Tabasco
MX-TAM|Tamaulipas
MX-TLA|Tlaxcala
MX-U-A|
MX-VER|Veracruz
MX-YUC|Yucatan
MX-ZAC|Zacatecas
MY-01|Johor
MY-02|Kedah
MY-03|Kelantan
MY-04|Melaka
MY-05|Negeri Sembilan
MY-06|Pahang
MY-07|Pulau Pinang
MY-08|Perak
MY-09|Perlis
MY-10|Selangor
MY-11|Terengganu
MY-12|Sabah
MY-13|Sarawak
MY-14|Wilayah Persekutuan Kuala Lumpur
MY-15|Wilayah Persekutuan Labuan
MY-16|Wilayah Persekutuan Putrajaya
MY-U-A|
MY-01|Johor
MY-02|Kedah
MY-03|Kelantan
MY-04|Melaka
MY-05|Negeri Sembilan
MY-06|Pahang
MY-07|Pulau Pinang
MY-08|Perak
MY-09|Perlis
MY-10|Selangor
MY-11|Terengganu
MY-12|Sabah
MY-13|Sarawak
MY-14|Wilayah Persekutuan Kuala Lumpur
MY-15|Wilayah Persekutuan Labuan
MY-16|Wilayah Persekutuan Putrajaya
MY-U-A|
MZ-A|Niassa Province
MZ-B|Manica Province
MZ-G|Gaza Province
MZ-I|Inhambane Province
MZ-L|Maputo Province
MZ-MPM|Maputo (city)
MZ-N|Nampula Province
MZ-P|Cabo Delgado Province
MZ-Q|Zambezia Province
MZ-S|Sofala Province
MZ-T|Tete Province
MZ-U-A|
MZ-A|Niassa Province
MZ-B|Manica Province
MZ-G|Gaza Province
MZ-I|Inhambane Province
MZ-L|Maputo Province
MZ-MPM|Maputo (city)
MZ-N|Nampula Province
MZ-P|Cabo Delgado Province
MZ-Q|Zambezia Province
MZ-S|Sofala Province
MZ-T|Tete Province
MZ-U-A|
NA-CA|Caprivi
NA-ER|Erongo
NA-HA|Hardap
NA-KA|Karas
NA-KH|Khomae
NA-KU|Kunene
NA-OD|Otjozondjupa
NA-OH|Omaheke
NA-OK|Okavango
NA-ON|Oshana
NA-OS|Omusati
NA-OT|Oshikoto
NA-OW|Ohangwena
NA-U-A|
NA-CA|Caprivi
NA-ER|Erongo
NA-HA|Hardap
NA-KA|Karas
NA-KH|Khomae
NA-KU|Kunene
NA-OD|Otjozondjupa
NA-OH|Omaheke
NA-OK|Okavango
NA-ON|Oshana
NA-OS|Omusati
NA-OT|Oshikoto
NA-OW|Ohangwena
NA-U-A|
NC-U-A|
NC-U-A|
NE-1|Agadez Region
NE-2|Diffa Region
NE-3|Dosso Region
NE-4|Maradi Region
NE-5|Tahoua Region
NE-6|Tillabéri Region
NE-7|Zinder Region
NE-8|Niamey Capital District
NE-U-A|
NE-1|Agadez Region
NE-2|Diffa Region
NE-3|Dosso Region
NE-4|Maradi Region
NE-5|Tahoua Region
NE-6|Tillabéri Region
NE-7|Zinder Region
NE-8|Niamey Capital District
NE-U-A|
NF-U-A|
NF-U-A|
NG-AB|Abia
NG-AD|Adamawa
NG-AK|Akwa Ibom
NG-AN|Anambra
NG-BA|Bauchi
NG-BE|Benue
NG-BO|Borno
NG-BY|Bayelsa
NG-CR|Cross River
NG-DE|Delta
NG-EB|Ebonyi
NG-ED|Edo
NG-EK|Ekiti
NG-EN|Enugu
NG-FC|Abuja Capital Territory
NG-GO|Gombe
NG-IM|Imo
NG-JI|Jigawa
NG-KD|Kaduna
NG-KE|Kebbi
NG-KN|Kano
NG-KO|Kogi
NG-KT|Katsina
NG-KW|Kwara
NG-LA|Lagos
NG-NA|Nassarawa
NG-NI|Niger
NG-OG|Ogun
NG-ON|Ondo
NG-OS|Osun
NG-OY|Oyo
NG-PL|Plateau
NG-RI|Rivers
NG-SO|Sokoto
NG-TA|Taraba
NG-U-A|
NG-YO|Yobe
NG-ZA|Zamfara
NG-AB|Abia
NG-AD|Adamawa
NG-AK|Akwa Ibom
NG-AN|Anambra
NG-BA|Bauchi
NG-BE|Benue
NG-BO|Borno
NG-BY|Bayelsa
NG-CR|Cross River
NG-DE|Delta
NG-EB|Ebonyi
NG-ED|Edo
NG-EK|Ekiti
NG-EN|Enugu
NG-FC|Abuja Capital Territory
NG-GO|Gombe
NG-IM|Imo
NG-JI|Jigawa
NG-KD|Kaduna
NG-KE|Kebbi
NG-KN|Kano
NG-KO|Kogi
NG-KT|Katsina
NG-KW|Kwara
NG-LA|Lagos
NG-NA|Nassarawa
NG-NI|Niger
NG-OG|Ogun
NG-ON|Ondo
NG-OS|Osun
NG-OY|Oyo
NG-PL|Plateau
NG-RI|Rivers
NG-SO|Sokoto
NG-TA|Taraba
NG-U-A|
NG-YO|Yobe
NG-ZA|Zamfara
NI-AN|Atlantico Norte
NI-AS|Atlantico Sur
NI-BO|Boaco
NI-CA|Carazo
NI-CI|Chinandega
NI-CO|Chontales
NI-ES|Esteli
NI-GR|Grenada
NI-JI|Jinotega
NI-LE|Leon
NI-MD|Madriz
NI-MN|Managua
NI-MS|Masaya
NI-MT|Matagalpa
NI-NS|Nueva Segovia
NI-RI|Rivas
NI-SJ|Rio San Juan
NI-U-A|
NI-AN|Atlantico Norte
NI-AS|Atlantico Sur
NI-BO|Boaco
NI-CA|Carazo
NI-CI|Chinandega
NI-CO|Chontales
NI-ES|Esteli
NI-GR|Grenada
NI-JI|Jinotega
NI-LE|Leon
NI-MD|Madriz
NI-MN|Managua
NI-MS|Masaya
NI-MT|Matagalpa
NI-NS|Nueva Segovia
NI-RI|Rivas
NI-SJ|Rio San Juan
NI-U-A|
NL-DR|Drente
NL-FL|Flevoland
NL-FR|Friesland
NL-GE|Gelderland
NL-GR|Groningen
NL-LI|Limburg
NL-NB|Noord-Brabant
NL-NH|Noord-Holland
NL-OV|Overijssel
NL-U-A|
NL-UT|Utrecht
NL-ZH|Zuid-Holland
NL-ZL|Zeeland
NL-DR|Drente
NL-FL|Flevoland
NL-FR|Friesland
NL-GE|Gelderland
NL-GR|Groningen
NL-LI|Limburg
NL-NB|Noord-Brabant
NL-NH|Noord-Holland
NL-OV|Overijssel
NL-U-A|
NL-UT|Utrecht
NL-ZH|Zuid-Holland
NL-ZL|Zeeland
NO-01|Østfold
NO-02|Akershus
NO-03|Oslo
NO-04|Hedmark
NO-05|Oppland
NO-06|Buskerud
NO-07|Vestfold
NO-08|Telemark
NO-09|Aust-Agder
NO-10|Vest-Agder
NO-11|Rogaland
NO-12|Hordaland
NO-14|Sogn og Fjordane
NO-15|Møre og Romsdal
NO-16|Sør-Trøndelag
NO-17|Nord-Trøndelag
NO-18|Nordland
NO-19|Troms
NO-20|Finnmark
NO-21|Svalbard
NO-22|Jan Mayen
NO-U-A|
NO-01|Østfold
NO-02|Akershus
NO-03|Oslo
NO-04|Hedmark
NO-05|Oppland
NO-06|Buskerud
NO-07|Vestfold
NO-08|Telemark
NO-09|Aust-Agder
NO-10|Vest-Agder
NO-11|Rogaland
NO-12|Hordaland
NO-14|Sogn og Fjordane
NO-15|Møre og Romsdal
NO-16|Sør-Trøndelag
NO-17|Nord-Trøndelag
NO-18|Nordland
NO-19|Troms
NO-20|Finnmark
NO-21|Svalbard
NO-22|Jan Mayen
NO-U-A|
NP-BA|Bagmati
NP-BH|Bheri
NP-DH|Dhawalagiri
NP-GA|Gandaki
NP-JA|Janakpur
NP-KA|Karnali
NP-KO|Kosi
NP-LU|Lumbini
NP-MA|Mahakali
NP-ME|Mechi
NP-NA|Narayani
NP-RA|Rapti
NP-SA|Sagarmatha
NP-SE|Seti
NP-U-A|
NP-BA|Bagmati
NP-BH|Bheri
NP-DH|Dhawalagiri
NP-GA|Gandaki
NP-JA|Janakpur
NP-KA|Karnali
NP-KO|Kosi
NP-LU|Lumbini
NP-MA|Mahakali
NP-ME|Mechi
NP-NA|Narayani
NP-RA|Rapti
NP-SA|Sagarmatha
NP-SE|Seti
NP-U-A|
NR-01|Aiwo
NR-02|Anabar
NR-03|Anetan
NR-04|Anibare
NR-05|Baiti
NR-06|Boe
NR-07|Buada
NR-08|Denigomodu
NR-09|Ewa
NR-10|Ijuw
NR-11|Meneng
NR-12|Nibok
NR-13|Uaboe
NR-14|Yaren
NR-U-A|
NR-01|Aiwo
NR-02|Anabar
NR-03|Anetan
NR-04|Anibare
NR-05|Baiti
NR-06|Boe
NR-07|Buada
NR-08|Denigomodu
NR-09|Ewa
NR-10|Ijuw
NR-11|Meneng
NR-12|Nibok
NR-13|Uaboe
NR-14|Yaren
NR-U-A|
NU-U-A|
NU-U-A|
NZ-AUK|Auckland Region
NZ-BOP|Bay of Plenty Region
NZ-CAN|Canterbury Region
NZ-GIS|Gisborne Region
NZ-HKB|Hawke's Bay Region
NZ-MBH|Marlborough Region
NZ-MWT|Manawatu-Wanganui Region
NZ-NSN|Nelson Region
NZ-NTL|Northland Region
NZ-OTA|Otago Region
NZ-STL|Southland Region
NZ-TAS|Tasman Region
NZ-TKI|Taranaki Region
NZ-U-A|
NZ-WGN|Wellington Region
NZ-WKO|Waikato Region
NZ-WTC|West Coast Region
NZ-AUK|Auckland Region
NZ-BOP|Bay of Plenty Region
NZ-CAN|Canterbury Region
NZ-GIS|Gisborne Region
NZ-HKB|Hawke's Bay Region
NZ-MBH|Marlborough Region
NZ-MWT|Manawatu-Wanganui Region
NZ-NSN|Nelson Region
NZ-NTL|Northland Region
NZ-OTA|Otago Region
NZ-STL|Southland Region
NZ-TAS|Tasman Region
NZ-TKI|Taranaki Region
NZ-U-A|
NZ-WGN|Wellington Region
NZ-WKO|Waikato Region
NZ-WTC|West Coast Region
OM-BA|Al Batinah
OM-DA|Ad Dakhillyah
OM-JA|Al Janblyah
OM-MA|Masqat
OM-MU|Musandam
OM-SH|Ash Sharqlyah
OM-U-A|
OM-WU|Al Wusta
OM-ZA|Az Zahirah
OM-BA|Al Batinah
OM-DA|Ad Dakhillyah
OM-JA|Al Janblyah
OM-MA|Masqat
OM-MU|Musandam
OM-SH|Ash Sharqlyah
OM-U-A|
OM-WU|Al Wusta
OM-ZA|Az Zahirah
PA-1|Bocas del Toro
PA-2|Cocle
PA-3|Colón
PA-4|Chiriqui
PA-5|Darien
PA-6|Herrera
PA-7|Loa Santoa
PA-8|Panama
PA-9|Veraguas
PA-Q|Comarca de San Blas
PA-U-A|
PA-1|Bocas del Toro
PA-2|Cocle
PA-3|Colón
PA-4|Chiriqui
PA-5|Darien
PA-6|Herrera
PA-7|Loa Santoa
PA-8|Panama
PA-9|Veraguas
PA-Q|Comarca de San Blas
PA-U-A|
PE-AMA|Amazonas Region
PE-ANC|Ancash Region
PE-APU|Apurímac Region
PE-ARE|Arequipa Region
PE-AYA|Ayacucho Region
PE-CAJ|Cajamarca Region
PE-CAL|El Callao Region
PE-CUS|Cuzco Region
PE-HUC|Huánuco Region
PE-HUV|Huancavelica Region
PE-ICA|Ica Region
PE-JUN|Junín Region
PE-LAL|La Libertad Region
PE-LAM|Lambayeque Region
PE-LIM|Lima Region
PE-LOR|Loreto Region
PE-MDD|Madre de Dios Region
PE-MOQ|Moquegua Region
PE-PAS|Pasco Region
PE-PIU|Piura Region
PE-PUN|Puno Region
PE-SAM|San Martín Region
PE-TAC|Tacna Region
PE-TUM|Tumbes Region
PE-U-A|
PE-UCA|Ucayali Region
PE-AMA|Amazonas Region
PE-ANC|Ancash Region
PE-APU|Apurímac Region
PE-ARE|Arequipa Region
PE-AYA|Ayacucho Region
PE-CAJ|Cajamarca Region
PE-CAL|El Callao Region
PE-CUS|Cuzco Region
PE-HUC|Huánuco Region
PE-HUV|Huancavelica Region
PE-ICA|Ica Region
PE-JUN|Junín Region
PE-LAL|La Libertad Region
PE-LAM|Lambayeque Region
PE-LIM|Lima Region
PE-LOR|Loreto Region
PE-MDD|Madre de Dios Region
PE-MOQ|Moquegua Region
PE-PAS|Pasco Region
PE-PIU|Piura Region
PE-PUN|Puno Region
PE-SAM|San Martín Region
PE-TAC|Tacna Region
PE-TUM|Tumbes Region
PE-U-A|
PE-UCA|Ucayali Region
PF-U-A|
PF-U-A|
PG-CPK|Chimbu
PG-CPM|Central
PG-EBR|East New Britain
PG-EHG|Eastern Highlands
PG-EPW|Enga
PG-ESW|East Sepik
PG-GPK|Gulf
PG-MBA|Milne Bay
PG-MPL|Morobe
PG-MPM|Madang
PG-MRL|Manus
PG-NCD|National Capital District (Port Moresby)
PG-NIK|New Ireland
PG-NPP|Northern (Oro)
PG-NSA|North Solomons
PG-SAN|Santaun
PG-SHM|Southern Highlands
PG-U-A|
PG-WBK|West New Britain
PG-WHM|Western Highlands
PG-WPD|Western (Fly River)
PG-CPK|Chimbu
PG-CPM|Central
PG-EBR|East New Britain
PG-EHG|Eastern Highlands
PG-EPW|Enga
PG-ESW|East Sepik
PG-GPK|Gulf
PG-MBA|Milne Bay
PG-MPL|Morobe
PG-MPM|Madang
PG-MRL|Manus
PG-NCD|National Capital District (Port Moresby)
PG-NIK|New Ireland
PG-NPP|Northern (Oro)
PG-NSA|North Solomons
PG-SAN|Santaun
PG-SHM|Southern Highlands
PG-U-A|
PG-WBK|West New Britain
PG-WHM|Western Highlands
PG-WPD|Western (Fly River)
PH-ABR|Abra
PH-AGN|Agusan del Norte
PH-AGS|Agusan del Sur
PH-AKL|Aklan
PH-ALB|Albay
PH-ANT|Antique
PH-APA|Apayao
PH-AUR|Aurora
PH-BAN|Batasn
PH-BAS|Basilan
PH-BEN|Benguet
PH-BIL|Biliran
PH-BOH|Bohol
PH-BTG|Batangas
PH-BTN|Batanes
PH-BUK|Bukidnon
PH-BUL|Bulacan
PH-CAG|Cagayan
PH-CAM|Camiguin
PH-CAN|Camarines Norte
PH-CAP|Capiz
PH-CAS|Camarines Sur
PH-CAT|Catanduanes
PH-CAV|Cavite
PH-CEB|Cebu
PH-COM|Compostela Valley
PH-DAO|Davao Oriental
PH-DAS|Davao del Sur
PH-DAV|Davao
PH-EAS|Eastern Samar
PH-GUI|Guimaras
PH-IFU|Ifugao
PH-ILI|Iloilo
PH-ILN|Ilocos Norte
PH-ILS|Ilocos Sur
PH-ISA|Isabela
PH-KAL|Kalinga-Apayso
PH-LAG|Laguna
PH-LAN|Lanao del Norte
PH-LAS|Lanao del Sur
PH-LEY|Leyte
PH-LUN|La Union
PH-MAD|Marinduque
PH-MAG|Maguindanao
PH-MAS|Masbate
PH-MDC|Mindoro Occidental
PH-MDR|Mindoro Oriental
PH-MOU|Mountain Province
PH-MSC|Misamis Occidental
PH-MSR|Misamis Oriental
PH-NCO|North Cotabato
PH-NEC|Negroe Occidental
PH-NER|Negros Oriental
PH-NSA|Northern Samar
PH-NUE|Nueva Ecija
PH-NUV|Nueva Vizcaya
PH-PAM|Pampanga
PH-PAN|Pangasinan
PH-PLW|Palawan
PH-QUE|Quezon
PH-QUI|Quirino
PH-RIZ|Rizal
PH-ROM|Romblon
PH-SAR|Sarangani
PH-SCO|South Cotabato
PH-SIG|Siquijor
PH-SLE|Southern Leyte
PH-SLU|Sulu
PH-SOR|Sorsogon
PH-SUK|Sultan Kudarat
PH-SUN|Surigao del Norte
PH-SUR|Surigao del Sur
PH-TAR|Tarlac
PH-TAW|Tawi-Tawi
PH-U-A|
PH-WSA|Western Samar
PH-ZAN|Zamboanga del Norte
PH-ZAS|Zamboanga del Sur
PH-ZMB|Zambales
PH-ZSI|Zamboanga Sibiguey
PH-ABR|Abra
PH-AGN|Agusan del Norte
PH-AGS|Agusan del Sur
PH-AKL|Aklan
PH-ALB|Albay
PH-ANT|Antique
PH-APA|Apayao
PH-AUR|Aurora
PH-BAN|Batasn
PH-BAS|Basilan
PH-BEN|Benguet
PH-BIL|Biliran
PH-BOH|Bohol
PH-BTG|Batangas
PH-BTN|Batanes
PH-BUK|Bukidnon
PH-BUL|Bulacan
PH-CAG|Cagayan
PH-CAM|Camiguin
PH-CAN|Camarines Norte
PH-CAP|Capiz
PH-CAS|Camarines Sur
PH-CAT|Catanduanes
PH-CAV|Cavite
PH-CEB|Cebu
PH-COM|Compostela Valley
PH-DAO|Davao Oriental
PH-DAS|Davao del Sur
PH-DAV|Davao
PH-EAS|Eastern Samar
PH-GUI|Guimaras
PH-IFU|Ifugao
PH-ILI|Iloilo
PH-ILN|Ilocos Norte
PH-ILS|Ilocos Sur
PH-ISA|Isabela
PH-KAL|Kalinga-Apayso
PH-LAG|Laguna
PH-LAN|Lanao del Norte
PH-LAS|Lanao del Sur
PH-LEY|Leyte
PH-LUN|La Union
PH-MAD|Marinduque
PH-MAG|Maguindanao
PH-MAS|Masbate
PH-MDC|Mindoro Occidental
PH-MDR|Mindoro Oriental
PH-MOU|Mountain Province
PH-MSC|Misamis Occidental
PH-MSR|Misamis Oriental
PH-NCO|North Cotabato
PH-NEC|Negroe Occidental
PH-NER|Negros Oriental
PH-NSA|Northern Samar
PH-NUE|Nueva Ecija
PH-NUV|Nueva Vizcaya
PH-PAM|Pampanga
PH-PAN|Pangasinan
PH-PLW|Palawan
PH-QUE|Quezon
PH-QUI|Quirino
PH-RIZ|Rizal
PH-ROM|Romblon
PH-SAR|Sarangani
PH-SCO|South Cotabato
PH-SIG|Siquijor
PH-SLE|Southern Leyte
PH-SLU|Sulu
PH-SOR|Sorsogon
PH-SUK|Sultan Kudarat
PH-SUN|Surigao del Norte
PH-SUR|Surigao del Sur
PH-TAR|Tarlac
PH-TAW|Tawi-Tawi
PH-U-A|
PH-WSA|Western Samar
PH-ZAN|Zamboanga del Norte
PH-ZAS|Zamboanga del Sur
PH-ZMB|Zambales
PH-ZSI|Zamboanga Sibiguey
PK-BA|Balochistan
PK-IS|Islamabad Capital Territory
PK-JK|Azad Kashmir
PK-NA|Northern Areas
PK-NW|North-West Frontier
PK-PB|Punjab
PK-SD|Sindh
PK-TA|Federally Administered Tribal Areas
PK-U-A|
PK-BA|Balochistan
PK-IS|Islamabad Capital Territory
PK-JK|Azad Kashmir
PK-NA|Northern Areas
PK-NW|North-West Frontier
PK-PB|Punjab
PK-SD|Sindh
PK-TA|Federally Administered Tribal Areas
PK-U-A|
PL-DS|Lower Silesia
PL-KP|Kuyavia-Pomerania
PL-LB|Lubusz
PL-LD|Lodz
PL-LU|Lublin
PL-MA|Lesser Poland
PL-MZ|Masovia
PL-OP|Opole
PL-PD|Podlachia
PL-PK|Subcarpathia
PL-PM|Pomerania
PL-SK|Swietokrzyskie
PL-SL|Silesia
PL-U-A|
PL-WN|Warmia-Masuria
PL-WP|Greater Poland
PL-ZP|West Pomerania
PL-DS|Lower Silesia
PL-KP|Kuyavia-Pomerania
PL-LB|Lubusz
PL-LD|Lodz
PL-LU|Lublin
PL-MA|Lesser Poland
PL-MZ|Masovia
PL-OP|Opole
PL-PD|Podlachia
PL-PK|Subcarpathia
PL-PM|Pomerania
PL-SK|Swietokrzyskie
PL-SL|Silesia
PL-U-A|
PL-WN|Warmia-Masuria
PL-WP|Greater Poland
PL-ZP|West Pomerania
PM-ML|Miquelon-Longlade
PM-SP|Saint-Pierre
PM-U-A|
PM-ML|Miquelon-Longlade
PM-SP|Saint-Pierre
PM-U-A|
PN-U-A|
PN-U-A|
PR-U-A|
PR-U-A|
PS-U-A|
PS-U-A|
PT-01|Aveiro District
PT-02|Beja District
PT-03|Braga District
PT-04|Bragança District
PT-05|Castelo Branco District
PT-06|Coimbra District
PT-07|Évora District
PT-08|Faro District
PT-09|Guarda District
PT-10|Leiria District
PT-11|Lisbon District
PT-12|Portalegre District
PT-13|Oporto District
PT-14|Santarém District
PT-15|Setúbal District
PT-16|Viana do Castelo District
PT-17|Vila Real District
PT-18|Viseu District
PT-20|Autonomous Region of Azores
PT-30|Autonomous Region of Madeira
PT-U-A|
PT-01|Aveiro District
PT-02|Beja District
PT-03|Braga District
PT-04|Bragança District
PT-05|Castelo Branco District
PT-06|Coimbra District
PT-07|Évora District
PT-08|Faro District
PT-09|Guarda District
PT-10|Leiria District
PT-11|Lisbon District
PT-12|Portalegre District
PT-13|Oporto District
PT-14|Santarém District
PT-15|Setúbal District
PT-16|Viana do Castelo District
PT-17|Vila Real District
PT-18|Viseu District
PT-20|Autonomous Region of Azores
PT-30|Autonomous Region of Madeira
PT-U-A|
PW-002|Aimeliik
PW-004|Airai
PW-010|Angaur
PW-050|Hatobohei
PW-100|Kayangel
PW-150|Koror
PW-212|Melekeok
PW-214|Ngaraard
PW-218|Ngarchelong
PW-222|Ngardmau
PW-224|Ngatpang
PW-226|Ngchesar
PW-227|Ngeremlengui
PW-228|Ngiwal
PW-350|Peleliu
PW-370|Sonsorol
PW-U-A|
PW-002|Aimeliik
PW-004|Airai
PW-010|Angaur
PW-050|Hatobohei
PW-100|Kayangel
PW-150|Koror
PW-212|Melekeok
PW-214|Ngaraard
PW-218|Ngarchelong
PW-222|Ngardmau
PW-224|Ngatpang
PW-226|Ngchesar
PW-227|Ngeremlengui
PW-228|Ngiwal
PW-350|Peleliu
PW-370|Sonsorol
PW-U-A|
PY-1|Concepción Department
PY-10|Alto Paraná Department
PY-11|Central Department
PY-12|Ñeembucú Department
PY-13|Amambay Department
PY-14|Canindeyú Department
PY-15|Presidente Hayes Department
PY-16|Alto Paraguay Department
PY-19|Boquerón Department
PY-2|San Pedro Department
PY-3|Cordillera Department
PY-4|Guairá Department
PY-5|Caaguazú Department
PY-6|Caazapá Department
PY-7|Itapúa Department
PY-8|Misiones Department
PY-9|Paraguarí Department
PY-ASU|Asunción Capital District
PY-U-A|
PY-1|Concepción Department
PY-10|Alto Paraná Department
PY-11|Central Department
PY-12|Ñeembucú Department
PY-13|Amambay Department
PY-14|Canindeyú Department
PY-15|Presidente Hayes Department
PY-16|Alto Paraguay Department
PY-19|Boquerón Department
PY-2|San Pedro Department
PY-3|Cordillera Department
PY-4|Guairá Department
PY-5|Caaguazú Department
PY-6|Caazapá Department
PY-7|Itapúa Department
PY-8|Misiones Department
PY-9|Paraguarí Department
PY-ASU|Asunción Capital District
PY-U-A|
QA-DA|Ad Dawhah Municipality
QA-GH|Al Ghuwayriyah Municipality
QA-JB|Jariyan al Batnah Municipality
QA-JU|Al Jumayliyah Municipality
QA-KH|Al Khawr Municipality
QA-MS|Madinat ash Shamal Municipality
QA-RA|Ar Rayyan Municipality
QA-U-A|
QA-US|Umm Salal Municipality
QA-WA|Al Wakrah Municipality
QA-DA|Ad Dawhah Municipality
QA-GH|Al Ghuwayriyah Municipality
QA-JB|Jariyan al Batnah Municipality
QA-JU|Al Jumayliyah Municipality
QA-KH|Al Khawr Municipality
QA-MS|Madinat ash Shamal Municipality
QA-RA|Ar Rayyan Municipality
QA-U-A|
QA-US|Umm Salal Municipality
QA-WA|Al Wakrah Municipality
RE-U-A|
RE-U-A|
RO-AB|Alba
RO-AG|Arge?
RO-AR|Arad
RO-B|Bucure?ti
RO-BC|Bac?u
RO-BH|Bihor
RO-BN|Bistri?a-N?s?ud
RO-BR|Br?ila
RO-BT|Boto?ani
RO-BV|Bra?ov
RO-BZ|Buz?u
RO-CJ|Cluj
RO-CL|C?l?ra?i
RO-CS|Caras-Severin
RO-CT|Constan?a
RO-CV|Covasna
RO-DB|Dâmbovi?a
RO-DJ|Dolj
RO-GJ|Gorj
RO-GL|Gala?i
RO-GR|Giurgiu
RO-HD|Hunedoara
RO-HR|Harghita
RO-IF|Ilfov
RO-IL|Ialomi?a
RO-IS|Ia?i
RO-MH|Mehedin?i
RO-MM|Maramure?
RO-MS|Mure?
RO-NT|Neam?
RO-OT|Olt
RO-PH|Prahova
RO-SB|Sibiu
RO-SJ|S?laj
RO-SM|Satu Mare
RO-SV|Suceava
RO-TL|Tulcea
RO-TM|Timi?
RO-TR|Teleorman
RO-U-A|
RO-VL|Vâlcea
RO-VN|Vrancea
RO-VS|Vaslui
RO-AB|Alba
RO-AG|Arge?
RO-AR|Arad
RO-B|Bucure?ti
RO-BC|Bac?u
RO-BH|Bihor
RO-BN|Bistri?a-N?s?ud
RO-BR|Br?ila
RO-BT|Boto?ani
RO-BV|Bra?ov
RO-BZ|Buz?u
RO-CJ|Cluj
RO-CL|C?l?ra?i
RO-CS|Caras-Severin
RO-CT|Constan?a
RO-CV|Covasna
RO-DB|Dâmbovi?a
RO-DJ|Dolj
RO-GJ|Gorj
RO-GL|Gala?i
RO-GR|Giurgiu
RO-HD|Hunedoara
RO-HR|Harghita
RO-IF|Ilfov
RO-IL|Ialomi?a
RO-IS|Ia?i
RO-MH|Mehedin?i
RO-MM|Maramure?
RO-MS|Mure?
RO-NT|Neam?
RO-OT|Olt
RO-PH|Prahova
RO-SB|Sibiu
RO-SJ|S?laj
RO-SM|Satu Mare
RO-SV|Suceava
RO-TL|Tulcea
RO-TM|Timi?
RO-TR|Teleorman
RO-U-A|
RO-VL|Vâlcea
RO-VN|Vrancea
RO-VS|Vaslui
RS-00|Beograd (city)
RS-01|Northern Ba?ka
RS-02|Central Banat
RS-03|North Banat
RS-04|South Banat
RS-05|West Ba?ka
RS-06|South Ba?ka
RS-07|Srem
RS-08|Ma?va
RS-09|Kolubara
RS-10|Podunavlje
RS-11|Brani?evo
RS-12|Šumadija
RS-13|Pomoravlje
RS-14|Bor
RS-15|Zaje?ar
RS-16|Zlatibor
RS-17|Moravica
RS-18|Raška
RS-19|Rasina
RS-20|Nišava
RS-21|Toplica
RS-22|Pirot
RS-23|Jablanica
RS-24|P?inja
RS-25|Kosovo
RS-26|Pe?
RS-27|Prizren
RS-28|Kosovska Mitrovica
RS-29|Kosovo-Pomoravlje
RS-U-A|
RS-00|Beograd (city)
RS-01|Northern Ba?ka
RS-02|Central Banat
RS-03|North Banat
RS-04|South Banat
RS-05|West Ba?ka
RS-06|South Ba?ka
RS-07|Srem
RS-08|Ma?va
RS-09|Kolubara
RS-10|Podunavlje
RS-11|Brani?evo
RS-12|Šumadija
RS-13|Pomoravlje
RS-14|Bor
RS-15|Zaje?ar
RS-16|Zlatibor
RS-17|Moravica
RS-18|Raška
RS-19|Rasina
RS-20|Nišava
RS-21|Toplica
RS-22|Pirot
RS-23|Jablanica
RS-24|P?inja
RS-25|Kosovo
RS-26|Pe?
RS-27|Prizren
RS-28|Kosovska Mitrovica
RS-29|Kosovo-Pomoravlje
RS-U-A|
RU-AD|Republic of Adygea
RU-AL|Altai Republic
RU-ALT|Altai Krai
RU-AMU|Amur Oblast
RU-ARK|Arkhangelsk Oblast
RU-AST|Astrakhan Oblast
RU-BA|Republic of Bashkortostan
RU-BEL|Belgorod Oblast
RU-BRY|Bryansk Oblast
RU-BU|Republic of Buryat
RU-CE|Chechen Republic
RU-CHE|Chelyabinsk Oblast
RU-CHI|Zabaykalsky Krai
RU-CHU|Chukotka Autonomous Okrug
RU-CU|Chuvash Republic
RU-DA|Republic of Dagestan
RU-IN|Republic of Ingushetia
RU-IRK|Irkutsk Oblast
RU-IVA|Ivanovo Oblast
RU-KAM|Kamchatka Krai
RU-KB|Kabardino-Balkar Republic
RU-KC|Karachay-Cherkess Republic
RU-KDA|Krasnodar Krai
RU-KEM|Kemerovo Oblast
RU-KGD|Kaliningrad Oblast
RU-KGN|Kurgan Oblast
RU-KHA|Khabarovsk Krai
RU-KHM|Khanty-Mansi Autonomous Okrug
RU-KIR|Kirov Oblast
RU-KK|Republic of Khakassia
RU-KL|Republic of Kalmykia
RU-KLU|Kaluga Oblast
RU-KO|Komi Republic
RU-KOS|Kostroma Oblast
RU-KR|Republic of Karelia
RU-KRS|Kursk Oblast
RU-KYA|Krasnoyarsk Krai
RU-LEN|Leningrad Oblast
RU-LIP|Lipetsk Oblast
RU-MAG|Magadan Oblast
RU-ME|Mari El Republic
RU-MO|Republic of Mordovia
RU-MOS|Moscow Oblast
RU-MOW|Moscow (city)
RU-MUR|Murmansk Oblast
RU-NEN|Nenets Autonomous Okrug
RU-NGR|Novgorod Oblast
RU-NIZ|Nizhny Novgorod Oblast
RU-NVS|Novosibirsk Oblast
RU-OMS|Omsk Oblast
RU-ORE|Orenburg Oblast
RU-ORL|Oryol Oblast
RU-PER|Perm Krai
RU-PNZ|Penza Oblast
RU-PRI|Primorsky Krai
RU-PSK|Pskov Oblast
RU-ROS|Rostov Oblast
RU-RYA|Ryazan Oblast
RU-SA|Sakha (Yakutia) Republic
RU-SAK|Sakhalin Oblast
RU-SAM|Samara Oblast
RU-SAR|Saratov Oblast
RU-SE|Republic of North Ossetia-Alania
RU-SMO|Smolensk Oblast
RU-SPE|Saint Petersburg (city)
RU-STA|Stavropol Krai
RU-SVE|Sverdlovsk Oblast
RU-TA|Republic of Tatarstan
RU-TAM|Tambov Oblast
RU-TOM|Tomsk Oblast
RU-TUL|Tula Oblast
RU-TVE|Tver Oblast
RU-TY|Tuva Republic
RU-TYU|Tyumen Oblast
RU-U-A|
RU-UD|Udmurt Republic
RU-ULY|Ulyanovsk Oblast
RU-UOB|Ust-Orda Buryat Autonomous Okrug
RU-VGG|Volgograd Oblast
RU-VLA|Vladimir Oblast
RU-VLG|Vologda Oblast
RU-VOR|Voronezh Oblast
RU-YAN|Yamalo-Nenets Autonomous Okrug
RU-YAR|Yaroslavl Oblast
RU-YEV|Jewish Autonomous Oblast
RU-AD|Republic of Adygea
RU-AL|Altai Republic
RU-ALT|Altai Krai
RU-AMU|Amur Oblast
RU-ARK|Arkhangelsk Oblast
RU-AST|Astrakhan Oblast
RU-BA|Republic of Bashkortostan
RU-BEL|Belgorod Oblast
RU-BRY|Bryansk Oblast
RU-BU|Republic of Buryat
RU-CE|Chechen Republic
RU-CHE|Chelyabinsk Oblast
RU-CHI|Zabaykalsky Krai
RU-CHU|Chukotka Autonomous Okrug
RU-CU|Chuvash Republic
RU-DA|Republic of Dagestan
RU-IN|Republic of Ingushetia
RU-IRK|Irkutsk Oblast
RU-IVA|Ivanovo Oblast
RU-KAM|Kamchatka Krai
RU-KB|Kabardino-Balkar Republic
RU-KC|Karachay-Cherkess Republic
RU-KDA|Krasnodar Krai
RU-KEM|Kemerovo Oblast
RU-KGD|Kaliningrad Oblast
RU-KGN|Kurgan Oblast
RU-KHA|Khabarovsk Krai
RU-KHM|Khanty-Mansi Autonomous Okrug
RU-KIR|Kirov Oblast
RU-KK|Republic of Khakassia
RU-KL|Republic of Kalmykia
RU-KLU|Kaluga Oblast
RU-KO|Komi Republic
RU-KOS|Kostroma Oblast
RU-KR|Republic of Karelia
RU-KRS|Kursk Oblast
RU-KYA|Krasnoyarsk Krai
RU-LEN|Leningrad Oblast
RU-LIP|Lipetsk Oblast
RU-MAG|Magadan Oblast
RU-ME|Mari El Republic
RU-MO|Republic of Mordovia
RU-MOS|Moscow Oblast
RU-MOW|Moscow (city)
RU-MUR|Murmansk Oblast
RU-NEN|Nenets Autonomous Okrug
RU-NGR|Novgorod Oblast
RU-NIZ|Nizhny Novgorod Oblast
RU-NVS|Novosibirsk Oblast
RU-OMS|Omsk Oblast
RU-ORE|Orenburg Oblast
RU-ORL|Oryol Oblast
RU-PER|Perm Krai
RU-PNZ|Penza Oblast
RU-PRI|Primorsky Krai
RU-PSK|Pskov Oblast
RU-ROS|Rostov Oblast
RU-RYA|Ryazan Oblast
RU-SA|Sakha (Yakutia) Republic
RU-SAK|Sakhalin Oblast
RU-SAM|Samara Oblast
RU-SAR|Saratov Oblast
RU-SE|Republic of North Ossetia-Alania
RU-SMO|Smolensk Oblast
RU-SPE|Saint Petersburg (city)
RU-STA|Stavropol Krai
RU-SVE|Sverdlovsk Oblast
RU-TA|Republic of Tatarstan
RU-TAM|Tambov Oblast
RU-TOM|Tomsk Oblast
RU-TUL|Tula Oblast
RU-TVE|Tver Oblast
RU-TY|Tuva Republic
RU-TYU|Tyumen Oblast
RU-U-A|
RU-UD|Udmurt Republic
RU-ULY|Ulyanovsk Oblast
RU-UOB|Ust-Orda Buryat Autonomous Okrug
RU-VGG|Volgograd Oblast
RU-VLA|Vladimir Oblast
RU-VLG|Vologda Oblast
RU-VOR|Voronezh Oblast
RU-YAN|Yamalo-Nenets Autonomous Okrug
RU-YAR|Yaroslavl Oblast
RU-YEV|Jewish Autonomous Oblast
RW-01|Ville de Kigali
RW-02|East
RW-03|North
RW-04|West
RW-05|South
RW-B|Gitarama
RW-C|Butare
RW-D|Gikongoro
RW-E|Cyangugu
RW-F|Kibuye
RW-G|Gisenyi
RW-H|Ruhengeri
RW-I|Byumba
RW-J|Kibungo
RW-K|Kigali-Rural Kigali y' Icyaro
RW-L|Kigali-Ville Kigali Ngari
RW-M|Mutara
RW-U-A|
RW-01|Ville de Kigali
RW-02|East
RW-03|North
RW-04|West
RW-05|South
RW-B|Gitarama
RW-C|Butare
RW-D|Gikongoro
RW-E|Cyangugu
RW-F|Kibuye
RW-G|Gisenyi
RW-H|Ruhengeri
RW-I|Byumba
RW-J|Kibungo
RW-K|Kigali-Rural Kigali y' Icyaro
RW-L|Kigali-Ville Kigali Ngari
RW-M|Mutara
RW-U-A|
SA-01|Riyadh
SA-02|Makkah
SA-03|Al Madinah
SA-04|Ash Sharqiyah
SA-05|Al Qasim
SA-06|Ha'il
SA-07|Tabuk
SA-08|The Northern Border
SA-09|Jlzan
SA-10|Najran
SA-11|Al Batah
SA-12|Al Jawf
SA-14|Asir
SA-U-A|
SA-01|Riyadh
SA-02|Makkah
SA-03|Al Madinah
SA-04|Ash Sharqiyah
SA-05|Al Qasim
SA-06|Ha'il
SA-07|Tabuk
SA-08|The Northern Border
SA-09|Jlzan
SA-10|Najran
SA-11|Al Batah
SA-12|Al Jawf
SA-14|Asir
SA-U-A|
SB-CE|Central
SB-CH|Choiseul
SB-CT|Capital Territory (Honiara)
SB-GU|Guadalcanal
SB-IS|Isabel
SB-MK|Makira
SB-ML|Malaita
SB-RB|Rennell and Bellona
SB-TE|Temotu
SB-U-A|
SB-WE|Western
SB-CE|Central
SB-CH|Choiseul
SB-CT|Capital Territory (Honiara)
SB-GU|Guadalcanal
SB-IS|Isabel
SB-MK|Makira
SB-ML|Malaita
SB-RB|Rennell and Bellona
SB-TE|Temotu
SB-U-A|
SB-WE|Western
SC-01|Anse aux Pins
SC-02|Anse Boileau
SC-03|Anse Étoile
SC-04|Anse Louis
SC-05|Anse Royale
SC-06|Baie Lazare
SC-07|Baie Sainte Anne
SC-08|Beau Vallon
SC-09|Bel Air
SC-10|Bel Ombre
SC-11|Cascade
SC-12|Glacis
SC-13|Grand' Anse (Mahé)
SC-14|Grand' Anse (Praslin)
SC-15|La Digue
SC-16|La Rivière Anglaise
SC-17|Mont Buxton
SC-18|Mont Fleuri
SC-19|Plaisance
SC-20|Pointe La Rue
SC-21|Port Glaud
SC-22|Saint Louis
SC-23|Takamaka
SC-U-A|
SC-01|Anse aux Pins
SC-02|Anse Boileau
SC-03|Anse Étoile
SC-04|Anse Louis
SC-05|Anse Royale
SC-06|Baie Lazare
SC-07|Baie Sainte Anne
SC-08|Beau Vallon
SC-09|Bel Air
SC-10|Bel Ombre
SC-11|Cascade
SC-12|Glacis
SC-13|Grand' Anse (Mahé)
SC-14|Grand' Anse (Praslin)
SC-15|La Digue
SC-16|La Rivière Anglaise
SC-17|Mont Buxton
SC-18|Mont Fleuri
SC-19|Plaisance
SC-20|Pointe La Rue
SC-21|Port Glaud
SC-22|Saint Louis
SC-23|Takamaka
SC-U-A|
SD-01|Northern
SD-02|North Darfur
SD-03|Khartoum State
SD-04|River Nile
SD-05|Kassala State
SD-06|Al Qadarif
SD-07|Al Jazirah
SD-08|White Nile
SD-09|North Kurdufan
SD-10|Western Kurdufan
SD-11|South Darfur
SD-12|West Darfur
SD-13|South Kurdufan
SD-24|Blue Nile
SD-25|Sennar
SD-26|Red Sea
SD-U-A|
SD-01|Northern
SD-02|North Darfur
SD-03|Khartoum State
SD-04|River Nile
SD-05|Kassala State
SD-06|Al Qadarif
SD-07|Al Jazirah
SD-08|White Nile
SD-09|North Kurdufan
SD-10|Western Kurdufan
SD-11|South Darfur
SD-12|West Darfur
SD-13|South Kurdufan
SD-24|Blue Nile
SD-25|Sennar
SD-26|Red Sea
SD-U-A|
SE-AB|Stockholms län
SE-AC|Västerbottens län
SE-BD|Norrbottena län
SE-C|Uppsala län
SE-D|Södermanlands län
SE-E|Östergötlands län
SE-F|Jönköpings län
SE-G|Kronoberge län
SE-H|Kalmar län
SE-I|Gotlands län
SE-K|Blekinge län
SE-M|Skåne län
SE-N|Hallands län
SE-Q|Västra Götalands län
SE-S|Värmlanda län
SE-T|Örebro län
SE-U|Västmanlanda län
SE-U-A|
SE-W|Dalarnas län
SE-X|Gävleborge län
SE-Y|Västernorrlands län
SE-Z|Jämtlande län
SE-AB|Stockholms län
SE-AC|Västerbottens län
SE-BD|Norrbottena län
SE-C|Uppsala län
SE-D|Södermanlands län
SE-E|Östergötlands län
SE-F|Jönköpings län
SE-G|Kronoberge län
SE-H|Kalmar län
SE-I|Gotlands län
SE-K|Blekinge län
SE-M|Skåne län
SE-N|Hallands län
SE-Q|Västra Götalands län
SE-S|Värmlanda län
SE-T|Örebro län
SE-U|Västmanlanda län
SE-U-A|
SE-W|Dalarnas län
SE-X|Gävleborge län
SE-Y|Västernorrlands län
SE-Z|Jämtlande län
SG-01|Central Singapore
SG-02|North East
SG-03|North West
SG-04|South East
SG-05|South West
SG-U-A|
SG-01|Central Singapore
SG-02|North East
SG-03|North West
SG-04|South East
SG-05|South West
SG-U-A|
SH-AC|Ascension
SH-SH|Saint Helena
SH-TA|Tristan da Cunha
SH-U-A|
SH-AC|Ascension
SH-SH|Saint Helena
SH-TA|Tristan da Cunha
SH-U-A|
SI-001|Ajdovscina
SI-002|Beltinci
SI-003|Bled
SI-004|Bohinj
SI-005|Borovnica
SI-006|Bovec
SI-007|Brda
SI-008|Brezovica
SI-009|Brezica
SI-010|Tisina
SI-011|Celje
SI-012|Cerklje na Gorenjskem
SI-013|Cerknica
SI-014|Cerkno
SI-015|Crensovci
SI-016|Crna na Koroskem
SI-017|Crnomelj
SI-018|Destrnik
SI-019|Divaca
SI-020|Dobrepolje
SI-021|Dobrova-Polhov Gradec
SI-022|Dol pri Ljubljani
SI-023|Domzale
SI-024|Dornava
SI-025|Dravograd
SI-026|Duplek
SI-027|Gorenja vas-Poljane
SI-028|Gorsnica
SI-029|Gornja Radgona
SI-030|Gornji Grad
SI-031|Gornji Petrovci
SI-032|Grosuplje
SI-033|Salovci
SI-034|Hrastnik
SI-035|Hrpelje-Kozina
SI-036|Idrija
SI-037|Ig
SI-038|IIrska Bistrica
SI-039|Ivancna Gorica
SI-040|Izola
SI-041|Jesenice
SI-042|Jursinci
SI-043|Kamnik
SI-044|Kanal
SI-045|Kidricevo
SI-046|Kobarid
SI-047|Kobilje
SI-048|Jovevje
SI-049|Komen
SI-050|Koper
SI-051|Kozje
SI-052|Kranj
SI-053|Kranjska Gora
SI-054|Krsko
SI-055|Kungota
SI-056|Kuzma
SI-057|Lasko
SI-058|Lenart
SI-059|Lendava
SI-060|Litija
SI-061|Ljubljana
SI-062|Ljubno
SI-063|Ljutomer
SI-064|Logatec
SI-065|Loska dolina
SI-066|Loski Potok
SI-067|Luce
SI-068|Lukovica
SI-069|Majsperk
SI-070|Maribor
SI-071|Medvode
SI-072|Menges
SI-073|Metlika
SI-074|Mezica
SI-075|Miren-Kostanjevica
SI-076|Mislinja
SI-077|Moravce
SI-078|Moravske Toplice
SI-079|Mozirje
SI-080|Murska Sobota
SI-081|Muta
SI-082|Naklo
SI-083|Nazarje
SI-084|Nova Gorica
SI-085|Nova mesto
SI-086|Odranci
SI-087|Ormož
SI-088|Osilnica
SI-089|Pesnica
SI-090|Piran
SI-091|Pivka
SI-092|Pod?etrtek
SI-093|Podvelka
SI-094|Postojna
SI-095|Preddvor
SI-096|Ptuj
SI-097|Puconci
SI-098|Ra?e-Fram
SI-099|Rade?e
SI-100|Radenci
SI-101|Radlje ob Dravi
SI-102|Radovljica
SI-103|Ravne na Koroškem
SI-104|Ribnica
SI-105|Rogašovci
SI-106|Rogaška Slatina
SI-107|Rogatec
SI-108|Ruše
SI-109|Semi?
SI-110|Sevnica
SI-111|Sežana
SI-112|Slovenj Gradec
SI-113|Slovenska Bistrica
SI-114|Slovenske Konjice
SI-115|Starše
SI-116|Sveti Jurij
SI-117|Sencur
SI-118|Sentilj
SI-119|Sentjernej
SI-120|Sentjur pri Celju
SI-121|Skocjan
SI-122|Skofja Loka
SI-123|Skoftjica
SI-124|Smarje pri Jelsah
SI-125|Smartno ob Paki
SI-126|Sostanj
SI-127|Store
SI-128|Tolmin
SI-129|Trbovje
SI-130|Trebnje
SI-131|Trzic
SI-132|Turnisce
SI-133|Velenje
SI-134|Velika Lasce
SI-135|Videm
SI-136|Vipava
SI-137|Vitanje
SI-138|Vojnik
SI-139|Vojnik
SI-140|Vrhnika
SI-141|Vuzenica
SI-142|Zagorje ob Savi
SI-143|Zavrc
SI-144|Zrece
SI-146|Zelezniki
SI-147|Ziri
SI-148|Benedikt
SI-149|Bistrica ob Sotli
SI-150|Bloke
SI-151|Braslovce
SI-152|Cankova
SI-153|Cerkvenjak
SI-154|Dobje
SI-155|Dobrna
SI-156|Dobrovnik
SI-157|Dolenjske Toplice
SI-158|Grad
SI-159|Hajdina
SI-160|Hoce-Slivnica
SI-161|Hodos
SI-162|Jorjul
SI-163|Jezersko
SI-164|Komenda
SI-165|Kostel
SI-166|Krizevci
SI-167|Lovrenc na Pohorju
SI-168|Markovci
SI-169|Miklavz na Dravskern polju
SI-170|Mirna Pec
SI-171|Oplotnica
SI-172|Podlehnik
SI-173|Polzela
SI-174|Prebold
SI-175|Prevalje
SI-176|Razkrižje
SI-177|Ribnica na Pohorju
SI-178|Selnica ob Dravi
SI-179|Sodražica
SI-180|Sol?ava
SI-181|Sveta Ana
SI-182|Sveti Andraz v Slovenskih goricah
SI-183|Sempeter-Vrtojba
SI-184|Tabor
SI-185|Trnovska vas
SI-186|Trzin
SI-187|Velika Polana
SI-188|Verzej
SI-189|Vransko
SI-190|Zalec
SI-191|Zetale
SI-192|Zirovnica
SI-193|Zuzemberk
SI-194|Smartno pri Litiji
SI-U-A|
SI-001|Ajdovscina
SI-002|Beltinci
SI-003|Bled
SI-004|Bohinj
SI-005|Borovnica
SI-006|Bovec
SI-007|Brda
SI-008|Brezovica
SI-009|Brezica
SI-010|Tisina
SI-011|Celje
SI-012|Cerklje na Gorenjskem
SI-013|Cerknica
SI-014|Cerkno
SI-015|Crensovci
SI-016|Crna na Koroskem
SI-017|Crnomelj
SI-018|Destrnik
SI-019|Divaca
SI-020|Dobrepolje
SI-021|Dobrova-Polhov Gradec
SI-022|Dol pri Ljubljani
SI-023|Domzale
SI-024|Dornava
SI-025|Dravograd
SI-026|Duplek
SI-027|Gorenja vas-Poljane
SI-028|Gorsnica
SI-029|Gornja Radgona
SI-030|Gornji Grad
SI-031|Gornji Petrovci
SI-032|Grosuplje
SI-033|Salovci
SI-034|Hrastnik
SI-035|Hrpelje-Kozina
SI-036|Idrija
SI-037|Ig
SI-038|IIrska Bistrica
SI-039|Ivancna Gorica
SI-040|Izola
SI-041|Jesenice
SI-042|Jursinci
SI-043|Kamnik
SI-044|Kanal
SI-045|Kidricevo
SI-046|Kobarid
SI-047|Kobilje
SI-048|Jovevje
SI-049|Komen
SI-050|Koper
SI-051|Kozje
SI-052|Kranj
SI-053|Kranjska Gora
SI-054|Krsko
SI-055|Kungota
SI-056|Kuzma
SI-057|Lasko
SI-058|Lenart
SI-059|Lendava
SI-060|Litija
SI-061|Ljubljana
SI-062|Ljubno
SI-063|Ljutomer
SI-064|Logatec
SI-065|Loska dolina
SI-066|Loski Potok
SI-067|Luce
SI-068|Lukovica
SI-069|Majsperk
SI-070|Maribor
SI-071|Medvode
SI-072|Menges
SI-073|Metlika
SI-074|Mezica
SI-075|Miren-Kostanjevica
SI-076|Mislinja
SI-077|Moravce
SI-078|Moravske Toplice
SI-079|Mozirje
SI-080|Murska Sobota
SI-081|Muta
SI-082|Naklo
SI-083|Nazarje
SI-084|Nova Gorica
SI-085|Nova mesto
SI-086|Odranci
SI-087|Ormož
SI-088|Osilnica
SI-089|Pesnica
SI-090|Piran
SI-091|Pivka
SI-092|Pod?etrtek
SI-093|Podvelka
SI-094|Postojna
SI-095|Preddvor
SI-096|Ptuj
SI-097|Puconci
SI-098|Ra?e-Fram
SI-099|Rade?e
SI-100|Radenci
SI-101|Radlje ob Dravi
SI-102|Radovljica
SI-103|Ravne na Koroškem
SI-104|Ribnica
SI-105|Rogašovci
SI-106|Rogaška Slatina
SI-107|Rogatec
SI-108|Ruše
SI-109|Semi?
SI-110|Sevnica
SI-111|Sežana
SI-112|Slovenj Gradec
SI-113|Slovenska Bistrica
SI-114|Slovenske Konjice
SI-115|Starše
SI-116|Sveti Jurij
SI-117|Sencur
SI-118|Sentilj
SI-119|Sentjernej
SI-120|Sentjur pri Celju
SI-121|Skocjan
SI-122|Skofja Loka
SI-123|Skoftjica
SI-124|Smarje pri Jelsah
SI-125|Smartno ob Paki
SI-126|Sostanj
SI-127|Store
SI-128|Tolmin
SI-129|Trbovje
SI-130|Trebnje
SI-131|Trzic
SI-132|Turnisce
SI-133|Velenje
SI-134|Velika Lasce
SI-135|Videm
SI-136|Vipava
SI-137|Vitanje
SI-138|Vojnik
SI-139|Vojnik
SI-140|Vrhnika
SI-141|Vuzenica
SI-142|Zagorje ob Savi
SI-143|Zavrc
SI-144|Zrece
SI-146|Zelezniki
SI-147|Ziri
SI-148|Benedikt
SI-149|Bistrica ob Sotli
SI-150|Bloke
SI-151|Braslovce
SI-152|Cankova
SI-153|Cerkvenjak
SI-154|Dobje
SI-155|Dobrna
SI-156|Dobrovnik
SI-157|Dolenjske Toplice
SI-158|Grad
SI-159|Hajdina
SI-160|Hoce-Slivnica
SI-161|Hodos
SI-162|Jorjul
SI-163|Jezersko
SI-164|Komenda
SI-165|Kostel
SI-166|Krizevci
SI-167|Lovrenc na Pohorju
SI-168|Markovci
SI-169|Miklavz na Dravskern polju
SI-170|Mirna Pec
SI-171|Oplotnica
SI-172|Podlehnik
SI-173|Polzela
SI-174|Prebold
SI-175|Prevalje
SI-176|Razkrižje
SI-177|Ribnica na Pohorju
SI-178|Selnica ob Dravi
SI-179|Sodražica
SI-180|Sol?ava
SI-181|Sveta Ana
SI-182|Sveti Andraz v Slovenskih goricah
SI-183|Sempeter-Vrtojba
SI-184|Tabor
SI-185|Trnovska vas
SI-186|Trzin
SI-187|Velika Polana
SI-188|Verzej
SI-189|Vransko
SI-190|Zalec
SI-191|Zetale
SI-192|Zirovnica
SI-193|Zuzemberk
SI-194|Smartno pri Litiji
SI-U-A|
SK-BC|Banská Bystrica
SK-BL|Bratislava
SK-KI|Košice
SK-NJ|Nitra
SK-PV|Prešov
SK-TA|Trnava
SK-TC|Tren?ín
SK-U-A|
SK-ZI|Žilina
SK-BC|Banská Bystrica
SK-BL|Bratislava
SK-KI|Košice
SK-NJ|Nitra
SK-PV|Prešov
SK-TA|Trnava
SK-TC|Tren?ín
SK-U-A|
SK-ZI|Žilina
SL-E|Eastern Province
SL-N|Northern Province
SL-S|Southern Province
SL-U-A|
SL-W|Western Area
SL-E|Eastern Province
SL-N|Northern Province
SL-S|Southern Province
SL-U-A|
SL-W|Western Area
SM-01|Acquaviva
SM-02|Chiesanuova
SM-03|Domagnano
SM-04|Faetano
SM-05|Fiorentino
SM-06|Borgo Maggiore
SM-07|San Marino
SM-08|Montegiardino
SM-09|Serravalle
SM-U-A|
SM-01|Acquaviva
SM-02|Chiesanuova
SM-03|Domagnano
SM-04|Faetano
SM-05|Fiorentino
SM-06|Borgo Maggiore
SM-07|San Marino
SM-08|Montegiardino
SM-09|Serravalle
SM-U-A|
SN-DB|Diourbel
SN-DK|Dakar
SN-FK|Fatick
SN-KD|Kolda
SN-KL|Kaolack
SN-LG|Louga
SN-MT|Matam
SN-SL|Saint-Louis
SN-TC|Tambacounda
SN-TH|Thies
SN-U-A|
SN-ZG|Ziguinchor
SN-DB|Diourbel
SN-DK|Dakar
SN-FK|Fatick
SN-KD|Kolda
SN-KL|Kaolack
SN-LG|Louga
SN-MT|Matam
SN-SL|Saint-Louis
SN-TC|Tambacounda
SN-TH|Thies
SN-U-A|
SN-ZG|Ziguinchor
SO-AW|Awdal
SO-BK|Bakool
SO-BN|Banaadir
SO-BR|Bari
SO-BY|Bay
SO-GA|Galguduud
SO-GE|Gedo
SO-HI|Hiirsan
SO-JD|Jubbada Dhexe
SO-JH|Jubbada Hoose
SO-MU|Mudug
SO-NU|Nugaal
SO-SA|Saneag
SO-SD|Shabeellaha Dhexe
SO-SH|Shabeellaha Hoose
SO-SO|Sool
SO-TO|Togdheer
SO-U-A|
SO-WO|Woqooyi Galbeed
SO-AW|Awdal
SO-BK|Bakool
SO-BN|Banaadir
SO-BR|Bari
SO-BY|Bay
SO-GA|Galguduud
SO-GE|Gedo
SO-HI|Hiirsan
SO-JD|Jubbada Dhexe
SO-JH|Jubbada Hoose
SO-MU|Mudug
SO-NU|Nugaal
SO-SA|Saneag
SO-SD|Shabeellaha Dhexe
SO-SH|Shabeellaha Hoose
SO-SO|Sool
SO-TO|Togdheer
SO-U-A|
SO-WO|Woqooyi Galbeed
SR-BR|Brokopondo
SR-CM|Commewijne
SR-CR|Coronie
SR-MA|Marowijne
SR-NI|Nickerie
SR-PM|Paramaribo
SR-PR|Para
SR-SA|Saramacca
SR-SI|Sipaliwini
SR-U-A|
SR-WA|Wanica
SR-BR|Brokopondo
SR-CM|Commewijne
SR-CR|Coronie
SR-MA|Marowijne
SR-NI|Nickerie
SR-PM|Paramaribo
SR-PR|Para
SR-SA|Saramacca
SR-SI|Sipaliwini
SR-U-A|
SR-WA|Wanica
SS-14|Western Bahr el Ghazal
SS-15|Northern Bahr el Ghazal
SS-16|Western Equatoria
SS-17|Central Equatoria
SS-18|Lakes
SS-19|Eastern Equatoria
SS-20|Jonglei
SS-21|Warrap
SS-22|Unity
SS-23|Upper Nile
SS-U-A|
SS-14|Western Bahr el Ghazal
SS-15|Northern Bahr el Ghazal
SS-16|Western Equatoria
SS-17|Central Equatoria
SS-18|Lakes
SS-19|Eastern Equatoria
SS-20|Jonglei
SS-21|Warrap
SS-22|Unity
SS-23|Upper Nile
SS-U-A|
ST-P|Principe
ST-S|São Tomé
ST-U-A|
ST-P|Principe
ST-S|São Tomé
ST-U-A|
SV-AH|Ahuachapan
SV-CA|Cabanas
SV-CH|Chalatenango
SV-CU|Cuscatlan
SV-LI|La Libertad
SV-MO|Morazan
SV-PA|La Paz
SV-SA|Santa Ana
SV-SM|San Miguel
SV-SO|Sonsonate
SV-SS|San Salvador
SV-SV|San Vicente
SV-U-A|
SV-UN|La Unión
SV-US|Usulutan
SV-AH|Ahuachapan
SV-CA|Cabanas
SV-CH|Chalatenango
SV-CU|Cuscatlan
SV-LI|La Libertad
SV-MO|Morazan
SV-PA|La Paz
SV-SA|Santa Ana
SV-SM|San Miguel
SV-SO|Sonsonate
SV-SS|San Salvador
SV-SV|San Vicente
SV-U-A|
SV-UN|La Unión
SV-US|Usulutan
SY-DI|Damascus Governorate
SY-DR|Daraa Governorate
SY-DY|Deir ez-Zor Governorate
SY-HA|Al-Hasakah Governorate
SY-HI|Homs Governorate
SY-HL|Aleppo Governorate
SY-HM|Hama Governorate
SY-ID|Idlib Governorate
SY-LA|Latakia Governorate
SY-QU|Quneitra Governorate
SY-RA|Ar-Raqqah Governorate
SY-RD|Rif Dimashq Governorate
SY-SU|As-Suwayda Governorate
SY-TA|Tartus Governorate
SY-U-A|
SY-DI|Damascus Governorate
SY-DR|Daraa Governorate
SY-DY|Deir ez-Zor Governorate
SY-HA|Al-Hasakah Governorate
SY-HI|Homs Governorate
SY-HL|Aleppo Governorate
SY-HM|Hama Governorate
SY-ID|Idlib Governorate
SY-LA|Latakia Governorate
SY-QU|Quneitra Governorate
SY-RA|Ar-Raqqah Governorate
SY-RD|Rif Dimashq Governorate
SY-SU|As-Suwayda Governorate
SY-TA|Tartus Governorate
SY-U-A|
SZ-HH|Hhohho
SZ-LU|Lubombo
SZ-MA|Manzini
SZ-SH|Shiselweni
SZ-U-A|
SZ-HH|Hhohho
SZ-LU|Lubombo
SZ-MA|Manzini
SZ-SH|Shiselweni
SZ-U-A|
TC-AC|Ambergris Cays
TC-DC|Dellis Cay
TC-EC|East Caicos
TC-FC|French Cay
TC-GT|Grand Turk
TC-LW|Little Water Cay
TC-MC|Middle Caicos
TC-NC|North Caicos
TC-PN|Pine Cay
TC-PR|Providenciales
TC-RC|Parrot Cay
TC-SC|South Caicos
TC-SL|Salt Cay
TC-U-A|
TC-WC|West Caicos
TC-AC|Ambergris Cays
TC-DC|Dellis Cay
TC-EC|East Caicos
TC-FC|French Cay
TC-GT|Grand Turk
TC-LW|Little Water Cay
TC-MC|Middle Caicos
TC-NC|North Caicos
TC-PN|Pine Cay
TC-PR|Providenciales
TC-RC|Parrot Cay
TC-SC|South Caicos
TC-SL|Salt Cay
TC-U-A|
TC-WC|West Caicos
TD-BA|Batha
TD-BET|Borkou-Ennedi-Tibesti
TD-BI|Biltine
TD-CB|Chari-Baguirmi
TD-GR|Guera
TD-KA|Kanem
TD-LC|Lac
TD-LO|Logone-Occidental
TD-LR|Logone-Oriental
TD-MC|Moyen-Chari
TD-MK|Mayo-Kebbi
TD-OD|Ouaddai
TD-SA|Salamat
TD-TA|Tandjile
TD-U-A|
TD-BA|Batha
TD-BET|Borkou-Ennedi-Tibesti
TD-BI|Biltine
TD-CB|Chari-Baguirmi
TD-GR|Guera
TD-KA|Kanem
TD-LC|Lac
TD-LO|Logone-Occidental
TD-LR|Logone-Oriental
TD-MC|Moyen-Chari
TD-MK|Mayo-Kebbi
TD-OD|Ouaddai
TD-SA|Salamat
TD-TA|Tandjile
TD-U-A|
TF-U-A|
TF-U-A|
TG-C|Centrale Region
TG-K|Kara Region
TG-M|Maritime Region
TG-P|Plateaux Region
TG-S|Savanes Region
TG-U-A|
TG-C|Centrale Region
TG-K|Kara Region
TG-M|Maritime Region
TG-P|Plateaux Region
TG-S|Savanes Region
TG-U-A|
TH-10|Bangkok Province
TH-11|Samut Prakan Province
TH-12|Nonthaburi Province
TH-13|Pathum Thani Province
TH-14|Phra Nakhon Si Ayutthaya Province
TH-15|Ang Thong Province
TH-16|Lop Buri Province
TH-17|Sing Buri Province
TH-18|Chai Nat Province
TH-19|Saraburi Province
TH-20|Chon Buri Province
TH-21|Rayong Province
TH-22|Chanthaburi Province
TH-23|Trat Province
TH-24|Chachoengsao Province
TH-25|Prachin Buri Province
TH-26|Nakhon Nayok Province
TH-27|Sa Kaeo Province
TH-30|Nakhon Ratchasima Province
TH-31|Buri Ram Province
TH-32|Surin Province
TH-33|Si Sa Ket Province
TH-34|Ubon Ratchathani Province
TH-35|Yasothon Province
TH-36|Chaiyaphum Province
TH-37|Amnat Charoen Province
TH-39|Nong Bua Lam Phu Province
TH-40|Khon Kaen Province
TH-41|Udon Thani Province
TH-42|Loei Province
TH-43|Nong Khai Province
TH-44|Maha Sarakham Province
TH-45|Roi Et Province
TH-46|Kalasin Province
TH-47|Sakon Nakhon Province
TH-48|Nakhon Phanom Province
TH-49|Mukdahan Province
TH-50|Chiang Mai Province
TH-51|Lamphun Province
TH-52|Lampang Province
TH-53|Uttaradit Province
TH-54|Phrae Province
TH-55|Nan Province
TH-56|Phayao Province
TH-57|Chiang Rai Province
TH-58|Mae Hong Son Province
TH-60|Nakhon Sawan Province
TH-61|Uthai Thani Province
TH-62|Kamphaeng Phet Province
TH-63|Tak Province
TH-64|Sukhothai Province
TH-65|Phitsanulok Province
TH-66|Phichit Province
TH-67|Phetchabun Province
TH-70|Ratchaburi Province
TH-71|Kanchanaburi Province
TH-72|Suphan Buri Province
TH-73|Nakhon Pathom Province
TH-74|Samut Sakhon Province
TH-75|Samut Songkhram Province
TH-76|Phetchaburi Province
TH-77|Prachuap Khiri Khan Province
TH-80|Nakhon Si Thammarat Province
TH-81|Krabi Province
TH-82|Phang Nga Province
TH-83|Phuket Province
TH-84|Surat Thani Province
TH-85|Ranong Province
TH-86|Chumphon Province
TH-90|Songkhla Province
TH-91|Satun Province
TH-92|Trang Province
TH-93|Phattalung Province
TH-94|Pattani Province
TH-95|Yala Province
TH-96|Narathiwat Province
TH-S|Pattaya Province
TH-U-A|
TH-10|Bangkok Province
TH-11|Samut Prakan Province
TH-12|Nonthaburi Province
TH-13|Pathum Thani Province
TH-14|Phra Nakhon Si Ayutthaya Province
TH-15|Ang Thong Province
TH-16|Lop Buri Province
TH-17|Sing Buri Province
TH-18|Chai Nat Province
TH-19|Saraburi Province
TH-20|Chon Buri Province
TH-21|Rayong Province
TH-22|Chanthaburi Province
TH-23|Trat Province
TH-24|Chachoengsao Province
TH-25|Prachin Buri Province
TH-26|Nakhon Nayok Province
TH-27|Sa Kaeo Province
TH-30|Nakhon Ratchasima Province
TH-31|Buri Ram Province
TH-32|Surin Province
TH-33|Si Sa Ket Province
TH-34|Ubon Ratchathani Province
TH-35|Yasothon Province
TH-36|Chaiyaphum Province
TH-37|Amnat Charoen Province
TH-39|Nong Bua Lam Phu Province
TH-40|Khon Kaen Province
TH-41|Udon Thani Province
TH-42|Loei Province
TH-43|Nong Khai Province
TH-44|Maha Sarakham Province
TH-45|Roi Et Province
TH-46|Kalasin Province
TH-47|Sakon Nakhon Province
TH-48|Nakhon Phanom Province
TH-49|Mukdahan Province
TH-50|Chiang Mai Province
TH-51|Lamphun Province
TH-52|Lampang Province
TH-53|Uttaradit Province
TH-54|Phrae Province
TH-55|Nan Province
TH-56|Phayao Province
TH-57|Chiang Rai Province
TH-58|Mae Hong Son Province
TH-60|Nakhon Sawan Province
TH-61|Uthai Thani Province
TH-62|Kamphaeng Phet Province
TH-63|Tak Province
TH-64|Sukhothai Province
TH-65|Phitsanulok Province
TH-66|Phichit Province
TH-67|Phetchabun Province
TH-70|Ratchaburi Province
TH-71|Kanchanaburi Province
TH-72|Suphan Buri Province
TH-73|Nakhon Pathom Province
TH-74|Samut Sakhon Province
TH-75|Samut Songkhram Province
TH-76|Phetchaburi Province
TH-77|Prachuap Khiri Khan Province
TH-80|Nakhon Si Thammarat Province
TH-81|Krabi Province
TH-82|Phang Nga Province
TH-83|Phuket Province
TH-84|Surat Thani Province
TH-85|Ranong Province
TH-86|Chumphon Province
TH-90|Songkhla Province
TH-91|Satun Province
TH-92|Trang Province
TH-93|Phattalung Province
TH-94|Pattani Province
TH-95|Yala Province
TH-96|Narathiwat Province
TH-S|Pattaya Province
TH-U-A|
TJ-GB|Gorno-Badakhshan Autonomous Province
TJ-KT|Khatlon Province
TJ-RR|Region of Republican Subordination
TJ-SU|Sughd Province
TJ-U-A|
TJ-GB|Gorno-Badakhshan Autonomous Province
TJ-KT|Khatlon Province
TJ-RR|Region of Republican Subordination
TJ-SU|Sughd Province
TJ-U-A|
TK-U-A|
TK-U-A|
TL-AL|Aileu
TL-AN|Ainaro
TL-BA|Baucau
TL-BO|Bobonaro
TL-CO|Cova Lima
TL-DI|Dili
TL-ER|Ermera
TL-LA|Lautém
TL-LI|Liquica
TL-MF|Manafahi
TL-MT|Manatuto
TL-OE|Oecussi
TL-U-A|
TL-VI|Viqueque
TL-AL|Aileu
TL-AN|Ainaro
TL-BA|Baucau
TL-BO|Bobonaro
TL-CO|Cova Lima
TL-DI|Dili
TL-ER|Ermera
TL-LA|Lautém
TL-LI|Liquica
TL-MF|Manafahi
TL-MT|Manatuto
TL-OE|Oecussi
TL-U-A|
TL-VI|Viqueque
TM-A|Ahal
TM-B|Balkan
TM-D|Da?oguz
TM-L|Lebap
TM-M|Mary
TM-U-A|
TM-A|Ahal
TM-B|Balkan
TM-D|Da?oguz
TM-L|Lebap
TM-M|Mary
TM-U-A|
TN-11|Tunis Governorate
TN-12|Ariana Governorate
TN-13|Ben Arous Governorate
TN-14|Manouba Governorate
TN-21|Nabeul Governorate
TN-22|Zaghouan Governorate
TN-23|Bizerte Governorate
TN-31|Béja Governorate
TN-32|Jendouba Governorate
TN-33|Kef Governorate
TN-34|Siliana Governorate
TN-41|Kairouan Governorate
TN-42|Kasserine Governorate
TN-43|Sidi Bou Zid Governorate
TN-51|Sousse Governorate
TN-52|Monastir Governorate
TN-53|Mahdia Governorate
TN-61|Sfax Governorate
TN-71|Gafsa Governorate
TN-72|Tozeur Governorate
TN-73|Kebili Governorate
TN-81|Gabès Governorate
TN-82|Medenine Governorate
TN-83|Tataouine Governorate
TN-U-A|
TN-11|Tunis Governorate
TN-12|Ariana Governorate
TN-13|Ben Arous Governorate
TN-14|Manouba Governorate
TN-21|Nabeul Governorate
TN-22|Zaghouan Governorate
TN-23|Bizerte Governorate
TN-31|Béja Governorate
TN-32|Jendouba Governorate
TN-33|Kef Governorate
TN-34|Siliana Governorate
TN-41|Kairouan Governorate
TN-42|Kasserine Governorate
TN-43|Sidi Bou Zid Governorate
TN-51|Sousse Governorate
TN-52|Monastir Governorate
TN-53|Mahdia Governorate
TN-61|Sfax Governorate
TN-71|Gafsa Governorate
TN-72|Tozeur Governorate
TN-73|Kebili Governorate
TN-81|Gabès Governorate
TN-82|Medenine Governorate
TN-83|Tataouine Governorate
TN-U-A|
TO-01|Eua
TO-02|Ha'apai
TO-03|Niuas
TO-04|Tongatapu
TO-05|Vava'
TO-U-A|
TO-01|Eua
TO-02|Ha'apai
TO-03|Niuas
TO-04|Tongatapu
TO-05|Vava'
TO-U-A|
TR-01|Adana
TR-02|Ad?yaman
TR-03|Afyonkarahisar
TR-04|A?r?
TR-05|Amasya
TR-06|Ankara
TR-07|Antalya
TR-08|Artvin
TR-09|Aydin
TR-10|Bal?kesir
TR-11|Bilecik
TR-12|Bingöl
TR-13|Bitlis
TR-14|Bolu
TR-15|Burdur
TR-16|Bursa
TR-17|Çanakkale
TR-18|Çank?r?
TR-19|Çorum
TR-20|Denizli
TR-21|Diyarbakir
TR-22|Edirne
TR-23|Elaz??
TR-24|Erzincan
TR-25|Erzurum
TR-26|Eski?ehir
TR-27|Gaziantep
TR-28|Giresun
TR-29|Gümü?hane
TR-30|Hakkâri
TR-31|Hatay
TR-32|Isparta
TR-33|Icel
TR-34|?stanbul
TR-35|?zmir
TR-36|Kars
TR-37|Kastamonu
TR-38|Kayseri
TR-39|Kirklareli
TR-40|K?r?ehir
TR-41|Kocaeli
TR-42|Konya
TR-43|Kütahya
TR-44|Malatya
TR-45|Manisa
TR-46|Kahramanmara?
TR-47|Mardin
TR-48|Mu?la
TR-49|Mu?
TR-50|Nev?ehir
TR-51|Ni?de
TR-52|Ordu
TR-53|Rize
TR-54|Sakarya
TR-55|Samsun
TR-56|Siirt
TR-57|Sinop
TR-58|Sivas
TR-59|Tekirda?
TR-60|Tokat
TR-61|Trabzon
TR-62|Tunceli
TR-63|?anl?urfa
TR-64|U?ak
TR-65|Van
TR-66|Yozgat
TR-67|Zonguldak
TR-68|Aksaray
TR-69|Bayburt
TR-70|Karaman
TR-71|Kirikkale
TR-72|Batman
TR-73|??rnak
TR-74|Bartin
TR-75|Ardahan
TR-76|I?d?r
TR-77|Yalova
TR-78|Karabük
TR-79|Kilis
TR-80|Osmaniye
TR-81|Düzce
TR-U-A|
TR-01|Adana
TR-02|Ad?yaman
TR-03|Afyonkarahisar
TR-04|A?r?
TR-05|Amasya
TR-06|Ankara
TR-07|Antalya
TR-08|Artvin
TR-09|Aydin
TR-10|Bal?kesir
TR-11|Bilecik
TR-12|Bingöl
TR-13|Bitlis
TR-14|Bolu
TR-15|Burdur
TR-16|Bursa
TR-17|Çanakkale
TR-18|Çank?r?
TR-19|Çorum
TR-20|Denizli
TR-21|Diyarbakir
TR-22|Edirne
TR-23|Elaz??
TR-24|Erzincan
TR-25|Erzurum
TR-26|Eski?ehir
TR-27|Gaziantep
TR-28|Giresun
TR-29|Gümü?hane
TR-30|Hakkâri
TR-31|Hatay
TR-32|Isparta
TR-33|Icel
TR-34|?stanbul
TR-35|?zmir
TR-36|Kars
TR-37|Kastamonu
TR-38|Kayseri
TR-39|Kirklareli
TR-40|K?r?ehir
TR-41|Kocaeli
TR-42|Konya
TR-43|Kütahya
TR-44|Malatya
TR-45|Manisa
TR-46|Kahramanmara?
TR-47|Mardin
TR-48|Mu?la
TR-49|Mu?
TR-50|Nev?ehir
TR-51|Ni?de
TR-52|Ordu
TR-53|Rize
TR-54|Sakarya
TR-55|Samsun
TR-56|Siirt
TR-57|Sinop
TR-58|Sivas
TR-59|Tekirda?
TR-60|Tokat
TR-61|Trabzon
TR-62|Tunceli
TR-63|?anl?urfa
TR-64|U?ak
TR-65|Van
TR-66|Yozgat
TR-67|Zonguldak
TR-68|Aksaray
TR-69|Bayburt
TR-70|Karaman
TR-71|Kirikkale
TR-72|Batman
TR-73|??rnak
TR-74|Bartin
TR-75|Ardahan
TR-76|I?d?r
TR-77|Yalova
TR-78|Karabük
TR-79|Kilis
TR-80|Osmaniye
TR-81|Düzce
TR-U-A|
TT-ARI|Arima
TT-CHA|Chaguanas
TT-CTT|Couva-Tabaquite-Talparo
TT-DMN|Diego Martin
TT-ETO|Eastern Tobago
TT-PED|Penal-Debe
TT-POS|Port of Spain
TT-PRT|Princes Town
TT-PTF|Point Fortin
TT-RCM|Rio Claro-Mayaro
TT-SFO|San Fernando
TT-SGE|Sangre Grande
TT-SIP|Siparia
TT-SJL|San Juan-Laventille
TT-TUP|Tunapuna-Piarco
TT-U-A|
TT-WTO|Western Tobago
TT-ARI|Arima
TT-CHA|Chaguanas
TT-CTT|Couva-Tabaquite-Talparo
TT-DMN|Diego Martin
TT-ETO|Eastern Tobago
TT-PED|Penal-Debe
TT-POS|Port of Spain
TT-PRT|Princes Town
TT-PTF|Point Fortin
TT-RCM|Rio Claro-Mayaro
TT-SFO|San Fernando
TT-SGE|Sangre Grande
TT-SIP|Siparia
TT-SJL|San Juan-Laventille
TT-TUP|Tunapuna-Piarco
TT-U-A|
TT-WTO|Western Tobago
TV-FUN|Funafuti
TV-NIT|Niutao
TV-NIU|Nui
TV-NKF|Nukufetau
TV-NKL|Nukulaelae
TV-NMA|Nanumea
TV-NMG|Nanumanga
TV-U-A|
TV-VAI|Vaitupu
TV-FUN|Funafuti
TV-NIT|Niutao
TV-NIU|Nui
TV-NKF|Nukufetau
TV-NKL|Nukulaelae
TV-NMA|Nanumea
TV-NMG|Nanumanga
TV-U-A|
TV-VAI|Vaitupu
TW-CHA|Changhua County
TW-CYI|Chiayi (city)
TW-CYQ|Chiayi County
TW-HSQ|Hsinchu County
TW-HSZ|Hsinchu (city)
TW-HUA|Hualien County
TW-ILA|Ilan County
TW-KEE|Keelung (city)
TW-KHH|Kaohsiung (municipality)
TW-KHQ|Kaohsiung County
TW-MIA|Miaoli County
TW-NAN|Nantou County
TW-PEN|Penghu County
TW-PIF|Pingtung County
TW-TAO|Taoyuan County
TW-TNN|Tainan City
TW-TNQ|Tainan County
TW-TPE|Taipei (municipality)
TW-TPQ|Taipei County
TW-TTT|Taitung County
TW-TXG|Taichung (city)
TW-TXQ|Taichung County
TW-U-A|
TW-X-KM|Kinmen County
TW-X-LK|Lienchiang County
TW-YUN|Yunlin County
TW-CHA|Changhua County
TW-CYI|Chiayi (city)
TW-CYQ|Chiayi County
TW-HSQ|Hsinchu County
TW-HSZ|Hsinchu (city)
TW-HUA|Hualien County
TW-ILA|Ilan County
TW-KEE|Keelung (city)
TW-KHH|Kaohsiung (municipality)
TW-KHQ|Kaohsiung County
TW-MIA|Miaoli County
TW-NAN|Nantou County
TW-PEN|Penghu County
TW-PIF|Pingtung County
TW-TAO|Taoyuan County
TW-TNN|Tainan City
TW-TNQ|Tainan County
TW-TPE|Taipei (municipality)
TW-TPQ|Taipei County
TW-TTT|Taitung County
TW-TXG|Taichung (city)
TW-TXQ|Taichung County
TW-U-A|
TW-X-KM|Kinmen County
TW-X-LK|Lienchiang County
TW-YUN|Yunlin County
TZ-01|Arusha
TZ-02|Dar-es-Salaam
TZ-03|Dodoma
TZ-04|Iringa
TZ-05|Kagera
TZ-06|Kaskazini Pemba
TZ-07|Kaskazini Unguja
TZ-08|Xigoma
TZ-09|Kilimanjaro
TZ-10|Rusini Pemba
TZ-11|Kusini Unguja
TZ-12|Lindi
TZ-13|Mara
TZ-14|Mbeya
TZ-15|Mjini Magharibi
TZ-16|Morogoro
TZ-17|Mtwara
TZ-18|Mwanza
TZ-19|Pwani
TZ-20|Rukwa
TZ-21|Ruvuma
TZ-22|Shinyanga
TZ-23|Singida
TZ-24|Tabora
TZ-25|Tanga
TZ-26|Manyara
TZ-U-A|
TZ-01|Arusha
TZ-02|Dar-es-Salaam
TZ-03|Dodoma
TZ-04|Iringa
TZ-05|Kagera
TZ-06|Kaskazini Pemba
TZ-07|Kaskazini Unguja
TZ-08|Xigoma
TZ-09|Kilimanjaro
TZ-10|Rusini Pemba
TZ-11|Kusini Unguja
TZ-12|Lindi
TZ-13|Mara
TZ-14|Mbeya
TZ-15|Mjini Magharibi
TZ-16|Morogoro
TZ-17|Mtwara
TZ-18|Mwanza
TZ-19|Pwani
TZ-20|Rukwa
TZ-21|Ruvuma
TZ-22|Shinyanga
TZ-23|Singida
TZ-24|Tabora
TZ-25|Tanga
TZ-26|Manyara
TZ-U-A|
UA-05|Vinnytsia
UA-07|Volyn
UA-09|Luhansk
UA-12|Dnipropetrovsk
UA-14|Donetsk
UA-18|Zhytomyr
UA-19|Rivne
UA-21|Zakarpattia
UA-23|Zaporizhia
UA-26|Ivano-Frankivsk
UA-30|Kiev (city)
UA-32|Kiev
UA-35|Kirovohrad
UA-40|Sevastopol (city)
UA-43|Crimea
UA-46|Lviv
UA-48|Mykolaiv
UA-51|Odessa
UA-53|Poltava
UA-56|Rivnens'ka Oblast'
UA-59|Sumy
UA-61|Ternopil
UA-63|Kharkiv
UA-65|Kherson
UA-68|Khmelnytskyi
UA-71|Cherkasy
UA-74|Chernihiv
UA-77|Chernivtsi
UA-U-A|
UA-05|Vinnytsia
UA-07|Volyn
UA-09|Luhansk
UA-12|Dnipropetrovsk
UA-14|Donetsk
UA-18|Zhytomyr
UA-19|Rivne
UA-21|Zakarpattia
UA-23|Zaporizhia
UA-26|Ivano-Frankivsk
UA-30|Kiev (city)
UA-32|Kiev
UA-35|Kirovohrad
UA-40|Sevastopol (city)
UA-43|Crimea
UA-46|Lviv
UA-48|Mykolaiv
UA-51|Odessa
UA-53|Poltava
UA-56|Rivnens'ka Oblast'
UA-59|Sumy
UA-61|Ternopil
UA-63|Kharkiv
UA-65|Kherson
UA-68|Khmelnytskyi
UA-71|Cherkasy
UA-74|Chernihiv
UA-77|Chernivtsi
UA-U-A|
UG-101|Kalangala District
UG-102|Kampala District
UG-103|Kiboga District
UG-104|Luwero District
UG-105|Masaka District
UG-106|Mpigi District
UG-107|Mubende District
UG-108|Mukono District
UG-109|Nakasongola District
UG-110|Rakai District
UG-111|Sembabule District
UG-112|Kayunga District
UG-113|Wakiso District
UG-201|Bugiri District
UG-202|Busia District
UG-203|Iganga District
UG-204|Jinja District
UG-205|Kamuli District
UG-206|Kapchorwa District
UG-207|Katakwi District
UG-208|Kumi District
UG-209|Mbale District
UG-210|Pallisa District
UG-211|Soroti District
UG-212|Tororo District
UG-213|Kaberamaido District
UG-214|Mayuge District
UG-215|Sironko District
UG-301|Adjumani District
UG-302|Apac District
UG-303|Arua District
UG-304|Gulu District
UG-305|Kitgum District
UG-306|Kotido District
UG-307|Lira District
UG-308|Moroto District
UG-309|Moyo District
UG-310|Nebbi District
UG-311|Nakapiripirit District
UG-312|Pader District
UG-313|Yumbe District
UG-401|Bundibugyo District
UG-402|Bushenyi District
UG-403|Hoima District
UG-404|Kabale District
UG-405|Kabarole District
UG-406|Kasese District
UG-407|Kibaale District
UG-408|Kisoro District
UG-409|Masindi District
UG-410|Mbarara District
UG-411|Ntungamo District
UG-412|Rukungiri District
UG-413|Kamwenge District
UG-414|Kanungu District
UG-415|Kyenjojo District
UG-U-A|
UG-101|Kalangala District
UG-102|Kampala District
UG-103|Kiboga District
UG-104|Luwero District
UG-105|Masaka District
UG-106|Mpigi District
UG-107|Mubende District
UG-108|Mukono District
UG-109|Nakasongola District
UG-110|Rakai District
UG-111|Sembabule District
UG-112|Kayunga District
UG-113|Wakiso District
UG-201|Bugiri District
UG-202|Busia District
UG-203|Iganga District
UG-204|Jinja District
UG-205|Kamuli District
UG-206|Kapchorwa District
UG-207|Katakwi District
UG-208|Kumi District
UG-209|Mbale District
UG-210|Pallisa District
UG-211|Soroti District
UG-212|Tororo District
UG-213|Kaberamaido District
UG-214|Mayuge District
UG-215|Sironko District
UG-301|Adjumani District
UG-302|Apac District
UG-303|Arua District
UG-304|Gulu District
UG-305|Kitgum District
UG-306|Kotido District
UG-307|Lira District
UG-308|Moroto District
UG-309|Moyo District
UG-310|Nebbi District
UG-311|Nakapiripirit District
UG-312|Pader District
UG-313|Yumbe District
UG-401|Bundibugyo District
UG-402|Bushenyi District
UG-403|Hoima District
UG-404|Kabale District
UG-405|Kabarole District
UG-406|Kasese District
UG-407|Kibaale District
UG-408|Kisoro District
UG-409|Masindi District
UG-410|Mbarara District
UG-411|Ntungamo District
UG-412|Rukungiri District
UG-413|Kamwenge District
UG-414|Kanungu District
UG-415|Kyenjojo District
UG-U-A|
UM-67|Johnston Atoll
UM-71|Midway Islands
UM-76|Navassa Island
UM-79|Wake Island
UM-81|Baker Island
UM-84|Howland Island
UM-86|Jarvis Island
UM-89|Kingman Reef
UM-95|Palmyra Atoll
UM-U-A|
UM-67|Johnston Atoll
UM-71|Midway Islands
UM-76|Navassa Island
UM-79|Wake Island
UM-81|Baker Island
UM-84|Howland Island
UM-86|Jarvis Island
UM-89|Kingman Reef
UM-95|Palmyra Atoll
UM-U-A|
US-AK|Alaska
US-AL|Alabama
US-AR|Arkansas
US-AZ|Arizona
US-CA|California
US-CO|Colorado
US-CT|Connecticut
US-DC|District of Columbia
US-DE|Delaware
US-FL|Florida
US-GA|Georgia
US-HI|Hawaii
US-IA|Iowa
US-ID|Idaho
US-IL|Illinois
US-IN|Indiana
US-KS|Kansas
US-KY|Kentucky
US-LA|Louisiana
US-MA|Massachusetts
US-MD|Maryland
US-ME|Maine
US-MI|Michigan
US-MN|Minnesota
US-MO|Missouri
US-MS|Mississippi
US-MT|Montana
US-NC|North Carolina
US-ND|North Dakota
US-NE|Nebraska
US-NH|New Hampshire
US-NJ|New Jersey
US-NM|New Mexico
US-NV|Nevada
US-NY|New York
US-OH|Ohio
US-OK|Oklahoma
US-OR|Oregon
US-PA|Pennsylvania
US-RI|Rhode Island
US-SC|South Carolina
US-SD|South Dakota
US-TN|Tennessee
US-TX|Texas
US-U-A|
US-UT|Utah
US-VA|Virginia
US-VT|Vermont
US-WA|Washington
US-WI|Wisconsin
US-WV|West Virginia
US-WY|Wyoming
US-AK|Alaska
US-AL|Alabama
US-AR|Arkansas
US-AZ|Arizona
US-CA|California
US-CO|Colorado
US-CT|Connecticut
US-DC|District of Columbia
US-DE|Delaware
US-FL|Florida
US-GA|Georgia
US-HI|Hawaii
US-IA|Iowa
US-ID|Idaho
US-IL|Illinois
US-IN|Indiana
US-KS|Kansas
US-KY|Kentucky
US-LA|Louisiana
US-MA|Massachusetts
US-MD|Maryland
US-ME|Maine
US-MI|Michigan
US-MN|Minnesota
US-MO|Missouri
US-MS|Mississippi
US-MT|Montana
US-NC|North Carolina
US-ND|North Dakota
US-NE|Nebraska
US-NH|New Hampshire
US-NJ|New Jersey
US-NM|New Mexico
US-NV|Nevada
US-NY|New York
US-OH|Ohio
US-OK|Oklahoma
US-OR|Oregon
US-PA|Pennsylvania
US-RI|Rhode Island
US-SC|South Carolina
US-SD|South Dakota
US-TN|Tennessee
US-TX|Texas
US-U-A|
US-UT|Utah
US-VA|Virginia
US-VT|Vermont
US-WA|Washington
US-WI|Wisconsin
US-WV|West Virginia
US-WY|Wyoming
UY-AR|Artigas
UY-CA|Canelones
UY-CL|Cerro Largo
UY-CO|Colonia
UY-DU|Durazno
UY-FD|Florida
UY-FS|Flores
UY-LA|Lavalleja
UY-MA|Maldonado
UY-MO|Montevideo
UY-PA|Paysandu
UY-RN|Río Negro
UY-RO|Rocha
UY-RV|Rivera
UY-SA|Salto
UY-SJ|San José
UY-SO|Soriano
UY-TA|Tacuarembo
UY-TT|Treinta y Tres
UY-U-A|
UY-AR|Artigas
UY-CA|Canelones
UY-CL|Cerro Largo
UY-CO|Colonia
UY-DU|Durazno
UY-FD|Florida
UY-FS|Flores
UY-LA|Lavalleja
UY-MA|Maldonado
UY-MO|Montevideo
UY-PA|Paysandu
UY-RN|Río Negro
UY-RO|Rocha
UY-RV|Rivera
UY-SA|Salto
UY-SJ|San José
UY-SO|Soriano
UY-TA|Tacuarembo
UY-TT|Treinta y Tres
UY-U-A|
UZ-AN|Andijon
UZ-BU|Buxoro
UZ-FA|Farg'ona
UZ-JI|Jizzax
UZ-KH|Khorazm
UZ-NG|Namangan
UZ-NW|Navoiy
UZ-QA|Qashqadaryo
UZ-QR|Qoraqalpogiston Respublikasi
UZ-SA|Samarqand
UZ-SI|Sirdaryo
UZ-SU|Surxondaryo
UZ-TK|Toshkent
UZ-TO|Toshkent
UZ-U-A|
UZ-XO|Xorazm
UZ-AN|Andijon
UZ-BU|Buxoro
UZ-FA|Farg'ona
UZ-JI|Jizzax
UZ-KH|Khorazm
UZ-NG|Namangan
UZ-NW|Navoiy
UZ-QA|Qashqadaryo
UZ-QR|Qoraqalpogiston Respublikasi
UZ-SA|Samarqand
UZ-SI|Sirdaryo
UZ-SU|Surxondaryo
UZ-TK|Toshkent
UZ-TO|Toshkent
UZ-U-A|
UZ-XO|Xorazm
VA-U-A|
VA-U-A|
VC-01|Charlotte
VC-02|Saint Andrew
VC-03|Saint David
VC-04|Saint George
VC-05|Saint Patrick
VC-06|Grenadines
VC-U-A|
VC-01|Charlotte
VC-02|Saint Andrew
VC-03|Saint David
VC-04|Saint George
VC-05|Saint Patrick
VC-06|Grenadines
VC-U-A|
VE-A|Distrito Federal
VE-B|Anzoategui
VE-C|Apure
VE-D|Aragua
VE-E|Barinas
VE-F|Bolívar
VE-G|Carabobo
VE-H|Cojedes
VE-I|Falcon
VE-J|Guarico
VE-K|Lara
VE-L|Merida
VE-M|Miranda
VE-N|Monagas
VE-O|Nueva Esparta
VE-P|Portuguesa
VE-R|Sucre
VE-S|Tachira
VE-T|Trujillo
VE-U|Yaracuy
VE-U-A|
VE-V|Zulia
VE-W|Dependencias Federales
VE-X|Vargas
VE-Y|Delta Amacuro
VE-Z|Amazonas
VE-A|Distrito Federal
VE-B|Anzoategui
VE-C|Apure
VE-D|Aragua
VE-E|Barinas
VE-F|Bolívar
VE-G|Carabobo
VE-H|Cojedes
VE-I|Falcon
VE-J|Guarico
VE-K|Lara
VE-L|Merida
VE-M|Miranda
VE-N|Monagas
VE-O|Nueva Esparta
VE-P|Portuguesa
VE-R|Sucre
VE-S|Tachira
VE-T|Trujillo
VE-U|Yaracuy
VE-U-A|
VE-V|Zulia
VE-W|Dependencias Federales
VE-X|Vargas
VE-Y|Delta Amacuro
VE-Z|Amazonas
VG-U-A|
VG-U-A|
VI-U-A|
VI-U-A|
VN-01|Lai Chau
VN-02|Lao Cai
VN-03|Ha Giang
VN-04|Cao Bang
VN-05|Son La
VN-06|Yen Bai
VN-07|Tuyen Quang
VN-09|Lang Son
VN-13|Quang Ninh
VN-14|Hoa Binh
VN-15|Ha Tay
VN-18|Ninh Binh
VN-20|Thai Binh
VN-21|Thanh Hoa
VN-22|Nghe An
VN-23|Ha Tinh
VN-24|Quang Binh
VN-25|Quang Tri
VN-26|Thua Thien-Hue
VN-27|Quang Nam
VN-28|Kon Tum
VN-29|Quang Ngai
VN-30|Gia Lai
VN-31|Binh Dinh
VN-32|Phu Yen
VN-33|Dac Lac
VN-34|Khanh Hoa
VN-35|Lam Dong
VN-36|Ninh Thuan
VN-37|Tay Ninh
VN-39|Dong Nai
VN-40|Binh Thuan
VN-41|Long An
VN-43|Ba Ria - Vung Tau
VN-44|An Giang
VN-45|Dong Thap
VN-46|Tien Giang
VN-47|Kien Giang
VN-48|Can Tho
VN-49|Vinh Long
VN-50|Ben Tre
VN-51|Tra Vinh
VN-52|Soc Trang
VN-53|Bac Can
VN-54|Bac Giang
VN-55|Bac Lieu
VN-56|Bac Ninh
VN-57|Binh Duong
VN-58|Binh Phuoc
VN-59|Ca Mau
VN-60|thanh pho Da Nang
VN-61|Hai Duong
VN-62|thanh pho Hai Phong
VN-63|Ha Nam
VN-64|thu do Ha Noi
VN-65|thanh pho Ho Chi Minh
VN-66|Hung Yen
VN-67|Nam Dinh
VN-68|Phu Tho
VN-69|Thai Nguyen
VN-70|Vinh Phuc
VN-U-A|
VN-01|Lai Chau
VN-02|Lao Cai
VN-03|Ha Giang
VN-04|Cao Bang
VN-05|Son La
VN-06|Yen Bai
VN-07|Tuyen Quang
VN-09|Lang Son
VN-13|Quang Ninh
VN-14|Hoa Binh
VN-15|Ha Tay
VN-18|Ninh Binh
VN-20|Thai Binh
VN-21|Thanh Hoa
VN-22|Nghe An
VN-23|Ha Tinh
VN-24|Quang Binh
VN-25|Quang Tri
VN-26|Thua Thien-Hue
VN-27|Quang Nam
VN-28|Kon Tum
VN-29|Quang Ngai
VN-30|Gia Lai
VN-31|Binh Dinh
VN-32|Phu Yen
VN-33|Dac Lac
VN-34|Khanh Hoa
VN-35|Lam Dong
VN-36|Ninh Thuan
VN-37|Tay Ninh
VN-39|Dong Nai
VN-40|Binh Thuan
VN-41|Long An
VN-43|Ba Ria - Vung Tau
VN-44|An Giang
VN-45|Dong Thap
VN-46|Tien Giang
VN-47|Kien Giang
VN-48|Can Tho
VN-49|Vinh Long
VN-50|Ben Tre
VN-51|Tra Vinh
VN-52|Soc Trang
VN-53|Bac Can
VN-54|Bac Giang
VN-55|Bac Lieu
VN-56|Bac Ninh
VN-57|Binh Duong
VN-58|Binh Phuoc
VN-59|Ca Mau
VN-60|thanh pho Da Nang
VN-61|Hai Duong
VN-62|thanh pho Hai Phong
VN-63|Ha Nam
VN-64|thu do Ha Noi
VN-65|thanh pho Ho Chi Minh
VN-66|Hung Yen
VN-67|Nam Dinh
VN-68|Phu Tho
VN-69|Thai Nguyen
VN-70|Vinh Phuc
VN-U-A|
VU-MAP|Malampa
VU-PAM|Penama
VU-SAM|Sanma
VU-SEE|Shefa
VU-TAE|Tafea
VU-TOB|Torba
VU-U-A|
VU-MAP|Malampa
VU-PAM|Penama
VU-SAM|Sanma
VU-SEE|Shefa
VU-TAE|Tafea
VU-TOB|Torba
VU-U-A|
WF-U-A|
WF-U-A|
WS-AA|A'ana District
WS-AL|Aiga-i-le-Tai District
WS-AT|Atua District
WS-FA|Fa'aaaleleaga District
WS-GE|Gaga'emauga District
WS-GI|Gagaifomauga District
WS-PA|Palauli District
WS-SA|Satupa'itea District
WS-TU|Tuamasaga District
WS-U-A|
WS-VF|Va'a-o-Fonoti District
WS-VS|Vaisigano District
WS-AA|A'ana District
WS-AL|Aiga-i-le-Tai District
WS-AT|Atua District
WS-FA|Fa'aaaleleaga District
WS-GE|Gaga'emauga District
WS-GI|Gagaifomauga District
WS-PA|Palauli District
WS-SA|Satupa'itea District
WS-TU|Tuamasaga District
WS-U-A|
WS-VF|Va'a-o-Fonoti District
WS-VS|Vaisigano District
YE-AB|Abyan Governorate
YE-AD|Adan Governorate
YE-AM|Amran Governorate
YE-BA|Al Bayda' Governorate
YE-DA|Ad Dali Governorate
YE-DH|Dhamar Governorate
YE-HD|Hadramawt Governorate
YE-HJ|Hajjah Governorate
YE-HU|Al Hydaydah Governorate
YE-IB|Ibb Governorate
YE-JA|Al Jawf Governorate
YE-LA|Lahij Governorate
YE-MA|Ma'rib Governorate
YE-MR|Al Mahrah Governorate
YE-MU|Al Hudaydah Governorate
YE-MW|Al Mahwit Governorate
YE-SD|Sa'dah Governorate
YE-SH|Shabwah Governorate
YE-SN|San'a' Governorate
YE-TA|Ta'izz Governorate
YE-U-A|
YE-AB|Abyan Governorate
YE-AD|Adan Governorate
YE-AM|Amran Governorate
YE-BA|Al Bayda' Governorate
YE-DA|Ad Dali Governorate
YE-DH|Dhamar Governorate
YE-HD|Hadramawt Governorate
YE-HJ|Hajjah Governorate
YE-HU|Al Hydaydah Governorate
YE-IB|Ibb Governorate
YE-JA|Al Jawf Governorate
YE-LA|Lahij Governorate
YE-MA|Ma'rib Governorate
YE-MR|Al Mahrah Governorate
YE-MU|Al Hudaydah Governorate
YE-MW|Al Mahwit Governorate
YE-SD|Sa'dah Governorate
YE-SH|Shabwah Governorate
YE-SN|San'a' Governorate
YE-TA|Ta'izz Governorate
YE-U-A|
YT-U-A|
YT-U-A|
ZA-EC|Eastern Cape
ZA-FS|Free State
ZA-GT|Gauteng
ZA-MP|Mpumalanga
ZA-NC|Northern Cape
ZA-NL|Kwazulu-Natal
ZA-NP|Limpopo
ZA-NW|North-West
ZA-U-A|
ZA-WC|Western Cape
ZA-EC|Eastern Cape
ZA-FS|Free State
ZA-GT|Gauteng
ZA-MP|Mpumalanga
ZA-NC|Northern Cape
ZA-NL|Kwazulu-Natal
ZA-NP|Limpopo
ZA-NW|North-West
ZA-U-A|
ZA-WC|Western Cape
ZM-01|Western Province
ZM-02|Central Province
ZM-03|Eastern Province
ZM-04|Luapula Province
ZM-05|Northern Province
ZM-06|North-Western Province
ZM-07|Southern Province
ZM-08|Copperbelt Province
ZM-09|Lusaka Province
ZM-U-A|
ZM-01|Western Province
ZM-02|Central Province
ZM-03|Eastern Province
ZM-04|Luapula Province
ZM-05|Northern Province
ZM-06|North-Western Province
ZM-07|Southern Province
ZM-08|Copperbelt Province
ZM-09|Lusaka Province
ZM-U-A|
ZW-BU|Bulawayo
ZW-HA|Harare
ZW-MA|Manicaland
ZW-MC|Mashonaland Central
ZW-ME|Mashonaland East
ZW-MI|Midlands
ZW-MN|Matabeleland North
ZW-MS|Matabeleland South
ZW-MV|Masvingo
ZW-MW|Mashonaland West
ZW-U-A|
ZW-BU|Bulawayo
ZW-HA|Harare
ZW-MA|Manicaland
ZW-MC|Mashonaland Central
ZW-ME|Mashonaland East
ZW-MI|Midlands
ZW-MN|Matabeleland North
ZW-MS|Matabeleland South
ZW-MV|Masvingo
ZW-MW|Mashonaland West
ZW-U-A|
ZZ-U-A|
ZZ-U-A|
