AF|Afeganistão
ZA|África do Sul
AL|Albânia
DE|Alemanha
AD|Andorra
AO|Angola
AI|Anguilla
AQ|Antárctida
AG|Antigua e Barbuda
AN|Antilhas Holandesas
SA|Arábia Saudita
DZ|Argélia
AR|Argentina
AM|Arménia
AW|Aruba
AU|Austrália
AT|Áustria
AZ|Azerbeijão
BS|Bahamas
BH|Bahrain
BD|Bangladesh
BB|Barbados
BE|Bélgica
BZ|Belize
BJ|Benin
BM|Bermuda
BY|Bielo-Rússia
BO|Bolívia
BA|Bósnia-Herzegovina
BW|Botswana
BR|Brasil
BN|Brunei
BG|Bulgária
BF|Burkina Faso
BI|Burundi
BT|Butão
CV|Cabo Verde
CM|Camarões
KH|Cambodja
CA|Canadá
KZ|Cazaquistão
TD|Chade
CL|Chile
CN|China
CY|Chipre
CO|Colômbia
KM|Comores
KR|Coreia do Sul
CI|Costa do Marfim
CR|Costa Rica
HR|Croácia
CU|Cuba
DK|Dinamarca
DJ|Djibouti
DM|Dominica
EG|Egipto
SV|El Salvador
AE|Emiratos Árabes Unidos
EC|Equador
ER|Eritreia
SK|Eslováquia
SI|Eslovénia
ES|Espanha
FM|Estados Federados da Micronésia
US|Estados Unidos da América
EE|Estónia
ET|Etiópia
FJ|Fiji
PH|Filipinas
FI|Finlândia
FR|França
GA|Gabão
GM|Gâmbia
GH|Gana
GE|Geórgia
GI|Gibraltar
GR|Grécia
GD|Grenada
GL|Gronelândia
GP|Guadeloupe
GU|Guam
GT|Guatemala
GG|Guernsey
GY|Guiana
GF|Guiana Francesa
GQ|Guiné Equatorial
GW|Guiné-Bissau
GN|Guiné-Conacri
HT|Haiti
HN|Honduras
HK|Hong Kong
HU|Hungria
YE|Iémen
CX|Ilha Christmas
IM|Ilha de Man
NF|Ilha Norfolk
KY|Ilhas Cayman
CC|Ilhas Cocos
CK|Ilhas Cook
FO|Ilhas Faroe
GS|Ilhas Geórgia do Sul e Sandwich do Sul
FK|Ilhas Malvinas
MH|Ilhas Marshall
UM|Ilhas Menores Distantes dos Estados Unidos
SB|Ilhas Salomão
VI|Ilhas Virgens Americanas
VG|Ilhas Virgens Britânicas
IN|Índia
ID|Indonésia
IR|Irão
IQ|Iraque
IE|Irlanda
IS|Islândia
IL|Israel
IT|Itália
JM|Jamaica
JP|Japão
JE|Jersey
JO|Jordânia
KI|Kiribati
KS|Kosovo
KW|Kuwait
LA|Laos
LS|Lesoto
LV|Letónia
LB|Líbano
LR|Libéria
LY|Líbia
LI|Liechtenstein
LT|Lituânia
LU|Luxemburgo
MO|Macau
MG|Madagáscar
MY|Malásia
MW|Malawi
MV|Maldivas
ML|Mali
MT|Malta
MP|Marianas Setentrionais
MA|Marrocos
MQ|Martinica
MU|Maurícia
MR|Mauritânia
YT|Mayotte
MX|México
MZ|Moçambique
MD|Moldávia
MC|Mónaco
MN|Mongólia
ME|Montenegro
MS|Montserrat
MM|Myanmar (antiga Birmânia)
NA|Namíbia
NR|Nauru
NP|Nepal
NI|Nicarágua
NE|Níger
NG|Nigéria
NU|Niue
NO|Noruega
NC|Nova Caledónia
NZ|Nova Zelândia
OM|Oman
NL|Países Baixos
PW|Palau
PS|Palestina
PA|Panamá
PG|Papua-Nova Guiné
PK|Paquistão
PY|Paraguai
PE|Peru
PN|Pitcairn
PF|Polinésia Francesa
PL|Polónia
PR|Porto Rico
PT|Portugal
QA|Qatar
KE|Quénia
KG|Quirguistão
GB|Reino Unido da Grã-Bretanha e Irlanda do Norte
CF|República Centro-africana
CZ|República Checa
MK|República da Macedónia
KP|República Democrática da Coreia
CD|República Democrática do Congo
CG|República do Congo
DO|República Dominicana
RE|Reunião
RO|Roménia
RW|Ruanda
RU|Rússia
EH|Saara Ocidental
BL|Saint Barthélemy
MF|Saint Martin
PM|Saint Pierre et Miquelon
WS|Samoa
AS|Samoa Americana
SM|San Marino
SH|Santa Helena
LC|Santa Lúcia
KN|São Cristóvão e Névis
ST|São Tomé e Príncipe
VC|São Vicente e Granadinas
SN|Senegal
SL|Serra Leoa
RS|Sérvia
SC|Seychelles
SG|Singapura
SY|Síria
SO|Somália
SS|South Sudan
LK|Sri Lanka
SZ|Suazilândia
SD|Sudão
SE|Suécia
CH|Suíça
SR|Suriname
TH|Tailândia
TW|Taiwan
TJ|Tajiquistão
TZ|Tanzânia
TF|Terras Austrais e Antárticas Francesas
IO|Território Britânico do Oceano Índico
TL|Timor-Leste
TG|Togo
TO|Tonga
TK|Toquelau
TT|Trindade e Tobago
TN|Tunísia
TC|Turks e Caicos
TM|Turquemenistão
TR|Turquia
TV|Tuvalu
UA|Ucrânia
UG|Uganda
ZZ|Unknown or unassigned country
UY|Uruguai
UZ|Usbequistão
VU|Vanuatu
VA|Vaticano
VE|Venezuela
VN|Vietname
WF|Wallis e Futuna
ZM|Zâmbia
ZW|Zimbabwe
