<?php
##########################
# IPis - ©2011           #
# http://www.ipis.com.br # ---------------------------- ATENCAO ---------------------------
# Code by Fernando Lima  #      Alterar este arquivo de configuração manualmente pode
# info@ipis.com.br       #   inutilizar algumas funcoes e impedir o acesso a este sistema
# (55)(84) 8833-2668     #
##########################

/**************************************

HAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHA!
TRY AGAIN, KKKKKKKKKKK!

HAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHA!
TRY AGAIN, KKKKKKKKKKK!

HAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHA!
TRY AGAIN, KKKKKKKKKKK!

HAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHA!
TRY AGAIN, KKKKKKKKKKK!

HAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHA!
TRY AGAIN, KKKKKKKKKKK!

HAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHA!
TRY AGAIN, KKKKKKKKKKK!

HAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHA!
TRY AGAIN, KKKKKKKKKKK!

HAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHA!
TRY AGAIN, KKKKKKKKKKK!

HAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHA!
TRY AGAIN, KKKKKKKKKKK!

HAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHA!
TRY AGAIN, KKKKKKKKKKK!

HAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHA!
TRY AGAIN, KKKKKKKKKKK!

HAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHA!
TRY AGAIN, KKKKKKKKKKK!

HAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHA!
TRY AGAIN, KKKKKKKKKKK!

HAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHA!
TRY AGAIN, KKKKKKKKKKK!

**************************************/
?>
